app/app.js
app/components/dashboard/master-ctrl.js
app/components/docker/docker.html
app/components/docker/dockerController.js
app/shared/services.js
dockerui.go
gruntFile.js
index.html

The `/config` endpoint is now exposed in the `dockerui.go` HTTP server. This will allow future options to be exposed.
The UI can now poll the config endpoint.
When the `dockerui.go` is started with the `-s` flag, it will display a Swarm tab. Else it will display a Docker tab with info about the engine.

Add configuration endpoint and -s flag for Swarm

---

app/components/templates/templates.html
assets/css/app.css

This PR uses the field `description` instead of the field `comment` for the templates.

refactor(templates): rename field comment to description

---

app/components/templates/templates.html
app/components/templates/templatesController.js

This PR brings select to the templates fields.
When an environment variable type is `container`, a select will automatically created in the UI listing all the running containers.
When creating the container, the container hostname will be used if swarm mode enabled and using an overlay network otherwise the container IP address will be used.
Close #158

feat(templates): support select for env fields with type 'container'

---

build/windows/microsoftservercore/Dockerfile
build/windows/nanoserver/Dockerfile

The Windows docker images could be much smaller if the standard base images are used to COPY all files into it.

Use microsoft base images

---

build.sh
gruntFile.js

With this PR you can build a Linux ARM binary as well.
``` bash
grunt release-arm
export DOCKER_HOST=tcp://<ip-address-of-your-raspbery-pi>:2375
docker build -t portainer -f build/linux/Dockerfile .
docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer
open http://<ip-address-of-your-raspbery-pi>:9000
```
Would be great if you push the portainer/portainer:arm (or portainer/portainer:armhf) docker image as well.

Add Linux ARM support

---

app/components/container/container.html
app/components/containerConsole/containerConsole.html
app/components/containerLogs/containerlogs.html
app/components/createContainer/createcontainer.html
app/components/createNetwork/createnetwork.html
app/components/createService/createservice.html
app/components/createVolume/createvolume.html
app/components/image/image.html
app/components/network/network.html
app/components/service/service.html
app/components/stats/stats.html
app/components/task/task.html

- change the first item in breadcrumbs to a clickable url
When playing around with portainer I found that that I was missing the ability to click on the first item in the breadcrumbs to navigate to it. More so, because the last item often is clickable, it felt weird without it.

feat: add clickable url in breadcrumbs

---

app/components/container/containerController.js

- When clicking leave network you will now stay on the container page
- The page will be refreshed
Fix #336.

Fix leaving a network in container view

---

app/components/service/service.html
app/components/service/serviceController.js

- This PR also contains a commit from #305 due to the changes in saving / editing a service. I can update / change as/when needed.
- Add editable labels based off the implementation done in #306. It has some overlap with the implementation done for environment variables, which may need to be addressed before this gets merged. I can do that if desired, after #305.
How it looks:

Add editable labels for services

---

app/app.js
app/components/container/container.html
app/components/container/containerController.js
app/components/containers/containers.html
app/components/containers/containersController.js
app/components/events/events.html
app/components/events/eventsController.js
app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/service/service.html
app/components/service/serviceController.js
app/components/services/services.html
app/components/services/servicesController.js
app/components/stats/stats.html
app/components/stats/statsController.js
app/components/swarm/swarm.html
app/components/swarm/swarmController.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js
app/shared/services.js
assets/css/app.css
bower.json
gruntFile.js

This PR brings pagination for all object lists.
Default value per page is 20 objects for containers, images, networks, volumes, events, services and tasks.
10 objects per page for processes in stats view and 15 for app templates.
Close #351

feat(UX): add pagination for all object lists

---

app/components/templates/templates.html
app/components/templates/templatesController.js

`$index` was causing issues as it was only the index of the currently visible items.
I chose `index` instead of `id` to as to not cause headache down the line incase the Template objects actually get IDs.
Fixes #361

#361 fix(templates): fixes an issue regarding template selection when paged

---

app/components/volumes/volumesController.js

Volumes is undefined when no volumes are present. The loading text will remain until volumes is defined. Fix #368.

Fix loading text displayed when no volumes present

---

app/components/container/containerController.js
app/components/createContainer/createContainerController.js
app/components/createService/createServiceController.js
app/components/image/imageController.js
app/components/images/imagesController.js
app/components/templates/templatesController.js
app/shared/helpers.js

This PR brings support for the field `registry` in any template definition. This field is optional and if not defined, portainer will pull the template image from the Dockerhub.
Documentation of the templates must be updated.
Close #311

feat(templates): add support for the template registry field

---

api/http/docker_handler.go

This involves copying and modifying go's httputil.NewSingleHostReverseProxy, which is documented to (perhaps surprisingly) leave the Host header untouched. Instead, we set the Host header to the target host for the connection for the benefit of name based virtual host proxies that make use of this.
See golang/go#7618 and golang/go#10342

Connect to docker behind a name based virtual host proxy

---

app/components/network/network.html
app/components/network/networkController.js
app/shared/services.js

- shows all containers currently connected to the network
- abillity to disconect a container from the network
- fix error when a container is not connected to any networks
Example:
Close #404

feat(network): add list of containers in network

---

build.sh
gruntfile.js

Inspired by @StefanScherer on [PR#299](https://github.com/portainer/portainer/pull/299) I added aarch64 support using arm64 cross compiling flag and Go 1.7 and tested the result on a Pine64 cluster

feat(images): initial aarch64/arm64 support

---

app/components/endpoint/endpointController.js
app/shared/services.js

This is a fix to the issue #476

#476 fix(UX): Rename 'local' endpoint doesn't overwrite "unix://"

---

app/components/containers/containersController.js

Hello this is my first contribution for this awesome project.
This PR contains
* displaying "Container is already paused" message when `Container.pause` triggered on paused containers
Thanks
Close #182

#182 feat(containers): support container already pause message

---

app/components/createContainer/createContainerController.js

Fix #557 
https://github.com/deviantony/splitargs was introduced with https://github.com/portainer/portainer/pull/585

fix(container-creation): split the container command to a token array

---

api/cli/cli.go
api/cli/defaults.go
api/cli/defaults_windows.go
api/cmd/portainer/main.go
api/portainer.go
app/app.js
app/services/stateManager.js
gruntfile.js

This PR introduces the flag `--no-analytics` (defaults to false) which will disable Google Analytics in app.
It re-create the same behavior as the user opt-out feature in Google Analytics.
Close #600

feat(cli): add a --no-analytics flag to disable google analytics

---

app/components/images/images.html
app/components/images/imagesController.js
app/rest/image.js
app/services/modalService.js
assets/css/app.css
bower.json
gruntfile.js

Hello,
This MR implements #497
This is my first contribution on this project, I am volonteer to continue on #354, if this one is OK for you.
Cheers
Romain
Close #497

feat(image): add the ability to force remove an image (#497)

---

app/components/endpointInit/endpointInit.html

Addressed some confusion in: https://github.com/portainer/portainer/issues/450
I'm hoping this change would make it clear that Portainer works fine when running Linux containers on Docker for Mac/Win and with Toolbox.

Clarify 'Manage instance where Portainer is running' warning

---

api/http/endpoint_handler.go

fix(api): allow empty array when removing accesses to an endpoint

---

app/components/containers/containers.html
app/components/containers/containersController.js

Fixes [this issue](https://github.com/portainer/portainer/issues/624) with long container names & ids causing the table to run off the screen.
Love the project, wanted to get my feet wet so I read the contribution guidelines and picked something small on the list.

fix #624 (containers): truncate long names & ids in the containers view

---

build/windows/microsoftservercore/Dockerfile
build/windows/nanoserver/Dockerfile

Now that the builder images are using Golang 1.8 (introduced in https://github.com/portainer/golang-builder/commit/ff5108c031d90ebd02c450372212c45f4f8cb327) we can revert the VOLUME definition in the Windows Dockerfile.

fix(Dockerfiles): use a volume to store data

---

app/components/createVolume/createVolumeController.js
app/components/createVolume/createvolume.html
app/helpers/volumeHelper.js
app/services/infoService.js
app/services/volumeService.js

This PR brings the ability to select volume drivers from a dropdown. They are fetched directly from the Docker engine.
Also refactor the codes to use a cleaner controller/service approach in the volume-creation view.

feat(volume-creation): fetch volume drivers from the engine

---

api/http/server.go
api/http/templates_handler.go
app/app.js
app/components/sidebar/sidebar.html
app/components/templates/templates.html
app/components/templates/templatesController.js
app/helpers/templateHelper.js
app/models/template.js
app/services/templateService.js
assets/css/app.css
gruntfile.js

This PR creates a new sub-navigation tab in the sidebar under the App Templates section. This allows to display the container templates of LinuxServer.io (for now, only the templates related to the *Network* category).
Close #666

feat(templates): LinuxServer.io templates integration

---

api/cli/cli.go
api/cmd/portainer/main.go
api/portainer.go

This pull request allow users to specify an hash for the admin password from the command line. Fixes #428.
A pull request to update the documentation is coming soon but in the meantime a couple of caveats:
- The password can be generate using the command `htpasswd -nb -B admin <password>`
- If portainer is run from the binary escape the `$` in the password hash with `\` to avoid shell expansion
- If portainer is run from inside a container escape the `$` in the password hash with `\\` to avoid expansion from the shell outside and inside the container.

fix(cli): Allow setting admin password from CLI

---

app/components/templates/templates.html
app/models/template.js

This PR brings support for the `note` field in any template definition. This field will be displayed if existing otherwise it will display the content of the `description` field (actual behavior).
This field supports HTML format.
Current display (nginx template, no `note` field):
Note display (new template with a specific `note` field):
Close #804

feat(templates): add support for the note field

---

app/components/services/servicesController.js

Fixes #803 
Can be tested by running a service with 1 replica of nginx image
Then scale up to 10, and refresh services view quickly
You can see X/10 grow from 1 to 10 when services are up
Before the change, portainer display immediately 10/10

#803 fix(services) Replicas count misunderstanding

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html

Added two new fields to the container creation page for statically setting the IPv4 and IPv6 addresses a container will be assigned.

feat(container-creation): add support for ip assignments (#473)

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/createService/includes/placement.html
app/components/service/serviceController.js
app/helpers/serviceHelper.js

This PR adds the ability to define placement constraints in the service creation view.
The implementation for it is copied from the service update controller, with the view slightly adjusted to match the service creation (it's the same as the labels).
I've put the placement constraints in it's own tab with the intention to at a later stage add the placement preferences.
Updates #121.

#121 feat(create-service): add placement constraints on service creation

---

app/helpers/templateHelper.js
app/models/template.js
app/services/templateService.js

Add support to templates for an optional 'interactive: true' field that starts the container using -i -t.
Closes #819

feat(templates): Support interactive templates (#819)

---

app/models/service.js

The only missing field is the `Arguments` field. This PR fixes this issue.
Fix #854

fix(service-details): add missing Arguments field

---

app/components/service/includes/constraints.html
app/components/service/includes/containerlabels.html
app/components/service/includes/environmentvariables.html
app/components/service/includes/mounts.html
app/components/service/includes/networks.html
app/components/service/includes/resources.html
app/components/service/includes/restart.html
app/components/service/includes/secrets.html
app/components/service/includes/servicelabels.html
app/components/service/includes/tasks.html
app/components/service/includes/updateconfig.html
app/components/service/service.html
app/components/service/serviceController.js

Signed-off-by: Eli Atzaba <eliat123@gmail.com>
Fix #833

#833 feat(service-details): add quick navigation menu anchors

---

app/components/containers/containers.html
app/components/containers/containersController.js

This PR applies next changes to the button disable conditions besides container selection:
- Start button requires selected stopped container
- Stop button requires selected running container
- Pause button requires selected running container
- Resume button requires selected paused container
Fixes #978

feat(containers): add buttons disabling based on cluster selection

---

api/http/proxy/response.go
api/http/proxy/transport.go

See: #990
This PR adds admin protection to the swarm api endpoint. This won't affect any of the existing features from Portainer from what I could tell. 
It also contains a fix for an issue I encountered when testing this:
> When accessing the swarm api without admin permissions, you receive an empty response because the header key-value map is `nil`. This change will ensure that there is always a map.

feat(swarm-api): make swarm api endpoint admin user protected

---

app/components/volumes/volumes.html
app/components/volumes/volumesController.js
app/services/docker/volumeService.js

This PR introduces additional volume filtering in listing view, user is able to view attached and dangling 
volumes separately as well as all volumes together.
Fixes #231

feat(volumes): view dangling volumes

---

app/components/createNetwork/createNetworkController.js
app/components/createNetwork/createnetwork.html
app/components/createSecret/createSecretController.js
app/components/createSecret/createsecret.html
app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/createService/includes/placement.html
app/components/service/includes/placementPreferences.html
app/components/service/service.html
app/components/service/serviceController.js
app/helpers/serviceHelper.js
app/models/docker/service.js

Closes #1002 
- Adds support for placement preferences.
- Includes some minor refactoring to clean up some duplicate code related to labels. This could also be done in a seperate PR if desired.
- Moves some environment variable logic to the service helper, cleans up the service controller a bit.
- Expands the `ServiceViewModel` with some other missing elements. Those would still need to be supported in the service view, but can be done later.
At the moment, placement preferences only support the strategy `spread`. As such, I've added this as the default value. I have left the option to edit the strategy, so it will also work if a new strategy is introduced. In that case, a future enhancement could be to introduce a typeahead or something like it.

feat(services): add support for placement preferences

---

build.sh
build/build_cross-platform.sh
build/build_in_container.sh
gruntfile.js
package.json

`build*Binary` tasks are all equal, except `BUILD_GOOS`, `BUILD_GOARCH` and the executable name. I moved the instructions to a separate bash file (`build/build_cross-platform.sh`) which takes two args. Then, I replaced all the tasks with a single function-based one: https://stackoverflow.com/questions/20799069/grunt-grunt-shell-and-command-argument
Furthermore, the existence of `dist/portainer(.exe)` can be checked with `grunt.file.isFile`: https://nodejs.org/docs/latest/api/fs.html#fs_class_fs_stats . As a result, the dependency on `grunt-if`` can be dropped:
``` javascript
buildBinary: { command: function (p, a) {
var file = 'dist/portainer'; 
if ( p === "windows" ) { file = 'dist/portainer.exe'; }   
if (grunt.file.isFile(file)) { return 'echo \'BinaryExists\'';
} else { …
```

#40 refactor(build-system): reduce gruntfile verbosity, drop grunt-if, allow custom build

---

app/components/images/images.html
app/components/networks/networks.html
app/components/service/includes/tasks.html
app/components/volumes/volumes.html
app/filters/filters.js
app/models/docker/image.js
app/rest/docker/system.js
app/services/docker/imageService.js
app/services/docker/systemService.js
assets/css/app.css

This PR adds `Containers` property to the `ImageViewModel` and new "Unused" tag support.
Let me know your opinion on name and color(here is a list of [available variants](http://getbootstrap.com/components/#available-variations))
Fixes #357

feat(357): unused images tags

---

gruntfile.js
package.json
vendor.yml

Coming from #939.
The following enhancements are proposed in this PR:
- Verbosity is reduced when loading NpmTasks, by using an array.
- Verbosity is reduced by using the `<dest>:<src>` format instead of `dest:<dest>, src:<src>` (only in the plugins that support it: copy, concat and uglify).
- Move declaration of vendor dependencies to a separate file (named `vendor.yml`). A task is added, which parses this file and constructs the content corresponding to `src.jsVendor` and `src.cssVendor` in `grunt.config`.
- Angular dependencies are declared in a similar way and added to `src.angularVendor`, instead of declaring them in `concat.angular.src`.
- This task accepts an argument named `min` which can be either `.min` or empty. If `min==='.min'`, minified versions of the files are used (when …

feat(build-system): dynamic vendoring

---

app/components/containers/containersController.js
app/components/createVolume/createVolumeController.js
app/components/images/images.html
app/components/images/imagesController.js
app/models/docker/image.js
app/services/docker/imageService.js

This PR fixes an issue where it would be impossible to display containers in the containers view.
Fix #977 
It also fixes an issue introduced with #1009 as the system usage endpoint is not compliant with the Swarm API. Therefore, displaying unused/used images is disabled when using Swarm.
It fixes as well another issue with the volume-creation view, the Swarm API do not expose the required information to retrieve available plugins. Therefore, the dropdown is replaced by a simple input when using Swarm.

fix(swarm): fix multiple Swarm related issues 

---

api/http/security/authorization.go

fix(UAC): allow a team member to delete a resource control

---

app/components/volumes/volumes.html

This PR introduces a label in front of the volume name if the volume is considered 'dangling'.
Close #1011

feat(volumes): add a label in front of dangling volumes

---

build/linux/Dockerfile
gruntfile.js

This PR replace the `centurylink/ca-cert` image with `portainer/base`.
Close #832

feat(Dockerfile): use portainer/base image

---

api/http/handler/docker.go
api/http/handler/handler.go
app/app.js
app/rest/api/auth.js
app/rest/api/dockerhub.js
app/rest/api/endpoint.js
app/rest/api/registry.js
app/rest/api/resourceControl.js
app/rest/api/settings.js
app/rest/api/status.js
app/rest/api/team.js
app/rest/api/teamMembership.js
app/rest/api/template.js
app/rest/api/user.js
app/rest/docker/container.js
app/rest/docker/containerCommit.js
app/rest/docker/containerLogs.js
app/rest/docker/containerTop.js
app/rest/docker/exec.js
app/rest/docker/image.js
app/rest/docker/network.js
app/rest/docker/node.js
app/rest/docker/secret.js
app/rest/docker/service.js
app/rest/docker/serviceLogs.js
app/rest/docker/swarm.js
app/rest/docker/system.js
app/rest/docker/task.js
app/rest/docker/volume.js

This PR introduces breaking changes for the HTTP API.
The `api/docker/:endpointId` API endpoint is now relocated under `/endpoints/:endpointId/docker` to make the HTTP API more coherent.

refactor(api): relocate /docker API endpoint under /endpoints

---

app/components/containers/containersController.js

Now for created container available buttons are the same as for stopped.
Fixes #1063

fix(containers): available buttons for created container

---

app/services/templateService.js

Initially just use the Container name as hostname. Later we could additionally offer an Input field to override the hostname
Close #1087

feat(templates): Add hostname to templates

---

app/app.js
app/components/swarm/swarm.html
app/components/swarmVisualizer/swarmVisualizer.html
app/components/swarmVisualizer/swarmVisualizerController.js
app/filters/filters.js
app/services/docker/nodeService.js
app/services/docker/serviceService.js
app/services/docker/taskService.js
assets/css/app.css

This PR brings a new view available when managing a Docker Swarm mode enabled cluster.
The view is available in the Swarm section by clicking on *Go to cluster visualizer*.
It displays information about the number of nodes, services and tasks in the cluster as well as a graphical view similar to docker-swarm-visualizer (https://github.com/dockersamples/docker-swarm-visualizer).
Close #395

feat(swarm-visualizer): add the swarm-visualizer view

---

api/cmd/portainer/main.go

Prevent the creation of multiple admin users Portainer is deployed using the `--admin-password` or `--admin-password-file` flags.
Fix #1249

fix(api): prevent the creation of multiple admin users

---

app/components/service/includes/tasks.html

If I have too many tasks, a filter is helpful when I just need to know the number of running tasks here.
Maybe we can add a checkbox[Show all tasks] later on. (I'am new to angularjs/go, but trying to learn.)
state.filter copied from:
'app/components/containers/containers.html'

chore(tasks): add a filter to show specific tasks in service page.

---

gruntfile.js

`eslint` is task from `gruntify-eslint` package and therefore package
should be loaded as well.
And btw we have around 20 errors 😭

Fix 'gruntify-eslint' usage

---

codefresh.yml

This PR adds a step to ensure the image built via CI on Codefresh (`portainer/portainer:develop`) contains the Docker binary.

chore(codefresh): add a step to download docker binary

---

gruntfile.js

As @1138-4EB [mentioned](https://github.com/portainer/portainer/pull/1276#issuecomment-337538243) there is a more generic way to handle grunt packages which don't fit default pattern instead of loading them individually.
[Default pattern](https://www.npmjs.com/package/load-grunt-tasks#pattern) is `['grunt-*', '@*/grunt-*']` so I've dropped `@*/grunt-*` as it's not being used anyway and added `gruntify-*`.

Replace individual package load with pattern

---

app/components/images/images.html

White spaces inside the `<span>` allows the label to be breaken to multiple lines:
This PR removes those white spaces, so that the label is always shown in a block.

fix(images) prevent unused label breaking to multiple lines

---

app/components/containerInspect/containerInspect.html
app/components/containerInspect/containerInspectController.js
assets/css/app.css
bower.json
vendor.yml

Enhances #1279 providing an interactive tree view of the JSON get from `docker inspect`. [awendland/angular-json-tree](https://github.com/awendland/angular-json-tree) ([demo](https://blog.alexwendland.com/angular-json-tree/)) is used, installed through bower. A button is added to the header of the widget, to allow the user to toggle between tree and text/raw views. Another button is added to download the JSON file.

feat(container-inspect) add angular-json-tree view and download button

---

app/components/swarm/swarm.html

Enable access to node details when authentication is disabled. That is, $scope.isAdmin must be ignored if applicationState.application.authentication is false.

Use isAdmin only if authentication is enabled

---

gruntfile.js

Dynamically evaluating the architecture simplifies natively building portainer on other platforms.
os.arch is used for that. It will return x64 (at least on my x86 system), so in that case is mapped to the expected value of amd64. On other platforms, the value is not modified, and that works at least on my s390x system.

check for actual arch instead of hard-coding amd64

---

api/cli/cli.go
api/cli/defaults.go
api/cli/defaults_windows.go
api/http/handler/file.go
api/http/server.go
gruntfile.js

Fixes #1286.
`defaultAssetsDirectory` is made relative to the location of portainer executable. After the flags are parsed, if `*flags.Assets` is not absolute the location of the portainer executable is prepended. This allows portainer to be called from anywhere in the system, not necessarily from the root of the extracted tarball.
Note that this does not allow to provide the location of assets as a path relative to where portainer is called from. I am not sure about it, but I think that this behaviour may be different for `DataDirectory`, `SSLCertPath`, etc. which would be relative to `os.Args[0]`. @deviantony, are relative paths supported for any of those?

fix(deployment) make assets default relative

---

api/exec/stack_manager.go
api/http/handler/stack.go
api/http/security/filter.go
api/http/server.go
api/portainer.go

This PR brings support for private registries when deploying stacks.
**NOTE**: the user deploying the stack must have access to the registry/registries for authentication to work (see Portainer settings > Registries > Manage accesses).
Closes #1313

feat(stacks): allow to use images from private registries in stacks

---

app/components/sidebar/sidebar.html
assets/css/app.css

As shown in the image in #1314, at now the header of the sidebar is included in the scrollable area, and the footer is not. This PR makes the following changes:
- The header is moved out of the scrollable area, thus made fixed on top.
- The footer is moved into the scrollable area.
Removed:
> As a result, the usable space for the menu is shrunk by the footer. Furthermore, when no custom logo is used the header and the footer are mostly the same.
>
>- The version number is added to the header.
>- The footer is shown only if a custom logo is used in the header.

Move sidebar header out of scrollable area, move footer in

---

assets/css/app.css

- Automatically adjusts sidebar title form-control elements (endpoint dropdown) font-size based on height. Following the same approach as in #1336.
- Sets the same colors used in other elements of the sidebar (background and font) to title form-control elements in the sidebar.
Enhances #1336

style(sidebar) Adjust title form-control

---

gruntfile.js
vendor.yml

At now the build system does not check whether vendor files listed in `vendor.yml` actually exist. This PR adds a check before populating `src.jsVendor`, `src.cssVendor` or `src.angularVendor`. If any of the dependencies is missing, the build fails.
Note that the `vendor` task is moved from the bottom of the gruntfile and placed before the project configuration. The real modification is that [lines 64-68](https://github.com/1138-4EB/portainer/blob/83060326d0527a1a5f22d4150955d703742527e2/gruntfile.js#L64-L68) are added.
This log shows the (errored) output when adding the check (first commit): https://travis-ci.org/1138-4EB/portainer/builds/303310565 (line 4887)
The second commit removes a duplicated incorrect location for `Chart.min.js`. See …

Add check for files listed in vendor.yml, fix location of Chart.min.js

---

app/components/container/container.html
app/components/containers/containers.html

The first commit adds `btn-responsive` class to button "Add container" in the containers view, which is the only button lacking it.
The second commit adds the class to all the action buttons in the container details view.
On top of that, it is a little weird that the containers view shows 7+1 buttons, and the container view shows 9. I split the latter to 7+2. Now, when the user changes from one view to the other it is easier to tell which are common and which specific to the view.

Fix containers btn-responsive

---

app/components/node/node.html
app/models/docker/node.js

A new section is added showing the node's engine labels. These labels cannot be modified as they are added to dockerd when it is started so they are shown as cells in a table.
Close #1374

feat(nodes): add engine labels info in the swarm nodes view

---

app/filters/filters.js

As discussed in https://github.com/portainer/portainer/issues/766, this code adds missing task states. I've reviewed the tasks listed [here](https://github.com/docker/swarmkit/blob/master/api/types.proto) and explained in the [official docs](https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/).
The following task states have been added and assigned to a css style:
- preparing (info)
- ready (info)
- starting (info)
- remove (info)
- running (success)
- orphaned (danger)
Also, as suggested in the discussion, new states can be added in the future so I've changed the default label from success to the existing default label style (background-color: `#777`) which has a grey color, so users won't assume that a new missing state is ok/green.
Close #766

feat(node): add missing task states, set new default state color

---

app/components/swarmVisualizer/swarmVisualizer.html
app/filters/filters.js

Close https://github.com/portainer/portainer/issues/1384 
We add CPU and RAM details to Swarm nodes under the role name.
If we add a memory limit to a service (e.g --limit-memory 128M) that info will be shown for each task below the Update time. Note that 128M in Docker means 128MiB which is the equivalent to 134.22 MB.
If we also add a CPU limit (e.g --limit-cpu 0.25) that info will be shown for each task below the memory limit or the update time.

feat(swarm-visualizer): add ram and cpu info to nodes & limits to tasks

---

api/ldap/ldap.go
app/components/settingsAuthentication/settingsAuthenticationController.js

As discussed in https://github.com/portainer/portainer/issues/1116 Portainer expect that a port is included in the ldap url to be used for authentication purposes.
If no port is added, an error will warn us about this issue:
Code in this commit adds a default port to the url if the user forgets to include a port in the LDAP url (hostname or IP address) after a colon. If plain LDAP or StartTLS is used, 389 will be the default port. If TLS is used, 636 port will be the default port.
First test. Adding LDAP url without port, 389 port will be added in the backend. Works fine.
Second test. Adding LDAP url. Url includes the port (the previous behaviour). Works fine.
Third test. Adding url for TLS without port. 636 port will be added in the backend. Works fine.
Fourth test. Adding url for TLS. …

feat(ldap): add default port when not set in url

---

build/build_in_container.sh
gruntfile.js

This PR just reduces the cognitive complexity of `gruntfile.js`, moving the definition of configuration objects for each of the tasks to the field of a new object named `gruntfile_cfg`.

chore(build-system) split gruntfile to gruntfile_cfg

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/service/includes/hosts.html
app/components/service/service.html
app/components/service/serviceController.js
app/helpers/serviceHelper.js

Close #924
This code allows us to add entries to the hosts file in a container when a service is created. An entry with the form hostname:ip is required.
The hosts entries are added to the Hosts inside the container spec in an array of ip and hostname separated by a space:
We can check that the hosts file contains the new entries:
Also when a service is edited, we now can find a section for Hosts file entries under Network & Published ports :
New entries can be added or removed when a service is edited:
The configuration is updated accordingly:

feat(service): add hosts file entries in service create/update

---

app/constants.js
app/services/stateManager.js

This PR introduces a cache validity check for the application state. Application state will now be cached for one hour max before being reloaded.
Fix #1258

fix(cache): add a cache validity mechanism

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/service/includes/logging.html
app/components/service/service.html
app/components/service/serviceController.js
app/helpers/serviceHelper.js
app/models/docker/service.js
app/services/docker/pluginService.js

Close #1131
The Command tab is renamed Command & Logging. A new section called Logging is added where the user can select a logging driver from a dropdown menu. The dropdown menu is populated with the logging plugins retrieved from Docker and two more values are added: none and Default logging driver. 
Default logging driver is the default value which will be ignored if selected as it means that the default docker daemon logging options are used. 
The add logging driver button will not work unless a driver other than none or the default driver is selected.
If a driver is selected, we can add options to the logging driver. Options will be ignored if none is the selected driver. For example with json-file we can add the max-file and max-size options.
Once we create the service we can …

feat(service): add logging driver config in service create/update

---

app/directives/ui/datatables/containers-datatable/containersDatatableController.js

Fix #1548 
This PR introduces a check of the persisted filters when reloading the containers datatable. Every filter that is not available in the dataset will be removed, new filter entries will be added.

fix(containers): update the persisted filters after refresh

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html

Added in a field to the networks area on the container creation page to allow for assigning a custom mac address to a container.
Also populates the mac address field with the currently assigned address when using the recreate function.
Related to feature request: (#1524)

feat(container-creation): add support for mac assignments (#1524)

---

app/components/service/service.html
app/components/service/serviceController.js
app/components/services/services.html
app/components/services/servicesController.js
app/directives/ui/datatables/services-datatable/servicesDatatable.html
app/directives/ui/datatables/services-datatable/servicesDatatable.js
app/services/modalService.js

Close #859 
A new button called Force update has been added next to the Remove button in the Services list view. That button will cause the tasks to be recreated anyway in the same way as if we use the --force option with the docker service update command. The button will be disabled until we select one or more services.
A dialog will show once we click the Force update button so we are informed about what is going to happen.
Now, the service will be updated using the ForceUpdate member of the TaskTemplate config option. The ForceUpdate value is a counter that we increment to tell Docker that the tasks must be recreated as suggested [here](https://github.com/docker/swarmkit/issues/2364).
If the service is updated successfully we will see a message.
Also we can check that the global or …

feat(service): add force update in service list/detail

---

app/components/swarmVisualizer/swarmVisualizer.html
app/components/swarmVisualizer/swarmVisualizerController.js

Close #1337 
A new drop-down menu is added above the filter section inside the Cluster Information panel, so we can choose the refresh rate (5, 10, 30, 60 seconds) for the view in the same way as the container statistics view works. 
A badge showing the node status has been added in the box which represents each node, so we can track the status of the node.
I try to shutdown one of the nodes in the swarm (portainer-node2) and wait for the view to be refreshed.
Then I launch a service from a different tab in my browser.
Thanks to the auto-refresh, I can see the service in starting state...
And then in the running state...
I change the refresh update time to 30 seconds and I start the powered off node again. 50 seconds later the node has been refreshed. 
The view has now a similar behavior …

feat(swarm-visualizer): add auto-refresh to the cluster visualizer

---

api/cli/cli.go
api/cli/defaults.go
api/cli/defaults_windows.go

Hi !
Fixed a typo in new check health cli flag default value: `defaultCheckHeath`. It should be `defaultCheckHealth`.

Fixed typo in new check health cli flag

---

app/directives/ui/datatables/networks-datatable/networksDatatable.html

If the network name was truncated (at 40 characters) we cannot see the whole network name inside the networks-table. This pull request shows tje untruncated network name as title on the link.

style(network-datatable): Show untruncated network name as link title

---

api/exec/stack_manager.go
api/http/handler/stack.go
api/portainer.go
api/swagger.yaml
app/components/stack/stack.html
app/components/stack/stackController.js
app/services/api/stackService.js

Close #1358 
I start with a docker stack that contains two service.
A new Options section is added to the Docker stack detail view. In this section a new switch named Prune services will be displayed if the API version is >= 1.27. 
If the Prune services option is set, it will force [the --prune option ](https://docs.docker.com/engine/reference/commandline/stack_deploy/#options)to be added to the docker stack deploy command which updates a stack from a Docker Compose file removing services that are no longer needed. The prune option is not used by the default value, it has to be explicitely enabled/added when the stack is updated.
I remove the db service from the docker compose file. If I try to update the stack without pruning the services, we'll still have the two services that were …

feat(stack-details): add stack deploy prune option

---

app/components/volumes/volumesController.js
app/helpers/volumeHelper.js

This PR upgrades the current mechanism to check if volumes are in use.
When connected to a Swarm cluster, the list of services is now retrieved, then we check that each volume declared as dangling is not actually used by any service. If the volume is used by a service, the dangling tag is removed.
Close #1599

feat(volumes): check if volumes are used in service definitions

---

app/docker/models/stackTemplate.js
app/docker/models/template.js
app/docker/views/templates/templatesController.js

This PR introduces support for the `name` property in a template definition. Container/stack name input value will automatically default to that property value when specified.

feat(templates): add support for the name property

---

app/docker/views/swarm/visualizer/swarmVisualizerController.js
app/docker/views/swarm/visualizer/swarmvisualizer.html
assets/css/app.css

This PR aim to solve [issue 1597](https://github.com/portainer/portainer/issues/1597)
The proposed solution is presented in the image below:
The base idea is:
* the tasks status could be checked by background color and  by status label (as it is now)
* the tasks of the same services has the same border color, and the border color is generated from the service id, so it is the same until the service lives
Close #1597

#1597  feat(swarm-visualizer): swarm visualizer color by service

---

api/http/handler/extensions.go
app/docker/views/services/logs/serviceLogsController.js
app/portainer/rest/extension.js
app/portainer/services/api/endpointService.js
app/portainer/services/api/extensionService.js
app/portainer/services/extensionManager.js
app/portainer/views/auth/authController.js
app/portainer/views/endpoints/endpointsController.js
app/portainer/views/sidebar/sidebarController.js

This PR changes the behavior of extension management:
* Upon the init of the endpoint, endpoint extensions are checked
* Upon switching endpoint using the dropdown, endpoint extensions are checked
* After login, endpoint extensions are checked
Also, the endpoint extension check now implies the following:
Check if the extension can be enabled, if yes, register the extension in the endpoint. If no, send a request to remove the extension (will be removed if it exists, otherwise ignored)

feat(storidge): add extension check on endpoint switch

---

api/http/handler/handler.go

fix(api): fix a regression with the HTTP handler

---

api/filesystem/filesystem.go
api/http/handler/stack.go
api/portainer.go

fix(api): use EntryPoint as a reference to overwrite stack Compose file

---

app/docker/models/imageLayer.js
app/docker/services/imageService.js
app/docker/views/images/edit/image.html
app/docker/views/images/edit/imageController.js

This pull request adds new column named "Depth" to the table with image layers and changes default sorting to use that column.
Fixes #1706
Screenshot:

feat(image-details): display image layer depth and sort by it by default (#1706)

---

app/docker/views/services/edit/serviceController.js

The stop-grace-period is now shown in a human-friendly format e.g. 10s, 15m.
To avoid misinterpretations the field is left blank if the value of the attribute is 0, which means it has not been set.
Close #1772

style(services): format stop grace period (fix #1772)

---

assets/css/app.css

This avoids containers name to be displayed on newline if they're longer than expected.
Close #1767

style(dashbard) avoid long container name to display on new line

---

app/docker/views/containers/console/containerconsole.html

Add `/bin/ash` as another dropbox option in addition to `bash and `sh` for shell.
`/bin/ash` is very popular in alpine based docker builds (`redis:alpine` is one good example)

Add support for ash

---

app/docker/views/swarm/visualizer/swarmVisualizerController.js
app/docker/views/swarm/visualizer/swarmvisualizer.html
app/portainer/services/localStorage.js

With this pull request changes to settings on the swarm visualizer view are stored to local storage. 
- Hide / Show Status of Information Panel
- Filter: Only display running tasks
- Refresh rate

feat(swarm-visualizer): save settings to local storage

---

api/http/proxy/transport.go

This PR removes any version path prefix that might be present when using the Docker CLI (`/v1.37/containers/json` -> `/containers/json` for example).

feat(api): remove any version api before proxying request

---

api/http/error/error.go
api/http/handler/handler.go

This PR fixes #1808 and adds "Content-Type: application/json" header to all api responses.
@deviantony

#1808 fix(api): add json content-type to all json API responses

---

app/docker/helpers/logHelper.js
app/docker/rest/container.js
app/docker/rest/response/handlers.js
app/docker/rest/service.js
app/docker/rest/task.js
app/docker/services/containerService.js
app/docker/services/serviceService.js
app/docker/services/taskService.js
app/docker/views/containers/logs/containerLogsController.js

Fix #1700
Based on the analysis in #1700, when `tty` is disabled for a container, extra headers are added to the log stream.
See the following issues for reference:
* https://github.com/moby/moby/issues/7375 
* https://github.com/moby/moby/issues/14201
This PR works-around this by removing the headers only when the container `tty = false`.

fix(log-viewer): strip headers in container logs when TTY is disabled

---

api/http/handler/auth.go
api/http/security/rate_limiter.go
api/http/security/rate_limiter_test.go
api/http/server.go

This PR adds new security entity, `RateLimiter` build on top of [the fork](https://github.com/G07cha/defender) of `defender`.
It's being used in `PostAuth` calls with limitation up to 10 requests per second and ban for an hour if amount goes above it.
Fix #1256

feat(brutforce-protection): add rate limiter

---

app/docker/views/services/edit/serviceController.js

Fix #1569
We add two simple checks that avoid sending unmodified or "default" values to the API when updating the service. The default resource limits and reservation may force tasks to be updated.

fix(service-details) avoid sending unmodified values in service update

---

LICENSE
README.md

Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in
https://landscape.cncf.io/selected=portainer)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit modifies a few of Portainer's docs so that Licensee is able
to recognize the repository's license type. It updates LICENSE so that
it contains only the text of the zlib license. It also moves the info
concerning 3rd-party software to a new "Licensing" section in the
README.
Collectively, these changes allow Licensee to successfully identify the
license type of Portainer as zlib.
For comparison purposes, here is the output that I get when I run Licensee …

edit Portainer license info so that GitHub recognizes it

---

README.md

README updated to document dropped support for standalone Docker Swarm.

Dropped support for standalone Docker Swarm documented

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

Now Portainer will create a container with the first network from the list(if there is any) and then add other networks after a container creation. I was thinking to add this step before container started inside of `containerService` but I didn't want to mix services together. 
Please let me know what do you think!
Fixes #1849

fix(container): recreate container with multiple networks

---

app/docker/rest/container.js

REST call to stop/restart a container overrides the default stop timeout (before kill) with hardcoded 5 seconds.
Containers already have a default stop timeout handled by the engine API (https://github.com/moby/moby/blob/master/client/container_stop.go).
With this hardcoded 5 seconds, the containers get killed after 5 seconds even if they define a custom greater stop timeout.
Another solution would be to not hardcode the 5 seconds but rather use a global editable setting.

fix(containers): remove container stop/restart timeout overload

---

api/http/handler/endpointproxy/handler.go
api/http/handler/endpointproxy/proxy_azure.go
api/http/handler/endpointproxy/proxy_docker.go
api/http/handler/endpointproxy/proxy_storidge.go
api/http/handler/stacks/handler.go
api/http/handler/stacks/stack_create.go
api/http/handler/stacks/stack_delete.go
api/http/handler/websocket/handler.go
api/http/handler/websocket/websocket_exec.go
api/http/security/authorization.go
api/http/security/bouncer.go
api/http/security/filter.go
api/http/server.go
app/docker/views/containers/console/containerConsoleController.js

This PR fixes a vulnerability with the `/api/websocket` endpoint where any unauthorized user could execute a request.
Also fixes a potential SSRF vulnerability allowing unauthorized access to the Docker API.

fix(api): add an authenticated access policy to the websocket endpoint

---

api/bolt/datastore.go
api/bolt/migrate_dbversion11.go
api/bolt/migrator.go
api/bolt/stack_service.go
api/cmd/portainer/main.go
api/filesystem/filesystem.go
api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/create_swarm_stack.go
api/http/handler/stacks/stack_create.go
api/http/handler/stacks/stack_delete.go
api/http/handler/stacks/stack_file.go
api/http/handler/stacks/stack_inspect.go
api/http/handler/stacks/stack_update.go
api/portainer.go

This PR introduces some refactoring regarding the type of a stack identifier. It was previously using a string (a concatenation of stack name + endpoint id) and it's now using an integer.

refactor(api): use a standard stack identifier

---

api/cli/defaults_windows.go

Fix an issue that was spotted in https://github.com/portainer/portainer/pull/2018#issuecomment-402562113

fix(cli): fix default template file path on Windows

---

app/docker/components/log-viewer/logViewer.html
app/docker/components/log-viewer/logViewerController.js
assets/css/app.css

Split auto scrolling & log refresh checkboxes + adds wrap settings for lines in log

feat(log-viewer): Split auto scrolling & log refresh + wrap lines checkbox

---

app/docker/components/datatables/images-datatable/imagesDatatable.html
app/docker/components/datatables/volumes-datatable/volumesDatatable.html

Raise cutoff level and provide tooltips for links in images and volumes datatables to avoid having to open the detail view to see the full name.

Make Images and Volumes datatable more readable

---

api/cli/cli.go
api/docker/client.go
api/http/handler/endpoints/endpoint_create.go
api/http/handler/websocket/websocket_exec.go
api/http/handler/websocket/websocket_exec_linux.go
api/http/handler/websocket/websocket_exec_windows.go
api/http/proxy/factory.go
api/http/proxy/local.go
api/http/proxy/local_linux.go
api/http/proxy/local_windows.go
api/http/proxy/manager.go
api/swagger.yaml
app/portainer/services/api/endpointService.js
app/portainer/views/endpoints/edit/endpointController.js
app/portainer/views/init/endpoint/initEndpoint.html
app/portainer/views/init/endpoint/initEndpointController.js
build/windows/nanoserver/Dockerfile

Updated PR for which replaces #1186 and solves merge issues on it.
Waiting for Microsoft/go-winio#80 to be merged.
Closes #1179 
Closes #1728

feat(api): Add npipe support

---

app/__module.js
app/agent/components/volume-browser/volume-browser-datatable/volume-browser-datatable.js
app/agent/components/volume-browser/volume-browser-datatable/volumeBrowserDatatable.html
app/agent/components/volume-browser/volume-browser.js
app/agent/components/volume-browser/volumeBrowser.html
app/agent/components/volume-browser/volumeBrowserController.js
app/agent/rest/agent.js
app/agent/rest/browse.js
app/agent/rest/response/browse.js
app/agent/services/volumeBrowserService.js
app/docker/__module.js
app/docker/components/datatables/volumes-datatable/volumesDatatable.html
app/docker/components/datatables/volumes-datatable/volumesDatatable.js
app/docker/services/containerService.js
app/docker/views/volumes/browse/browseVolumeController.js
app/docker/views/volumes/browse/browsevolume.html
app/docker/views/volumes/volumes.html
app/portainer/components/datatables/endpoints-snapshot-datatable/endpointsSnapshotDatatable.html
app/portainer/views/stacks/edit/stack.html
package.json
vendor.yml
yarn.lock

This PR introduces introduce a new feature allowing the user to explore the content of a volume directly from Portainer UI.
It is only available for endpoints using the Portainer agent (requires the latest version of the agent to work).
A new browse action is available in the volumes datatable:
Giving you access to the content of the volume, allowing you to download files, delete files/folders, rename files/folders.
Closes #1380

feat(volume-browser): add the ability to browse volume content

---

api/http/proxy/docker_transport.go
api/http/proxy/swarm.go

Close #2053 
Removes the `JoinTokens` and `TLSInfo` fields from the `SwarmInspect` operation for non-administrator users.

feat(api): rewrite SwarmInspect operation

---

app/docker/filters/filters.js
app/docker/views/dashboard/dashboard.html

I replaced the new `containerswithstatus` filter with two new filters `runningcontainers` and `stoppedcontainers` that count the number of running/stopped containers.
They do this by checking `State` property on each container if it's `running` or not.
I'm just worried that there are types of State that are considered running.
Fix #2106

Replace filter for counting running and stopped containers

---

templates.json

hacdias/filemanager has been moved to filebrowser/filebrowser
See: https://filebrowser.github.io/installation/

point filebrowser template to correct image

---

app/docker/components/datatables/services-datatable/servicesDatatable.html
app/docker/filters/filters.js
app/docker/helpers/constraintsHelper.js
app/docker/models/task.js

Fix a bug on replicas number display for services in `global` mode with constraints or `replicated` mode with tasks in unknown state (e.g. Desired State != Current State)
Missing `nodes.labels` and `engine.labels` constraints evaluation.
Closes #1990 .

fix(services): replicas numbers display (#1990)

---

app/portainer/views/stacks/edit/stackController.js

Fix #2123 
For some reason `agentProxy` was not passed to relevant functions, after fixing that the reproduced bug was fixed.

Fix action buttons in stacks view

---

app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/models/network.js
app/docker/views/networks/edit/network.html

Implements feature requested in #1717:
1. visibility of "--internal" and "--attachable" network options in the network list view
2. visibility of "--internal" and "--attachable" network options in the network details view
Closes #1717

feat(networks): Add network details (#1717)

---

app/docker/views/images/import/importimage.html

This is a PR to fix #2174 
Current Behaviour in master - Allows only .tar files 
Expected Behaviour after merge - Allows both .tar and .tar.gz files

#2174 fix(images): Fix to allow both tar and gzip images

---

api/ldap/ldap.go

Hi guys,
LDAP filters need to be escaped when run against an AD backend.
This PR does simple string replace of a few possible characters, in order to allow those in the user CN.
**NB:** I'm fairly new to the various Go tools, and I couldn't make GoLand understand the .godir file, so I haven't been able to actually compile this code. You should probably be very skeptic of this code.
Unfortunately, I'm short on time due to work and I really want to use Portainer at my work, so I wanted to do my best to fix this issue.
If nothing else it might serve as a base for someone else to pick this up.
_Thanks for an awesome project!_
Close #2177

fix(authentication): escape LDAP filters

---

app/docker/components/datatables/nodes-datatable/nodesDatatable.html
app/docker/views/swarm/visualizer/swarmvisualizer.html

- checks if the name of a node is available, otherwise it defaults to the Hostname
- closes #2213

Display node name instead of hostname when applicable

---

api/swagger.yaml
api/swagger_config.json

* Fix yamllint errors that were interfering with `swagger-codegen-cli -l swagger`
* Add `security: [jwt: []]` to non-public endpoints
* Allows use of `ApiClient.configuration.api_key['Authorization']` in generated clients
* Added `api/swagger_config.json` for use with `swagger-codegen`
* Avoids `swagger_client` library name

Updates for swagger-codegen

---

api/http/handler/motd/motd.go
api/portainer.go
app/portainer/views/home/home.html

Returns an empty message instead of 500 when no motd available.
Also upload the URL for the MOTD file location.

feat(motd): relocate motd file URL and always return 200

---

api/cmd/portainer/main.go
api/crypto/ecdsa.go
api/docker/client.go
api/exec/swarm_stack.go
api/http/handler/websocket/websocket_exec.go
api/http/proxy/docker_transport.go
api/portainer.go

This PR introduces support for the `AGENT_SECRET` environment variable that can be used to setup a shared secret between an agent and multiple Portainer instances.

feat(api): support AGENT_SECRET environment variable

---

package.json
yarn.lock

I noticed that newer version of Xterm.js contains lot of bug fixes.
Here is simple example by copy pasting Portainer deployment command
```
docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
```
to console.
**Xterm.js 3.1.0**
**Xterm.js 3.8.0**
Probably can close #2348

chore(terminal): updated xterm to 3.8.0 version

---

api/http/handler/settings/handler.go
api/http/handler/settings/settings_inspect.go
api/portainer.go

Fixes a potential LDAP credential leak by removing the password from the `/api/settings` response.

feat(api): filter LDAP password from settings response

---

app/docker/views/containers/edit/containerController.js

Closes #2442 .
Note: no real visual feedback added, as Notification is already present.
Simply purging the entered image name on creation success disables the button and prevents a user to create many images.

 feat2442: container image create visual feedback

---

package.json

added the following scripts:
- `yarn start` - will start a dev environment - build the server and client and watch for changed client files (basically an alias for `grunt run-dev`
- `yarn start:server` - will build the server (using offline deps) and run the server

add start and start:server scripts

---

app/docker/views/containers/console/containerConsoleController.js

Close the console when selected shell does not exist inside the container.

fix(containers-console): strange console behaviour on error at start

---

app/docker/views/containers/stats/containerstats.html

Sometimes user wants to monitor process and CPU usage even more frequently, such as 1s or 3s.

feat(containers-stats): add refresh rate of 1 and 3 seconds

---

app/docker/views/containers/create/createContainerController.js

fix #2379
I made a mistake in a fix I did a few weeks back, where I was calling the stopContainer function in the promise chain, instead of just passing it. It didn't cause many bugs (except #2379) because it did return a promise, so most times it means just stopping the container before pulling the image.

Stop container only after pull

---

api/swagger.yaml

docs(api): fix invalid example value for AutoCreateUsers property

---

package.json
yarn.lock

Upgrades bootstrap version to 3.4.0 to fix a potential XSS attack.
Related links:
* https://snyk.io/vuln/npm:bootstrap:20160627
* https://github.com/twbs/bootstrap/issues/20184

dep(bootstrap): update bootstrap version to 3.4.0

---

app/docker/__module.js
app/portainer/__module.js
app/portainer/components/datatables/stacks-datatable/stacksDatatable.html

closes #2494 
it adds a resolve to docker states to check if `endpointID` is set, if not, redirects to `portainer.home` with a warning notification.
For some reason the stacks state is in the portainer module instead of docker. I think it should move, but nevertheless I added the same resolve to the stacks state. I did move `portainer.newstack` to `portainer.stacks.newstack`, seems more logical and removes another duplication of the resolve function

Redirect to home if no endpoint is set

---

app/portainer/views/endpoints/create/createEndpointController.js

The directions for installing the agent stack from the endpoints view used an old url. Update to the new url.
Fixes https://github.com/portainer/portainer/issues/2584

2584 fix(endpoints): correct agent stack download url

---

api/cmd/portainer/main.go

Just a trivial speling mistake.

style(main): fix spelling of endointSyncSchedule

---

README.md

The current logo src is 404: https://portainer.io/images/logo_alt.png
The repo already includes the logo: https://github.com/portainer/portainer/blob/develop/assets/images/logo_alt.png?raw=true

docs(README): update logo src

---

app/app.js

fix(auth): Do not double redirect to portainer.auth

---

app/portainer/services/codeMirror.js

fix(codemirror): For YAML, set tab key to insert spaces

---

app/constants.js
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/components/datatables/networks-datatable/networksDatatable.js
app/docker/components/datatables/networks-datatable/networksDatatableController.js
app/docker/views/networks/edit/network.html
app/docker/views/networks/edit/networkController.js

This adds a disabled property based on the name of the network since there is no other way to distinguish between a user-created-network or predefined-network. This fixes #1838.

fix(networks): disable removing predefined networks (#1838)

---

gruntfile.js

Install docker binary when on macOS based system.
fix #2774

fix(build-system): Install docker binary when on macOS

---

build/build_binary_devops.ps1

This is to add a `-Force` switch to override `dist` and `portainer` folders if they exist

Fix Windows CI with Webpack

---

app/docker/components/container-quick-actions/containerQuickActions.html
app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/containers-datatable/containersDatatableController.js
app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatableController.js
app/docker/components/datatables/tasks-datatable/tasksDatatableController.js

As this feature can be confusing for new users (you usually need to start a container in a specific way to use it), it will be hidden by default and can be toggled on via the containers datatable settings for quick actions.
The attach link is still available in the container details view.
Related to #592

feat(containers): hide the attach quick action by default

---

app/portainer/services/api/extensionService.js
app/portainer/views/auth/authController.js
app/portainer/views/extensions/extensionsController.js
app/portainer/views/init/admin/initAdminController.js

Extension status retrieval was cancelled on OAuth login.
It's now fixed.

fix(app): extensions status retrieval

---

package.json
yarn.lock

Closes #2931 
Bump auto-ngtemplate-loader to 2.0.1 to fix windows build.

fix(build): fix windows builds

---

app/agent/components/volume-browser/volumeBrowserController.js
app/agent/rest/browse.js
app/agent/rest/v1/browse.js

This fixes #2661.
FileSaver.js expects the data to be an Blob or ArrayBuffer
https://github.com/eligrey/FileSaver.js/issues/367#issuecomment-360390179
I had to remove the fixed declaration of the type as well (text/plain;charset=utf-8), since it can cause problems while saving files likes tar.gz or mp3.
I have tested it with txt, zip, tar.gz, mp3 and files without extension.

fix(volume-browser): Zip files corrupted when downloaded from a docker volume 

---

app/docker/views/swarm/visualizer/swarmvisualizer.html

Closes https://github.com/portainer/portainer/issues/2862

fix(swarmvisualizer): nodes are now sorted by roles then by hostname

---

app/docker/components/host-view-panels/engine-details-panel/engine-details-panel.html
app/docker/components/host-view-panels/swarm-node-details-panel/swarm-node-details-panel.html
app/docker/views/nodes/node-details/node-details-view-controller.js

Move engine labels from node-details panel to engine-details panel.
Closes #2964 .

feat(node-details): engine labels

---

app/extensions/rbac/directives/disable-authorization.js

Closes #2979 
`disable-authorization` directive was hiding/showing elements instead of disabling them.

fix(app): un-needed checkbox in service details view

---

api/http/handler/endpointproxy/proxy_docker.go
app/portainer/views/home/homeController.js

Closes #3088 
It is worth noting that this PR removes the automatic "Endpoint is down" error response returned by the backend each time a request was sent against an endpoint with a status set to Down.
Instead, we let the request go through the remote API (agent/docker) and returns the response from the remote.

fix(api): remove automatic backend failure for Down endpoints

---

api/http/handler/endpointproxy/proxy_docker.go
app/portainer/views/home/homeController.js

Closes #3083 
Note: This implementation is based on https://github.com/portainer/portainer/pull/3160 and should be tested after this one has been validated.

fix(home): refresh the view on endpoint ping failure

---

gruntfile.js

This PR upgrades the docker version to 19.03.2 to support compose v3.8.
Is there anything that speaks against this?
Closes #3206

update docker binary version to 19.03.2

---

api/authorizations.go
api/bolt/migrator/migrate_dbversion19.go
api/http/handler/endpointgroups/endpointgroup_delete.go
api/http/handler/endpointgroups/endpointgroup_update.go
api/http/handler/endpoints/endpoint_create.go
api/http/handler/endpoints/endpoint_delete.go
api/http/handler/endpoints/endpoint_update.go
api/http/handler/extensions/upgrade.go
api/http/handler/teammemberships/handler.go
api/http/handler/teammemberships/teammembership_create.go
api/http/handler/teammemberships/teammembership_delete.go
api/http/handler/teams/handler.go
api/http/handler/teams/team_delete.go
api/http/handler/users/handler.go
api/http/handler/users/user_delete.go
api/http/server.go

The user authorizations were not correctly updated introducing some issues reported in https://github.com/portainer/portainer/issues/2960#issuecomment-537311641
User authorizations are now updated when:
* An access policy on a group has changed (created, updated, deleted)
* An access policy on an endpoint has changed (created, updated, deleted)
* An endpoint has been created that is part of a group with existing access policies associated
* An endpoint group is removed, reassigning access policies associated to the Unassigned default endpoint group
* A user is added to a team
* A user is removed from a team
A clean-up of access policies is also triggered when:
* A user is removed
* A team is removed
This will remove existing access policies associated to the user/team for …

feat(api): trigger user authorization update when required

---

app/vendors.js
package.json
yarn.lock

Fixes #3130.
Tested visually, icons are still shown.

chore(icons): update fontawesome dependency (#3130)

---

app/docker/helpers/containerHelper.js
app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

I've added support for port ranges when deploying containers.
I also made sure that any port ranges are combined when editing/duplicating containers for a better overview.
Let me know what you think.
This should also close #734
**NOTE:**
I was asked by @itsconquest to reopen a new pull request because of a CI bug. The previous pull request is here: https://github.com/portainer/portainer/pull/2855
I took the liberty of squashing my previous commits as well, which I hope was fine.

feat(containers): added support for port range mappings when deploying containers

---

app/docker/views/containers/create/createContainerController.js

Closes: #2112
Currently we are using RegExp `/\=(.+)/` to catch key-value
of environment variables, which could not match empty-value
environment variables such as `KEY=`.
This commit will change the RegExp to `/\=(.*)/`, which
matches the empty values.

fix(container): Fix bad env in container creation

---

api/exec/extension.go

Closes #3269 
Unfortunately, I did not find a way to bubble up the error happening in the extension to the Portainer UI. 
This implementation will make all the extension logs now available inside the same output as the Portainer logs.

feat(api): bind extensions stdout and stderr to current process

---

app/docker/views/containers/create/createContainerController.js
app/portainer/helpers/templateHelper.js

This small patch will allow empty values to be set on container labels during container creation or during App Template creation.
This addresses #2646
Currently the inspect does not retain empty values when re-creating containers or inspecting containers. Looks like ```api/http/proxy/response.go``` has ```extractJSONField``` and it's somehow eating empty labels. Not sure what to do with this last piece.

Container label value allow null

---

app/docker/views/containers/create/createContainerController.js

patches aliases for case when no network config exists (in new container creation)

fix(container-create): patch aliases

---

api/cmd/portainer/main.go

remove the logging of the hashed password on an 
admin user creation as referenced in issue #2844 .
Closes #2844

#2844 fix(cli): remove the logging of the hashed password of the admin user

---

api/cmd/portainer/main.go
api/ldap/ldap.go
api/portainer.go
api/swagger.yaml

* When enabled, ReaderDN and Password will not be used
* Anonymous mode is set to `true` by default on fresh installations
**Pending:** bolt database migration logic (if any is necessary)
API changes to fix #3443 and to complement #3456

feat(authentication/ldap): implement anonymous mode for LDAP connection

---

api/http/handler/settings/settings_update.go

* Allows to avoid changing any current value when using LDAP Anonymous Mode
Futher API changes to fix #3443 and to complement #3456
See comment: https://github.com/portainer/portainer/pull/3456#issuecomment-577462777

feat(authentication/ldap): preserve ReaderDN in database if empty in settings payload

---

api/docker/snapshot.go
api/portainer.go
app/docker/filters/filters.js
app/docker/views/dashboard/dashboard.html
app/portainer/components/endpoint-list/endpoint-item/endpointItem.html

Closes #3488 
Re-purposes the heartbeat icon to indicate health, instead uses the poweroff icon for running or not.  If the container has no healthcheck, behavior remains the same as before.
**Portainer Homepage view**
**Endpoint Dashboard View**

feat(dashboard): add health status to home page and dashboard

---

app/docker/views/containers/create/createContainerController.js

Patch container duplicate for case when no Dns property exists (e.g. containers deployed via templates)

fix(container-duplicate): patch dns

---

api/ldap/ldap.go

Patch connectivity check to execute an anonymous bind and show error when not allowed

fix(authentication): patch connectivity check

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

Adds an option for the `--init` option on container creation, per this comment: https://github.com/portainer/portainer/issues/2111#issuecomment-427155043
This is my first PR, so I'm sure I've missed out on something somewhere; feel free to nag at me to fix it.
Closes #2111

feat(container-creation): add support for --init (#2111)

---

api/chisel/service.go
api/docker/client.go
api/exec/swarm_stack.go
api/http/handler/websocket/proxy.go
api/http/proxy/factory/docker.go
api/libcompose/compose_stack.go
api/portainer.go

This commit changes all instances of "localhost" in Go code to fix #3144.
Should fully resolve the issue until the IETF localhost draft becomes adopted.

fix #3144: convert localhost to 127.0.0.1

---

app/docker/helpers/containerHelper.js

Close #1261 
I suggest that we just ensure that config.ExposedPorts exists in container's config. It seems that works fine with home-assistant and haproxy now.

fix(container): Cannot set property <port>/tcp of undefined while editing container port mapping

---

docker-compose.pull-dog.yml
pull-dog.json

I sent you an e-mail about this @deviantony, along with a video that demonstrates the whole thing. This pull request assumes you've watched the video first.
**It's important that you install the GitHub app before merging this.** If you don't, Pull Dog will not detect that the repo has been set up.
As per the video (and as you can see in `pull-dog.json`), lazy mode has been enabled, meaning that a POST request from the build server will be needed before Pull Dog starts.
The POST request that has to be made is of the following form:
```
POST https://dogger.io/api/pull-dog/provision
{
"repositoryHandle": "59239347",
"apiKey": "<your API key from the dashboard, as seen in the video>",
"commitReference": "<GIT commit ID>",
"configuration": {
"buildArguments": {
"PORTAINER_TAG": "develop"
}
}
} …
```

Enable Pull Dog for the repository

---

api/http/handler/registries/registry_update.go

fix(registries): check same url for gitlab

---

app/portainer/views/auth/auth.html

Close #3953 .
As a note `auto-focus` directive doesn't work when used inside a `ng-show`'d block. It's only working inside blocks that are always displayed, or `ng-if`'d blocks.

fix(auth): autofocus on login field

---

app/__module.js
app/app.js

this fixes an issue where the @babel/polyfill plugins were loaded after the agent module (loading is alphabetically), because they were in another file other than the entrypoint. babel's best practices suggest putting it in the beginning.

refactor(app): move @babel/polyfill to entry

---

app/docker/components/datatables/images-datatable/imagesDatatable.html
app/docker/components/datatables/volumes-datatable/volumesDatatable.html
app/portainer/components/datatables/genericDatatableController.js
app/portainer/services/authentication.js
app/portainer/services/endpointProvider.js
app/portainer/services/localStorage.js
app/portainer/views/main/mainController.js

fix #4064
tests:
Here's a list of features/areas where we're using cookies that you can use for review:

feat(settings): replace cookies with local storage

---

app/docker/views/containers/create/createContainerController.js

Closes #3635 
Sorts volumes in the container creation view drop-down into alphabetical order as shown in the image below.

#3635 fix(containers) sort volumes in container creation view

---

api/bolt/init.go
api/bolt/migrator/migrate_dbversion23.go
api/http/handler/settings/settings_public.go
api/http/handler/settings/settings_update.go
api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/create_swarm_stack.go
api/http/handler/stacks/stack_create.go
api/http/proxy/factory/docker/containers.go
api/portainer.go
app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html
app/portainer/models/settings.js
app/portainer/services/stateManager.js
app/portainer/views/settings/settings.html
app/portainer/views/settings/settingsController.js

fix #4066
* feat(settings): introduce device mapping service
* feat(containers): hide devices field when setting is on
* feat(containers): prevent passing of devices when not allowed
* feat(stacks): prevent non admin from device mapping
* feat(stacks): disallow swarm stack creation for user
* refactor(settings): replace disableDeviceMapping with allow
* fix(stacks): remove check for disable device mappings from swarm
* feat(settings): rename field to disable
* feat(settings): supply default value for disableDeviceMapping
* feat(container): check for endpoint admin

feat(settings): add setting to disable device mapping for regular users

---

app/docker/views/containers/edit/containerController.js
app/portainer/models/settings.js
app/portainer/services/stateManager.js
app/portainer/views/settings/settings.html
app/portainer/views/settings/settingsController.js

fix #4069 
* feat(settings): add info about container edit disable
* feat(settings): set security settings
* feat(containers): hide recreate button when the setting is enabled
* feat(settings): rephrase security notice
* fix(settings): save allowHostNamespaceForRegularUsers to state

feat(containers): disable edit container on security setting restricting regular users

---

app/portainer/components/forms/registry-form-custom/registry-form-custom.html
app/portainer/models/registry.js
app/portainer/services/api/registryService.js
app/portainer/views/registries/edit/registry.html

Closes #3965 .
Removes trailing slash from registry URLs when:
- Adding a new registry
- Updating an existing registry

Remove trailing slash & protocol in registry URLs

---

app/docker/helpers/containerHelper.js
app/docker/views/containers/edit/containerController.js

closes #3523
WIP, still need to load host ports correctly on duplicate when multiple host `ip:port` entries point to the same container port
_Container was published as:_
_On duplicate it was loaded as:_

fix(containers): handle multiple ips with the same port

---

app/portainer/__module.js
app/portainer/services/authentication.js

reproduce:
1. login
2. run `yarn start:server` or just restart portainer (`docker restart portainer`)
3. refresh the page
before fix:
stuck on logout even if refreshing again
after fix:
redirected to auth page

fix(auth): reject main route if logged out

---

app/portainer/__module.js

fixes an issue when spawning a new environment shows an empty screen. basically it checks that the route is protected before redirecting when the user is not logged in.
tests:
1.1. log in
1.2. restart docker container (`docker restart portainer`)
1.3. user should see login page when refreshing or trying to do something in the app
2.1. create a new environment 
2.2. user should see create admin page

fix(auth): don't redirect if route is unauthenticated

---

app/assets/css/app.css
app/docker/views/containers/edit/container.html

Fixes #2676 
Please see the screenshot

style(containers): fix word-break on container details table

---

.github/stale.yml

Update the closing message from stalebot to ask users to mention a member of our support team and not myself

chore(project): update stalebot message

---

app/kubernetes/views/applications/applicationsController.js

fix(applications/ports-mapping): load balancer link expand only if item length > 1

---

api/http/proxy/factory/docker/transport.go

Fixes #4463 
This was only tested against volumes, we'll need to do more testing against other resources.

fix(docker/resourcecontrol): fix an issue with resource deletion

---

app/portainer/views/stacks/edit/stack.html

This will solve #4470.
Instead of removing the entire editor tab we are now disabling the "Update the Stack" button when the editor content is empty.

#4470 fix(stack): fix a display issue with the stack editor tab.

---

app/kubernetes/services/configMapService.js

Closes https://github.com/portainer/portainer/issues/4629

fix(frontend) unable to retrieve config map error when trying to manage newly created resource pool (ce#180)

---

app/portainer/views/stacks/edit/stack.html

fix(docker/stack-details): do not display editor tab for external stack

---

gruntfile.js

This reverts commit 380f106571330e778e2ef8790cc6f2a617643e97.

Revert "chore(build): bump Kompose version (#4475)" in release

---

CONTRIBUTING.md
README.md

Provide build instructions directly in the `CONTRIBUTING.md` file of the repository and make the link to build documentation stand out more.
Closes #4411 
Closes #3929

#4411 docs: make build steps for local development more easily discoverable

---

api/http/proxy/factory/kubernetes/transport.go
api/http/proxy/manager.go
api/kubernetes/cli/client.go

fix(kubernetes): removes kube client cache when edge proxy is removed (#4487)

---

app/docker/components/datatables/images-datatable/imagesDatatable.html
app/docker/models/image.js
app/docker/models/imageDetails.js
app/docker/views/images/edit/image.html

Closes #3462 
This PR includes changes that displays labels associated with an image in the images datatable.
Sample image: `wurstmeister/kafka:latest`

feat(image-details): Show labels in images datatable

---

api/exec/swarm_stack.go
build/download_docker_binary.ps1
gruntfile.js

Update Docker binary version to 19.03.x for both Linux and Windows which adds support for Docker Stack version 3.8 https://docs.docker.com/compose/compose-file/
Because Docker, Inc does not any more publish Windows binaries separately I change script to use binaries published by Microsoft. Links to those can be found from https://go.microsoft.com/fwlink/?LinkID=825636&clcid=0x409
Closes #3206 #3036

dep(api): update docker binary version to 19.03.12

---

app/kubernetes/views/volumes/edit/volume.html
app/kubernetes/views/volumes/edit/volumeController.js

Updated version of PR #4405 
Closes #4402 
This PR adds the shared access policy entry in the volume details view for Kubernetes.
Any suggestions and advice are welcome!
Thank you!

Show shared access policy in volume details - 2

---

api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/create_swarm_stack.go
api/http/handler/stacks/handler.go
api/http/proxy/factory/docker.go
api/http/proxy/factory/docker/containers.go
api/http/proxy/factory/docker/transport.go
api/http/proxy/factory/docker_unix.go
api/http/proxy/factory/docker_windows.go
api/http/proxy/factory/factory.go
api/http/proxy/manager.go
api/http/server.go
app/docker/views/volumes/volumesController.js

fix #4125
The following are not a problem, because they are hidden behind a check for `tokenData.isAdmin` and this check is true by default, but we might want to add a check for isAuthDisabled so it won't be removed by accident.
```
api/http/proxy/factory/docker/transport.go:
437: 		user, err := transport.userService.User(tokenData.ID)
713: 		user, err := transport.userService.User(operationContext.userID)
api/http/security/bouncer.go:
183: 	user, err := bouncer.userService.User(tokenData.ID)
261: 		user, err := bouncer.userService.User(tokenData.ID)
```
the following should be tested:
- create swarm stack
- create compose stack
- delete/inspect stack
- create container
- browse volumes (on agent)

fix(auth): skip security checks with --no-auth flag 

---

app/kubernetes/helpers/configurationHelper.js

fix(k8s) parse empty configuration as empty string yaml instead of {} (ce#395)

---

app/kubernetes/converters/configMap.js
app/kubernetes/models/config-map/models.js
app/kubernetes/services/configMapService.js
app/kubernetes/views/resource-pools/access/resourcePoolAccessController.js
app/portainer/views/stacks/create/createStackController.js

Close #4808
PR #4691 introduced a change in ConfigMap model that didn't consider access management feature.
I extracted Portainer access management (relying on ConfigMaps) from generic ConfigMap system to prevent similar failures in the future.

fix(k8s/resource-pool): unusable RP access management

---

api/cmd/portainer/main.go
api/exec/compose_wrapper.go
api/exec/compose_wrapper_integration_test.go

closes #4807 
closes #CE-401
Provide `DOCKER_CONFIG` env var to the `docker-compose` executable. Env var points to a directory with the docker's `config.json` file.

fix: docker-compose access to private registries

---

app/agent/components/file-uploader/fileUploader.html
app/docker/views/images/import/importimage.html
app/edge/components/edge-job-form/edgeJobForm.html
app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackView.html
app/portainer/components/endpointSecurity/porEndpointSecurity.html
app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateView.html
app/portainer/views/settings/authentication/settingsAuthentication.html
app/portainer/views/stacks/create/createstack.html

Close #4748 
Fix the bug on :
- Endpoint creation/edition (with select file button)
- Custom template creation
- Edge stack creation/edition
When adding a file selection button in a form, we need to specify the type of the button (`type="button"`) (https://www.w3schools.com/tags/att_button_type.asp)

feat(app): add type=button on every button with ngf-select

---

api/http/handler/endpoints/endpoint_update.go

fix(endpoint): skip tls for kube endpoints

---

app/portainer/views/settings/settings.html

Minor change, under the 'App Templates' section in settings the link to the 'how to use templates' page returns a 404, updated it to point to the same(?) section in newer docs.
Glanced through existing PRs and I don't think this has been done yet.
Closes https://github.com/portainer/portainer/issues/4832

fix(app/settings): update link to template definition docs

---

api/http/handler/customtemplates/customtemplate_list.go
app/portainer/components/forms/stack-from-template-form/stackFromTemplateForm.html
app/portainer/views/custom-templates/custom-templates-view/customTemplatesViewController.js
app/portainer/views/templates/templatesController.js

feat(custom-templates): switching a template to standalone makes it disappear in swarm mode

---

app/docker/components/imageRegistry/porImageRegistry.html
app/docker/filters/filters.js

Add a button next to the image field when creating a new container, which
takes the user to the Docker Hub search page for this image. Version
identifiers are trimmed from the image name to ensure that matching images
will be found.
Closes #4374

#4374 feat(images): Add link to Docker Hub on container creation page

---

api/portainer.go

fix [CE-462]
sends security settings in camelCase (as expected in client) vs PascalCase
[CE-462]: https://portainer.atlassian.net/browse/CE-462

fix(endpoints): show correct values of security settings

---

api/bolt/team/team.go
api/bolt/user/user.go
api/go.mod
api/http/proxy/factory/docker/access_control.go
api/http/proxy/factory/docker/access_control_test.go

closes #3547
closes [CE-51]
Ignore duplicates, whitespaces and casing in Portainer's users and teams labels
[CE-51]: https://portainer.atlassian.net/browse/CE-51

fix(uac): ignore duplicates, spaces and casing in portainer labels

---

app/kubernetes/views/configure/configureController.js
app/portainer/services/endpointProvider.js

Close CE-463
Reference issue: JIRA CE-463
* $stateParams
* $transition$
* $uiRouterGlobals
to retrieve the URL params
* $stateParams: is deprecated and will cause a circular dependency injection error because EndpointProvider is used by EndpointStatusInterceptor which is injected inside $httpProvider
> [$injector:cdep] Circular dependency found: $uiRouter <- $stateParams <- EndpointProvider <- EndpointStatusInterceptor <- $http <- $uiRouter
For more details, see https://stackoverflow.com/questions/20230691/injecting-state-ui-router-into-http-interceptor-causes-circular-dependency#20230786
* $transition$: mentionned as the replacement of $stateParams (https://ui-router.github.io/guide/ng1/migrate-to-1_0#stateparams-deprecation) but is not injectable without tweaks inside a service
* …

fix(app): EndpointProvider fallback on URL EndpointID when no endpoint is selected

---

app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationData.html
app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationDataController.js

fix [CE-469]
- recalculate duplcate keys when they are changed
- show used warning on duplicate keys
[CE-469]: https://portainer.atlassian.net/browse/CE-469

fix(kube/config): show used key warning when needed

---

api/http/proxy/factory/docker/containers.go
api/http/proxy/factory/docker/services.go
api/http/proxy/factory/docker/transport.go
app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html
app/docker/views/services/create/createServiceController.js
app/docker/views/services/create/createservice.html

fix #4106 [CE-28]
* feat(containers): enforce disable bind mounts
* refactor(docker): move check for endpoint admin to a function
* feat(docker): check if service has bind mounts
* feat(services): allow bind mounts for endpoint admin
* feat(container): enable bind mounts for endpoint admin
* fix(services): fix typo
[CE-28]: https://portainer.atlassian.net/browse/CE-28

feat(containers): enforce disable bind mounts (#4110)

---

api/exec/compose_wrapper.go
api/http/handler/stacks/create_compose_stack.go
api/libcompose/compose_stack.go
api/portainer.go

closes #4835
closes [CE-418]
Changes:
- only stacks deployed with libcompose should normalize the stack names

fix: normalize stack name only for libcompose

---

app/portainer/views/endpoints/edit/endpointController.js

Fix #4478
[CE-110]
Note that changing the agent URL and trying to access the endpoint creates the following errors 
```
2020/11/23 16:22:47 server: Reverse tunnelling enabled
2020/11/23 16:22:47 server: Fingerprint 3c:dd:80:47:5a:19:c1:d2:41:81:87:71:c3:15:52:ac
2020/11/23 16:22:47 server: Listening on 0.0.0.0:8000...
2020/11/23 16:22:47 Starting Portainer 2.0.0 on :9000
2020/11/23 16:22:47 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]
2020/11/23 16:23:52 http error: No administrator account found inside the database (err=Object not found inside the database) (code=404)
2020/11/23 16:23:52 http error: No administrator account found inside the database (err=Object not found inside the database) (code=404)
2020/11/23 16:24:24 …
```

fix(k8s/endpoint): update endpoint URL

---

api/http/proxy/factory/docker/configs.go
api/http/proxy/factory/docker/containers.go
api/http/proxy/factory/docker/networks.go
api/http/proxy/factory/docker/secrets.go
api/http/proxy/factory/docker/services.go
api/http/proxy/factory/docker/swarm.go
api/http/proxy/factory/docker/transport.go
api/http/proxy/factory/docker/volumes.go
api/http/proxy/factory/responseutils/response.go

closes [EE-479]
`responseutils.GetResponseAsJSONOBject` should be `responseutils.GetResponseAsJSONObject`
[EE-479]: https://portainer.atlassian.net/browse/EE-479

style(proxy): fix function name

---

app/kubernetes/models/resource-pool/formValues.js
app/kubernetes/models/resource-types/models.js
app/kubernetes/services/applicationService.js
app/kubernetes/views/applications/create/createApplication.html
app/kubernetes/views/configurations/create/createConfiguration.html
app/kubernetes/views/configurations/edit/configuration.html
app/kubernetes/views/resource-pools/create/createResourcePool.html
app/kubernetes/views/resource-pools/edit/resourcePool.html
app/kubernetes/views/summary/resources/applicationResources.js
app/kubernetes/views/summary/resources/configurationResources.js
app/kubernetes/views/summary/resources/helpers.js
app/kubernetes/views/summary/resources/namespaceResources.js
app/kubernetes/views/summary/summary.html
app/kubernetes/views/summary/summary.js
app/kubernetes/views/summary/summaryController.js
app/portainer/services/localStorage.js

Closes [EE-436](https://portainer.atlassian.net/browse/EE-436).
A summary is provided upon creating and updating the following kubernetes resources:
- Configurations
- Namespaces
- Applications

feat(kubernetes/summary): summary of k8s actions upon deploying/updating resources EE-436

---

app/docker/helpers/serviceHelper.js
app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html
app/docker/views/services/create/createServiceController.js
app/docker/views/services/create/createservice.html
app/docker/views/services/edit/includes/environmentvariables.html
app/docker/views/services/edit/serviceController.js
app/portainer/components/environment-variables-panel/environment-variables-panel.controller.js
app/portainer/components/environment-variables-panel/environment-variables-panel.css
app/portainer/components/environment-variables-panel/environment-variables-panel.html
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode-item/environment-variables-simple-mode-item.controller.js
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode-item/environment-variables-simple-mode-item.html
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode-item/index.js
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode.controller.js
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode.css
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode.html
app/portainer/components/environment-variables-panel/environment-variables-simple-mode/index.js
app/portainer/components/environment-variables-panel/index.js
app/portainer/filters/filters.js
app/portainer/helpers/env-vars.js
app/portainer/views/stacks/create/createStackController.js
app/portainer/views/stacks/create/createstack.html
app/portainer/views/stacks/edit/stack.html
app/portainer/views/stacks/edit/stackController.js

Closes #546
Closes https://github.com/portainer/portainer/issues/3558
closes [CE-32]
**TO-DO:**
[CE-32]: https://portainer.atlassian.net/browse/CE-32

feat(UX): introduce new env variables UI

---

api/go.sum
api/http/handler/websocket/handler.go
api/http/handler/websocket/pod.go
api/http/handler/websocket/shell_pod.go
api/kubernetes/cli/client.go
api/kubernetes/cli/naming.go
api/kubernetes/cli/pod.go
api/kubernetes/cli/pod_test.go
api/kubernetes/cli/service_account.go
api/kubernetes/cli/service_account_test.go
api/portainer.go

Closes [EE-849](https://portainer.atlassian.net/browse/EE-849).
This is the backport for the backend kubectl shell functionality from EE.
The overall feature is still WIP.

feat(kubernetes/shell): backport kubectl shell backend functionality EE-849

---

api/http/handler/handler.go
api/http/handler/kubernetes/handler.go
api/http/handler/kubernetes/kubernetes_config.go
api/http/server.go
api/kubernetes/cli/kubeconfig.go
api/kubernetes/cli/kubeconfig_test.go
api/kubernetes/cli/resource.go
api/kubernetes/cli/resource_test.go
api/portainer.go

Closes [EE-1004](https://portainer.atlassian.net/browse/EE-1004).
This is the backport for the backend kubeconfig file generation functionality from EE.
The overall feature is still WIP.

feat(kubernetes/shell): backport kubeconfig generation backend functionality EE-1004

---

api/http/handler/kubernetes/kubernetes_config.go
app/constants.js
app/kubernetes/components/kubectl-shell/kubectlShell.css
app/kubernetes/components/kubectl-shell/kubectlShell.html
app/kubernetes/components/kubectl-shell/kubectlShellController.js
app/kubernetes/rest/kubeconfig.js
app/kubernetes/services/kubeconfigService.js

Closes [EE-926](https://portainer.atlassian.net/browse/EE-926).
The following PR enables one to download `kubeconfig` file as `config.yaml`
Note: A change was made to backend to parse `Accept` header instead of `Content-Type` header as this aligns more closely to what k8s API server requires/does.

feat(kubernetes/shell): backport of kubeconfig export functionality EE-926

---

api/cli/cli.go
api/cmd/portainer/main.go
api/http/handler/backup/backup_test.go
api/http/handler/backup/handler.go
api/http/handler/backup/handler_test.go
api/http/handler/backup/restore_test.go
api/http/server.go
api/portainer.go
app/portainer/rest/backup.js

fix [EE-634]
- introduce a cli flag `--demo`
- when `--demo` is supplied, the backup operations will fail
[EE-634]: https://portainer.atlassian.net/browse/EE-634

feat(backup): disable backup for demo environment

---

app/docker/components/log-viewer/logViewerController.js

fix issue with download logs file showing `[Object object]` after updating log viewer with ascii colors
closes #5241

fix(logs):  Download logs is broken in relase/2.6 EE-1051

---

.vscode.example/settings.json
package.json

[DTD-56]
this PR adds the following:
- yarn scripts:
- `yarn lint:server` - will run go linter
- `yarn lint:client` - will run eslint
- `yarn lint` will run both
- vscode example settings for go linter - this enables a developer to copy the settings to his own `.vscode` folder and will run the same linter for go files (if using the vscode go extension)
[DTD-56]: https://portainer.atlassian.net/browse/DTD-56

chore(lint): add lint command

---

app/kubernetes/components/resource-reservation/resourceReservation.html
app/kubernetes/components/resource-reservation/resourceReservation.js
app/kubernetes/components/resource-reservation/resourceReservationController.js
app/kubernetes/metrics/metrics.js
app/kubernetes/metrics/rest.js
app/kubernetes/views/cluster/cluster.html
app/kubernetes/views/cluster/cluster.js
app/kubernetes/views/cluster/clusterController.js
app/kubernetes/views/cluster/node/node.html
app/kubernetes/views/cluster/node/node.js
app/kubernetes/views/cluster/node/nodeController.js
app/kubernetes/views/resource-pools/edit/resourcePool.html
app/kubernetes/views/resource-pools/edit/resourcePoolController.js

Closes EE-1112.
This PR introduces displaying resource usage on the cluster, node and namespace views for a k8s endpoint - if metrics server is enabled.
Note: The usage is only viewable by admin role
---
Display k8s resource usage on cluster view - using k8s metrics server API:
---
Display k8s resource usage on node view - using k8s metrics server API:
---
Display k8s resource usage on namespace view - using k8s metrics server API:
---

feat(kubernetes/resource-usage): k8s resource usage for cluster, node and namespace EE-3 EE-1112

---

api/git/git.go

Our client usage of go-git library was ignoring the proxy server settings

fix(git): proxy git requests

---

app/kubernetes/views/cluster/cluster.html
app/kubernetes/views/cluster/clusterController.js
app/kubernetes/views/cluster/node/node.html
app/kubernetes/views/cluster/node/nodeController.js
app/kubernetes/views/resource-pools/edit/resourcePoolController.js

Closes [EE-1273](https://portainer.atlassian.net/browse/EE-1273), [EE-1274](https://portainer.atlassian.net/browse/EE-1274).
If metric server api is disabled for k8s endpoint, this bugfix will also:
- disable metric server api call on cluster view
- disable metric server api call on node view
- disable metric server api call on namespace view

fix(metrics): disable metric server api calls if metric server is disabled on k8s endpoint EE-1273 EE-1274

---

app/kubernetes/components/datatables/resource-pools-datatable/resourcePoolsDatatable.html
app/kubernetes/components/datatables/resource-pools-datatable/resourcePoolsDatatableController.js
app/kubernetes/services/namespaceService.js

Closes [EE-1550](https://portainer.atlassian.net/browse/EE-1550)
This PRs brings the following:

feat(k8s): display namespace status [EE-1550]

---

api/http/handler/websocket/pod.go
api/kubernetes/cli/exec.go
api/portainer.go

Closes [EE-1520](https://portainer.atlassian.net/browse/EE-1520).
- fixed zombie kubectl shell pod issue
- spawned kuebctl shell pods were not removed after websocket disconnection
- fixed bug with websocket connection error - raised when re-opening kubectl shell in quick succession

fix(kubectl/shell): zombie pods and websocket connection error bugfixes EE-1520

---

api/http/handler/stacks/create_kubernetes_stack.go
api/http/handler/stacks/stack_create.go
app/kubernetes/models/deploy.js
app/kubernetes/views/deploy/deploy.html
app/kubernetes/views/deploy/deployController.js

Closes [EE-1546](https://portainer.atlassian.net/browse/EE-1546)
It brings the following:
* Introduce a new URL build method in advanced deployment to deploy a manifest from a URL
NOTE: Requires https://github.com/portainer/portainer/pull/5535 to be able to deploy from a URL in the default namespace
Requires portainer/agent#206 to be used with an agent deployment.

feat(k8s): add the ability to deploy from a manifest URL

---

api/go.mod
api/go.sum
api/http/handler/helm/handler.go
api/http/handler/helm/user_helm_repos.go
api/http/handler/users/handler.go
app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.controller.js
app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.js
app/kubernetes/components/helm/helm-templates/helm-templates.controller.js
app/kubernetes/components/helm/helm-templates/helm-templates.js
app/kubernetes/helm/rest.js
app/kubernetes/helm/service.js
app/kubernetes/views/applications/applications.js
app/kubernetes/views/applications/applicationsController.js
app/kubernetes/views/applications/helm/helm.controller.js
app/kubernetes/views/applications/helm/index.js
app/portainer/rest/user.js
app/portainer/services/api/userService.js

- migrated user_helm_repos to helm endpoint handler
- migrated api operations from user factory/service to helm factory/service
- passing endpointId into helm service/factory as endpoint provider is deprecated

fix(helm): migrating code from user handler to helm handler

---

api/http/handler/helm/helm_delete.go
api/http/handler/helm/helm_install.go
api/http/handler/helm/helm_list.go
api/http/handler/helm/helm_repo_search.go
api/http/handler/helm/helm_show.go
api/http/handler/helm/user_helm_repos.go
api/http/handler/kubernetes/kubernetes_nodes_limits.go
api/http/handler/settings/settings_update.go
api/portainer.go
app/kubernetes/__module.js
app/kubernetes/components/datatables/applications-datatable-url/applications-datatable-url.css
app/kubernetes/components/datatables/applications-datatable-url/applications-datatable-url.html
app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
app/kubernetes/components/datatables/applications-datatable/applicationsDatatableController.js
app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.controller.js
app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.html
app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.js
app/kubernetes/components/helm/helm-templates/helm-templates.controller.js
app/kubernetes/components/helm/helm-templates/helm-templates.html
app/kubernetes/helpers/application/index.js
app/kubernetes/views/applications/applications.html
app/kubernetes/views/applications/applicationsController.js
app/kubernetes/views/applications/helm/helm.controller.js

Closes [EE-1582](https://portainer.atlassian.net/browse/EE-1582), [EE-1593](https://portainer.atlassian.net/browse/EE-1593).
- trim trailing slash and lowercase before persisting helm repo
- browser helm templates url /kubernetes/templates/templates -> /kubernetes/templates/helm
- fix publish url
- fix helm repo add refresh
- semi-fix k8s app expansion
- fix swagger variable K8sNodesLimits in api/http/handler/kubernetes/kubernetes_nodes_limits.go
- change swagger helm section from helm_charts to helm and ensure user repo endpoints are listed under helm
- fallback to loadbalancer url for published urls

fix(helm): helm epic bugfixes EE-1582 EE-1593

---

README.md

The slack link in the readme was wrong.  It's now portainer.slack.com

doc(readme) fix slack link

---

app/config.js

This pr will introduce these changes:
1. close button for error toast
2. progress bar showing the timeout of message 
3. TapToDismiss is disabled, timeout counter will stop and message will stay as long as mouse on toast
close EE-1652

feat(ui): fix error message not last long enough for user to copy error EE-1652

---

app/assets/css/vendor-override.css
app/kubernetes/components/datatables/applications-ports-datatable/applicationsPortsDatatable.html
app/kubernetes/components/datatables/configurations-datatable/configurationsDatatable.html
app/kubernetes/components/kubernetes-sidebar/kubernetes-sidebar.html
app/kubernetes/converters/application.js
app/kubernetes/converters/service.js
app/kubernetes/filters/applicationFilters.js
app/kubernetes/filters/configurationFilters.js
app/kubernetes/models/application/formValues.js
app/kubernetes/models/application/models/constants.js
app/kubernetes/views/applications/create/createApplication.html
app/kubernetes/views/applications/create/createApplicationController.js
app/kubernetes/views/applications/edit/application.html
app/kubernetes/views/configurations/configurations.html
app/kubernetes/views/configurations/create/createConfiguration.html
app/kubernetes/views/configurations/edit/configuration.html
app/kubernetes/views/summary/summary.html
app/portainer/components/sidebar/sidebar.css

Closes [EE-1626](https://portainer.atlassian.net/browse/EE-1626).
- We accurately reflect the underlying service type in the UI, this implied changing the following service type in the UI.
- `Internal` -> `ClusterIP`
- `Cluster` -> `NodePort`
---
- The description has been updated for all the service types to now also explicitly state the type of service for the application
- Table heading updated
---
- Create/Update application has an additional panel from which we can expose/deploy services
---
- portainer lingo for services translated to k8s service types (in both application create and update views)
---
- k8s application list view publishing mode column displays k8s service type
- port mappings table publishing mode column also updated 
Configurations list view:
---
Configuration …

feat(configurations): portainer k8s configurations lingo update for explicitness EE-1626

---

api/bolt/migrator/migrate_dbversion31.go

[EE-1768]
This PR adds a warning when migrating to db v31 fails because of a missing snapshot
[EE-1768]: https://portainer.atlassian.net/browse/EE-1768

fix(db): warn on missing docker id when migrating to db 31

---

api/bolt/migrate_data.go

Fixes [EE-1971](https://portainer.atlassian.net/browse/EE-1971)
An error where a panic during db migration would cause an error like the following to show in the CE edition.
> level=info msg="2021/10/24 08:11:57 The Portainer database is set for Portainer Business Edition, please follow the instructions in our documentation to downgrade it: https://documentation.portainer.io/v2.0-be/downgrade/be-to-ce/"

fix(migration): bubble up recovered panic in new error EE-1971

---

api/http/handler/helm/handler.go
api/http/handler/helm/helm_delete_test.go
api/http/handler/helm/helm_install_test.go
api/http/handler/helm/helm_list_test.go
api/http/security/bouncer.go
api/http/security/bouncer_test.go
api/http/server.go

Closes [EE-1891](https://portainer.atlassian.net/browse/EE-1891).
- Additional of `AnyAuth` middleware - into which one can pass in multiple auth middlewares and if any middlewares successfully process the request, then the successful middleware is used to process the actual request.
- This allows us to support multiple auth paradigms
- The API access token auth is in TODO as the backend implementation requires access to the datastore which will contain api access tokens - to be implemented by [EE-1889](https://portainer.atlassian.net/browse/EE-1889).

feat(access-token): Multi-auth middleware support EE-1891

---

api/http/handler/handler.go
api/portainer.go
package.json

Pre-release for 2.9.3
[EE-1979](https://portainer.atlassian.net/browse/EE-1979)
Branch release/2.9  is already done.  This is for develop

chore(version): update version to 2.9.3 EE-1979

---

api/apikey/apikey.go
api/apikey/cache.go
api/apikey/service.go
api/apikey/service_test.go
api/bolt/apikey/apikey.go
api/bolt/apikeyrepository/apikeyrepository.go
api/bolt/datastore.go
api/bolt/services.go
api/cmd/portainer/main.go
api/go.mod
api/go.sum
api/http/handler/users/handler.go
api/http/handler/users/user_create_access_token.go
api/http/handler/users/user_create_access_token_test.go
api/http/handler/users/user_delete.go
api/http/handler/users/user_delete_test.go
api/http/handler/users/user_get_access_tokens.go
api/http/handler/users/user_get_access_tokens_test.go
api/http/handler/users/user_remove_access_token.go
api/http/handler/users/user_remove_access_token_test.go
api/http/security/bouncer.go
api/http/security/bouncer_test.go
api/http/server.go
api/internal/testhelpers/datastore.go
api/portainer.go

Closes [EE-1889](https://portainer.atlassian.net/browse/EE-1889),  [EE-1888](https://portainer.atlassian.net/browse/EE-1888),  [EE-1895](https://portainer.atlassian.net/browse/EE-1895)
- Endpoint to generate user access token (api-key)
- This endpoint requires JWT auth (api-key auth cannot be used to create more api-keys)
- An admin user cannot generate api-keys for other users
- Endpoint to retrieve all user access tokens
- Endpoint to revoke existing user access token
- Tests for all the functionality above
- APIKey middleware to authenticate and authorise `x-api-key` based requests
- note: the key can be present in request header or as query param (similar to JWT auth)
- APIKey caching to improve middleware performance (api-key -> user mapping lookups)
```sh
curl -X POST \
-H …
```

feat(api-key): user-access-token generation endpoint EE-1889 EE-1888 EE-1895

---

api/apikey/apikey.go
api/apikey/service.go
api/apikey/service_test.go
api/http/security/bouncer.go
api/portainer.go

- prefixing generated api-keys with `ptr_`
- updated tests accordingly

Prefix generated api-keys with `ptr_`

---

api/bolt/migrator/migrate_ce.go
api/bolt/migrator/migrate_dbversion31.go
api/bolt/migrator/migrate_dbversion34.go
api/bolt/migrator/migrate_dbversion34_test.go
api/portainer.go

Ensure we call dockerhub migrate again to clean up and ensure we only have one migrated dockerhub entry.
Fixes [EE-2042](https://portainer.atlassian.net/browse/EE-2042)

fix(dockerhub-migration): prevent duplicate migrated dockerhub entries EE-2042

---

.github/workflows/validate-openapi-spec.yml
api/http/handler/edgegroups/edgegroup_list.go
api/http/handler/webhooks/webhook_list.go
package.json
yarn.lock

Addresses [EE-2056](https://portainer.atlassian.net/browse/EE-2056).
- run the following in a Github CI pipeline
- convert OAS 2.0 to OAS 3.0 (since a few of our handlers don't support OAS 2.0)
- validate OAS 3.0 spec
- resolve discrepancies/issues in the generated OAS3.0 spec
- update `package.json` to include dependencies and scripts which would allow a user to run generation and validation of OAS 3.0 spec locally

feat(openapi): github workflow to generate and validate openapi spec EE-2056

---

app/docker/views/images/import/importimage.html

The ngf-accept file filter has been removed as it erroneously hides accepted file types such as .tar.xz and .tar.bz2
(I raised that issue because I thought that those formats were not accepted by the front-end).
Attempts to add application/x-bzip2 and application/x-xz failed as they are not accepted MIME types.
Closes https://github.com/portainer/portainer/issues/5220

style(images): remove files filter from upload image task EE-1944

---

api/bolt/stack/stack.go
api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/stack_list.go
api/portainer.go

The delete func basically follows the process defined in stack_delete.go. 
It does not call the handler.deleteStack(), because I believe this is to handle the swarm stack removal via swarm command.

fix(stack): support removing duplicated stacks EE-1962

---

api/http/handler/webhooks/webhook_execute.go

This fixes a bug where image names that contain a port number were inadvertently truncated (because port numbers are specified with a colon, just like the image tag).
For example, updating an image named `registry.example.com:5000/myimage:oldtag` with the new image tag `newtag` was incorrectly transformed into `registry.example.com:newtag`
---
I'm unfortunately unfamiliar with testing in Go, so I have not been able to add any automated tests. However, I have tested this fix manually, by performing the following steps:
1. Create a service in Portainer with the image `registry.example.com:5000/myimage:latest`
2. Enable the webhook in the Portainer UI
3. Make a request to the webhook _without_ specifying a new tag, e.g.:
` curl -X POST -k …

fix(webhooks): support image names containing a port number [EE-493]

---

app/portainer/views/endpoints/create/createEndpointController.js
app/portainer/views/wizard/wizard-endpoints/wizard-endpoint-docker/wizard-docker.controller.js

Windows server 2019 doesn't have `-L` or `&&` in the powershell I was on (freshly installed for #5890)

fix(endpoints): use the right command for windows agent EE-1877

---

CONTRIBUTING.md
gruntfile.js

documented the 2 existing env vars, and added a new one so I can add some defaults to every run (notably, my admin password, so I don' have to do the initialization steps)
https://portainer.atlassian.net/browse/EE-2076

chore(build): EE-2076: add a PORTAINER_FLAGS env var for yarn so I can default a password, and enable feature flags

---

api/bolt/migrate_data.go
api/bolt/migrator/migrate_ce.go
api/bolt/migrator/migrate_dbversion22.go
api/bolt/migrator/migrate_dbversion23.go
api/bolt/migrator/migrate_dbversion24.go
api/bolt/migrator/migrate_dbversion25.go
api/bolt/migrator/migrate_dbversion26.go
api/bolt/migrator/migrate_dbversion29.go
api/bolt/migrator/migrate_dbversion31.go
api/bolt/migrator/migrate_dbversion32.go
api/bolt/migrator/migrate_dbversion33.go
api/bolt/migrator/migrate_dbversion34.go

Closes [EE-2071](https://portainer.atlassian.net/browse/EE-2071)
Specifically, for logging of upgrades from the latest 1.x release to the current release.
This should help in diagnosing any issues during migration should there be a failure during upgrade.
I've also added a stack trace to the error returned from failsafe_migrate should a panic occur.
I haven't created any test code for this because as you can imagine, generating old data structures to run migrate is rather difficult.  I don't actually know what the old data looks like in many cases

feat(migrations): add more logging EE-2071

---

app/assets/css/app.css

[EE-2097]
[EE-2097]: https://portainer.atlassian.net/browse/EE-2097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(environments): show kubeconfig env list in dark mode

---

api/apikey/apikey.go
api/apikey/service.go
api/apikey/service_test.go
api/http/handler/users/user_remove_access_token.go
api/http/handler/users/user_remove_access_token_test.go

Closes [EE-2126](https://portainer.atlassian.net/browse/EE-2126).

fix(api-keys): standard user should not be able to delete another users api keys EE-2126

---

app/portainer/components/Button/CopyButton/CopyButton.tsx

Closes [EE-2122](https://portainer.atlassian.net/browse/EE-2122).

fix(api-key): fallback to deprecated copy text if clipboard api not available EE-2122

---

app/constants.js

related to #4071
adds the shared constants as es6. after merging this the best practice would be to use `export {CONSTANT} from `@/constants` (as done in edge/agent modules) instead of using the angular constants

refactor(app): duplicate constants as es6 exports [EE-1370]

---

package.json
yarn.lock

fixes [EE-2179]
since plugins of jquery rely on an existing instance of jquery, if we have more than one instance (as happend in our case), plugins won't necesarilly work. we need to keep jquery installed once (and hopefully soon enough, removed)
[EE-2179]: https://portainer.atlassian.net/browse/EE-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(modals): upgrade jquery versions [EE-2179]

---

api/http/proxy/factory/gitlab/transport.go

fixes [EE-2176]
this passes the request body to gitlab registry proxy.
for QA: need to check that gitlab registry is still working right on CE
[EE-2176]: https://portainer.atlassian.net/browse/EE-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(registries): sync code with ee [EE-2176]

---

api/cli/cli.go
api/cli/defaults.go
api/cli/defaults_windows.go
api/cmd/portainer/import.go
api/cmd/portainer/log.go
api/cmd/portainer/main.go
api/connection.go
api/database/boltdb/db.go
api/database/boltdb/export.go
api/database/boltdb/json.go
api/database/boltdb/json_test.go
api/database/database.go
api/dataservices/endpoint/endpoint.go
api/dataservices/errors/errors.go
api/dataservices/helmuserrepository/helmuserrepository.go
api/dataservices/interface.go
api/datastore/backup.go
api/datastore/backup_test.go
api/datastore/datastore.go
api/datastore/services.go
api/datastore/teststore.go
api/portainer.go

Working implementation of [EE-1852](https://portainer.atlassian.net/browse/EE-1852) - portainer.db encryption
Supports:
- Portainer secret is loaded from `/run/secrets/portainer`
- Bootstrapping directly to a new encrypted db if the secret is present and Portainer started for the first time
- Migrating an unencrypted db to an encrypted `portainer.edb` by creating a secret.

feat(database): add encryption support EE-1983

---

api/backup/backup.go
api/backup/restore.go
api/cmd/portainer/main.go
api/dataservices/interface.go
api/datastore/datastore.go
api/internal/testhelpers/datastore.go

Resolves [EE-2413](https://portainer.atlassian.net/browse/EE-2413)
Exposes the connection object to the data services layer so that we can query the correct db filename for creating the backup

fix(backup) use correct backup db file name EE-2413

---

api/http/proxy/factory/docker/transport.go

fixes [EE-2411]
ignore resource control object not found when deleting a docker resource
[EE-2411]: https://portainer.atlassian.net/browse/EE-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(docker): delete docker resources [EE-2411]

---

app/portainer/services/axios.ts

To support portainer running under a subdirectory such as  `https://xyz.com/portainer`, fixed API base URL in axios.ts

fix(home): axios base url fix

---

api/cli/cli.go
api/cli/defaults.go
api/cmd/portainer/main.go
api/datastore/init.go
api/internal/snapshot/snapshot.go
api/portainer.go

Closes [EE-2397](https://portainer.atlassian.net/browse/EE-2397)
- Set default values for settings values (EnableTelemetry, SSO, SnapshotInterval) in `Init` method, only allow override `updateSettingsFromFlags` with cli flags.
- Move `DefaultSnapshotInterval` from cli flags defaults to portainer defaults, and reuse it in `SnapshotService`.
- Remove default value for `SnapshotInterval` flag, which would override the value stored in datastore.
- Small refactor in `bolt.Init()` for better code readability.

fix(settings): updateSettingsFromFlags only if dataStore is new [EE-2397]

---

api/cli/defaults.go
api/cli/defaults_windows.go
api/cmd/portainer/main.go

Closes [EE-2465](https://portainer.atlassian.net/browse/EE-2465)
- Change default value for `HTTPEnabled` to `false`, having it set as `true` as default results in it being impossible to pass value `false` to the flag
- Adjust `updateSettingsFromFlags` logic to only tamper with `sslSettings.HTTPEnabled` if either: 
- `http-disabled` is passed (set setting to `false`)
- `http-enabled` is passed (set setting to `true`) 
- use stored settings otherwise
The second change doesn't really modify the behaviour, it's just for cleaner code

fix(ssl): default httpEnabled to false [EE-2465]
