portainer/portainer

- app/edge/components/edge-stack-status/edgeStackStatus.css
> feat(edge-stacks): change acknowledged status color to blue

- api/http/handler/endpointedge/endpoint_edgestack_inspect.go
> feat(edge-compute): provide stack name to edge endpoint

- app/edge/components/group-form/groupForm.html
- app/edge/components/group-form/groupFormController.js
> feat(edge-groups): when no tags selected show empty list of endpoints

- app/docker/components/volumesNFSForm/volumesnfsForm.html
> feat(volumes): Revise the UX for creation of NFS volumes

- api/http/proxy/factory/docker/access_control.go
- api/http/proxy/factory/docker/transport.go
Closes #3662 
Also fixes a potential panic error.
> fix(api): update restricted volume browsing operation logic

- api/http/handler/edgegroups/associated_endpoints.go
- api/http/handler/edgegroups/edgegroup_update.go
- api/http/handler/endpoints/endpoint_delete.go
- api/http/handler/tags/tag_delete.go
> fix(edge-compute): add missing relations updates

- app/edge/views/edge-stacks/edgeStacksViewController.js
- app/edge/views/groups/edgeGroupsViewController.js
- app/portainer/views/endpoints/endpointsController.js
- app/portainer/views/groups/groupsController.js
- app/portainer/views/tags/tagsController.js
closes #3816
this pr implements sequential delete in edge groups, edge stacks, tags, endpoints, and endpoint groups.
> fix(edge-compute): use sequential delete in resources

- api/http/handler/stacks/stack_delete.go
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
- app/portainer/components/datatables/stacks-datatable/stacksDatatableController.js
> feat(stacks): prevent external stack removal by a non-administrator user

- api/cli/cli.go
> feat(cli): add deprecation warnings

- app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.html
> fix(networks): network without ipv6 should not be expand in container networks datatable

- app/portainer/views/templates/templates.html
- app/portainer/views/templates/templatesController.js
> fix(volumes): Non-admins can mount admin volumes through template deploy volume typeahead

- api/bolt/migrator/migrate_dbversion23.go
- api/bolt/migrator/migrator.go
Related to #3707 
Fix missing database migration.
> fix(bolt): migrate empty templates URL settings

- package.json
- yarn.lock
Related to #3645 
Fixes an issue with `$transition$` object being set to null.
> fix(yarn): downgrade router version

- api/http/handler/endpoints/endpoint_create.go
- api/http/handler/endpoints/endpoint_status_inspect.go
- api/http/handler/endpoints/endpoint_update.go
- api/portainer.go
- app/portainer/services/api/endpointService.js
- app/portainer/services/fileUpload.js
- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/create/createendpoint.html
- app/portainer/views/endpoints/edit/endpoint.html
- app/portainer/views/endpoints/edit/endpointController.js
- app/portainer/views/settings/settings.html
> feat(edge-compute): add specific edge endpoint checkin interval

- app/portainer/views/endpoints/edit/endpointController.js
> fix(endpoints):Copy command button

- api/http/handler/users/user_update.go
- app/portainer/services/api/userService.js
- app/portainer/views/users/edit/user.html
- app/portainer/views/users/edit/userController.js
> feat(users): enable rename username

- api/http/handler/users/user_delete.go
- app/portainer/components/datatables/users-datatable/usersDatatable.html
- app/portainer/components/datatables/users-datatable/usersDatatable.js
- app/portainer/components/datatables/users-datatable/usersDatatableController.js
- app/portainer/views/users/edit/user.html
- app/portainer/views/users/edit/userController.js
> feat(users): prevent the removal of initial admin account

- plop-templates/component.js.hbs
controller import wasn't valid in the component template. this PR fixes it
> chore(plop): fix controller import in template

- app/azure/components/azure-sidebar-content/azureSidebarContent.html
- app/azure/views/containerinstances/containerinstances.html
- app/docker/components/dockerSidebarContent/dockerSidebarContent.html
- app/docker/views/containers/containers.html
- app/docker/views/containers/edit/container.html
- app/docker/views/dashboard/dashboard.html
- app/docker/views/volumes/edit/volume.html
- app/docker/views/volumes/volumes.html
- app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
- app/portainer/components/forms/template-form/templateForm.html
- app/portainer/views/stacks/edit/stack.html
> fix(sidebar): replace icons for containers and volumes

- app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
> fix(endpoints): hide edge endpoint url

- api/http/handler/stacks/create_compose_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/http/handler/stacks/stack_create.go
- api/http/proxy/factory/docker/containers.go
- api/http/proxy/factory/docker/transport.go
> feat(containers): Ensure users cannot create privileged containers via the API

- api/http/handler/settings/settings_public.go
- api/http/handler/settings/settings_update.go
- api/http/handler/stacks/handler.go
- api/http/handler/stacks/stack_create.go
- api/portainer.go
- app/docker/components/dockerSidebarContent/docker-sidebar-content.js
- app/docker/components/dockerSidebarContent/dockerSidebarContent.html
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.js
- app/portainer/models/settings.js
- app/portainer/services/stateManager.js
- app/portainer/views/settings/settings.html
- app/portainer/views/settings/settingsController.js
- app/portainer/views/sidebar/sidebar.html
- app/portainer/views/stacks/stacks.html
- app/portainer/views/stacks/stacksController.js
> feat(stacks): add a setting to disable the creation of stacks for non-admin users

- app/extensions/registry-management/views/repositories/registryRepositoriesController.js
> fix(registries): hide zero tags repositories

- api/http/proxy/factory/docker/transport.go
- api/http/proxy/factory/docker/volumes.go
> feat(volumes): Ensure a unique identifier for volumes

- api/cmd/portainer/main.go
- api/http/handler/settings/settings_public.go
- api/http/handler/settings/settings_update.go
- api/http/handler/stacks/create_compose_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/http/handler/stacks/handler.go
- api/http/handler/stacks/stack_create.go
- api/http/proxy/factory/docker/containers.go
- api/portainer.go
- app/portainer/models/settings.js
- app/portainer/services/stateManager.js
- app/portainer/views/settings/settings.html
- app/portainer/views/settings/settingsController.js
> feat(containers): Prevent non-admin users from running containers using the host namespace pid

- app/docker/views/networks/create/createNetworkController.js
- app/docker/views/networks/create/createnetwork.html
- app/docker/views/networks/edit/network.html
> feat(networks): Support multiple excluded IPs for MACVLAN networks

- build/linux/Dockerfile
- build/linux/alpine.Dockerfile
- build/linux/toolkit.Dockerfile
- build/windows2016/nanoserver/Dockerfile
> feat(docker): expose port 8000 in Dockerfile

- app/docker/views/containers/create/createContainerController.js
> fix(container-creation): always rebuild exposed ports

- api/crypto/tls.go
- api/http/server.go
> feat(server): support minimum tls v1.2

- app/config.js
- app/docker/components/datatables/images-datatable/imagesDatatable.html
- app/docker/components/datatables/volumes-datatable/volumesDatatable.html
- app/portainer/components/datatables/genericDatatableController.js
- app/portainer/services/authentication.js
- app/portainer/services/endpointProvider.js
- app/portainer/services/localStorage.js
- app/portainer/views/main/mainController.js
> feat(settings): replace cookies with local storage

- api/bolt/migrator/migrate_dbversion22.go
- api/bolt/migrator/migrator.go
- api/cmd/portainer/main.go
- api/http/handler/settings/settings_public.go
- api/http/handler/settings/settings_update.go
- api/http/handler/stacks/create_compose_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/http/handler/stacks/stack_create.go
- api/http/proxy/factory/docker/containers.go
- api/portainer.go
- app/docker/views/containers/create/createContainerController.js
- app/docker/views/containers/create/createcontainer.html
- app/portainer/models/settings.js
- app/portainer/services/stateManager.js
- app/portainer/views/settings/settings.html
- app/portainer/views/settings/settingsController.js
> feat(settings): add setting to disable device mapping for regular users

- app/docker/views/containers/edit/containerController.js
- app/portainer/models/settings.js
- app/portainer/services/stateManager.js
- app/portainer/views/settings/settings.html
- app/portainer/views/settings/settingsController.js
> feat(containers): disable edit container on security setting restricting regular users

- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/configurations/create/createConfigurationController.js
- app/kubernetes/views/configurations/edit/configuration.html
- app/kubernetes/views/configurations/edit/configurationController.js
> feat(kubernetes): Prevent deployment/edition of resources inside a system namespace

- app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.html
> feat(aci): show container ip

- app/kubernetes/components/datatables/applications-ports-datatable/applicationsPortsDatatable.html
- app/kubernetes/components/datatables/applications-ports-datatable/applicationsPortsDatatableController.js
- app/kubernetes/converters/application.js
- app/kubernetes/filters/applicationFilters.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/helpers/serviceHelper.js
- app/kubernetes/ingress/converter.js
- app/kubernetes/ingress/helper.js
- app/kubernetes/ingress/models.js
- app/kubernetes/ingress/rest.js
- app/kubernetes/ingress/service.js
- app/kubernetes/models/application/models.js
- app/kubernetes/models/port/models.js
- app/kubernetes/models/service/models.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/views/applications/applicationsController.js
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
- jsconfig.json
Close #3991 
Useful technical resource used to do nested `ng-repeat` without changing the model to a single flat array that would duplicate values: https://stackoverflow.com/a/23699153/2987712
In a nutshell, applied code for us is (it's working with `ng-repeat-start / ng-repeat-end` instead of `dir-paginate-start / dir-paginate-end` but we needed pagination on the table).
```html
<tr dir-paginate-start="item in $ctrl.itemList">
</tr>
<tr ng-repeat-start="port in item.Ports">
</tr>
<tr ng-repeat-end ng-repeat="rule in port.Rules">
</tr>
<tr dir-paginate-end></tr>
```
This code will result in the following pseudo HTML table (each line represents a row)
```
item_1
port_1.1
rule_1.1.1
rule_1.1.2
...
rule_1.1.x
port_1.2
rule_1.2.1
...
item_2
port_2.1
...
```
Notes:
* `port_xxx` lines will only …
> feat(kubernetes): add ingress details

- app/extensions/registry-management/services/registryGitlabService.js
- app/extensions/registry-management/views/repositories/registryRepositoriesController.js
> fix(registries): filter gitlab repos without tags

- app/kubernetes/views/applications/logs/logs.html
- app/kubernetes/views/applications/logs/logsController.js
- app/kubernetes/views/stacks/logs/logs.html
- app/kubernetes/views/stacks/logs/logsController.js
> feat(logs): Add the ability to download application/stack logs

- api/bolt/migrator/migrate_dbversion22.go
- api/bolt/migrator/migrate_dbversion23.go
- api/bolt/migrator/migrator.go
- api/portainer.go
Review the database migration logic for 1.24.1.
Related to:
* https://github.com/portainer/portainer/issues/3936
* https://github.com/portainer/portainer/issues/3930
* https://github.com/portainer/portainer/issues/3958
> feat(database): review database migration

- app/azure/_module.js
- app/azure/components/azure-sidebar-content/azure-sidebar-content.js
- app/azure/components/azure-sidebar-content/azureSidebarContent.html
- app/docker/__module.js
- app/docker/components/dockerSidebarContent/docker-sidebar-content.js
- app/docker/components/dockerSidebarContent/dockerSidebarContent.html
- app/kubernetes/__module.js
- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.html
- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.js
- app/portainer/__module.js
- app/portainer/views/sidebar/sidebar.html
- app/portainer/views/sidebar/sidebarController.js
> fix(app): use deps injection in router correctly

- app/azure/_module.js
- app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.html
- app/azure/models/container_group.js
- app/azure/rest/container_group.js
- app/azure/rest/resource_group.js
- app/azure/rest/subscription.js
- app/azure/services/containerGroupService.js
- app/azure/services/resourceGroupService.js
- app/azure/services/subscriptionService.js
- app/azure/views/containerinstances/container-instance-details/containerInstanceDetails.html
- app/azure/views/containerinstances/container-instance-details/containerInstanceDetailsController.js
- app/azure/views/containerinstances/container-instance-details/index.js
> feat(aci): provide container details page

- build/windows2016/nanoserver/Dockerfile
Fixes #4043
Introduce a work-around for Windows build.
> feat(build/windows): update windows dockerfile

- api/http/handler/extensions/extension_create.go
- api/http/handler/extensions/extension_upload.go
- app/portainer/views/extensions/extensions.html
- app/portainer/views/extensions/extensionsController.js
> feat(core/extensions): add the ability to update a license

- app/__module.js
- app/agent/index.js
> refactor(agent): replace root file with index

- app/agent/models/agent.js
> refactor(agent): replace model with class

- app/portainer/components/custom-templates-list/customTemplatesList.html
- app/portainer/components/template-list/template-list-controller.js
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateView.html
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateViewController.js
- app/portainer/views/custom-templates/custom-templates-view/customTemplatesView.html
- app/portainer/views/custom-templates/custom-templates-view/customTemplatesViewController.js
- app/portainer/views/custom-templates/edit-custom-template-view/editCustomTemplateView.html
- app/portainer/views/custom-templates/edit-custom-template-view/editCustomTemplateViewController.js
- app/portainer/views/stacks/create/createstack.html
- app/portainer/views/stacks/edit/stack.html
> fix(templates): replace custom templates and stacks links

- app/agent/services/pingService.js
> refactor(agent): refactor pingService to es6

- app/agent/rest/agent.js
- app/agent/rest/browse.js
- app/agent/rest/host.js
- app/agent/rest/ping.js
- app/agent/rest/response/browse.js
- app/agent/rest/v1/agent.js
- app/agent/rest/v1/browse.js
> refactor(agent): refactor rest factories to es6

- app/agent/services/agentService.js
> refactor(agent): refactor agentService to es6

- app/agent/services/hostBrowserService.js
> refactor(agent): refactor hostBrowserService to es6

- app/agent/services/volumeBrowserService.js
> feat(agent): refactor volumeBrowserService to es6

- app/docker/views/containers/create/createContainerController.js
- app/docker/views/containers/create/createcontainer.html
> fix(container-creation): preselect network

- app/portainer/components/datatables/genericDatatableController.js
> fix(datatables): select table items

- api/portainer.go
> fix(extensions): load extensions file

- api/http/proxy/factory/docker/containers.go
- api/http/proxy/factory/docker/services.go
- api/http/proxy/factory/docker/transport.go
- app/docker/views/containers/create/createContainerController.js
- app/docker/views/containers/create/createcontainer.html
- app/docker/views/services/create/createServiceController.js
- app/docker/views/services/create/createservice.html
> feat(containers): enforce disable bind mounts

- app/azure/views/containerinstances/container-instance-details/containerInstanceDetails.html
> fix(aci): show container instance title

- app/docker/services/imageService.js
> fix(images): ignore pull image rejection

- api/bolt/migrator/migrate_dbversion23.go
- api/bolt/migrator/migrator.go
- api/http/handler/stacks/create_compose_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/http/handler/stacks/handler.go
- api/http/handler/stacks/stack_start.go
- api/http/handler/stacks/stack_stop.go
- api/portainer.go
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
- app/portainer/components/datatables/stacks-datatable/stacksDatatableController.js
- app/portainer/models/stack.js
- app/portainer/rest/stack.js
- app/portainer/services/api/stackService.js
- app/portainer/services/modalService.js
- app/portainer/views/stacks/edit/stack.html
- app/portainer/views/stacks/edit/stackController.js
> feat(stacks): add the option to stop a stack

- app/docker/views/containers/create/createContainerController.js
> fix(container-creation): allow resetting to unlimited

- api/http/handler/endpoints/endpoint_create.go
- api/http/handler/endpoints/endpoint_status_inspect.go
- api/portainer.go
- app/portainer/models/endpoint/models.js
- app/portainer/services/api/endpointService.js
- app/portainer/services/fileUpload.js
- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/create/createendpoint.html
- app/portainer/views/endpoints/edit/endpoint.html
- app/portainer/views/endpoints/edit/endpointController.js
- app/portainer/views/init/endpoint/initEndpointController.js
> feat(agent): add auto agent platform detection

- api/http/proxy/factory/kubernetes/token.go
- api/http/proxy/factory/kubernetes/transport.go
- api/kubernetes/cli/naming.go
- api/kubernetes/cli/service_account.go
- api/portainer.go
> fix(k8s/user): remove username part from service account

- api/kubernetes.go
- api/portainer.go
- app/kubernetes/converters/application.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/horizontal-pod-auto-scaler/converter.js
- app/kubernetes/horizontal-pod-auto-scaler/helper.js
- app/kubernetes/horizontal-pod-auto-scaler/models.js
- app/kubernetes/horizontal-pod-auto-scaler/payload.js
- app/kubernetes/horizontal-pod-auto-scaler/service.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/configure/configure.html
- app/kubernetes/views/configure/configureController.js
> feat(application): Add the ability to set the auto-scale policy of an application

- app/portainer/components/datatables/genericDatatableController.js
- app/portainer/views/registries/create/createRegistryController.js
> fix(datatables): deselect row

- app/kubernetes/services/applicationService.js
> fix(application): horizontal pod auto scaler breaks application edit

- app/docker/models/network.js
- app/docker/services/networkService.js
- app/docker/views/services/edit/includes/networks.html
- app/docker/views/services/edit/serviceController.js
> feat(services): Add the ability to edit a service networks

- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
> feat(namespace): prevent admins from making changes to "system" namespaces

- app/docker/views/containers/create/createContainerController.js
> fix(container-creation): handle extraHosts correctly

- app/docker/components/imageRegistry/por-image-registry.js
- app/docker/components/imageRegistry/porImageRegistry.html
- app/docker/views/containers/create/createContainerController.js
- app/docker/views/containers/create/createcontainer.html
> fix(container-creation): add default/override options

- api/portainer.go
- app/kubernetes/converters/persistentVolumeClaim.js
- app/kubernetes/converters/storageClass.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/models/storage-class/models.js
- app/kubernetes/models/storage-class/payload.js
- app/kubernetes/rest/storage.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/services/storageService.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/configure/configure.html
- app/kubernetes/views/configure/configureController.js
- app/kubernetes/views/volumes/edit/volume.html
- app/kubernetes/views/volumes/edit/volumeController.js
- app/portainer/services/modalService.js
> feat(application): Add the ability to use existing volumes when creating an application

- app/docker/views/containers/create/createcontainer.html
- app/edge/components/group-form/groupForm.html
- app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackView.html
- app/portainer/views/stacks/create/createstack.html
> refactor(UX): fix improper grammar

- app/kubernetes/services/storageService.js
- app/kubernetes/views/configure/configureController.js
> fix(storage): missing endpoint id in storage patch request

- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
> feat(resourcepool): Reducing the Quota assigned to a RP

- app/docker/components/host-view-panels/node-labels-table/node-labels-table.html
- app/docker/components/host-view-panels/swarm-node-details-panel/swarm-node-details-panel.html
> refactor(UX): change table to div and fix styling

- app/assets/css/app.css
> fix(ux): fix checkbox sizing

- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.html
> feat(k8s/sidebar): add a setup sidebar entry

- app/docker/__module.js
> feat(routes): add /docker parent route

- app/edge/components/associated-endpoints-datatable/associatedEndpointsDatatableController.js
- app/edge/components/edge-job-form/edgeJobFormController.js
- app/edge/components/edge-stack-endpoints-datatable/edgeStackEndpointsDatatableController.js
- app/edge/components/edit-edge-stack-form/editEdgeStackFormController.js
- app/edge/components/groups-datatable/groupsDatatableController.js
- app/edge/views/edge-jobs/createEdgeJobView/createEdgeJobViewController.js
- app/edge/views/edge-jobs/edgeJob/edgeJobController.js
- app/edge/views/edge-jobs/edgeJobsView/edgeJobsViewController.js
- app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackViewController.js
- app/edge/views/edge-stacks/edgeStacksView/edgeStacksViewController.js
- app/edge/views/edge-stacks/editEdgeStackView/editEdgeStackViewController.js
> fix(edge): fix edge views

- app/agent/components/node-selector/nodeSelectorController.js
> fix(nodes): add ngInject to node-select

- app/kubernetes/views/applications/create/createApplication.html
> feat(application): Update form validation for environment variables when deploying an application

- app/kubernetes/converters/application.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/views/applications/create/createApplicationController.js
> feat(kubernetes): add default values for auto scaler

- app/kubernetes/components/datatables/volumes-datatable/volumesDatatable.html
> feat(volumes): Enhance the used by column for volumes

- app/kubernetes/views/cluster/node/node.html
> fix(k8s/node): only show API address field for nodes tagged as API

- app/kubernetes/views/volumes/edit/volumeController.js
> fix(k8s/volume): only show resize modal for used volumes

- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.html
- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.js
- app/portainer/views/sidebar/sidebar.html
> feat(k8s/sidebar): relocate setup entry as a sub-entry

- app/portainer/views/settings/settings.html
> feat(core/settings): rename settings sections

- app/kubernetes/node/converter.js
- app/kubernetes/node/formValues.js
- app/kubernetes/node/helper.js
- app/kubernetes/node/models.js
- app/kubernetes/node/payload.js
- app/kubernetes/node/rest.js
- app/kubernetes/node/service.js
- app/kubernetes/views/applications/edit/applicationController.js
- app/kubernetes/views/applications/edit/components/placements-datatable/template.html
- app/kubernetes/views/cluster/node/node.html
- app/kubernetes/views/cluster/node/nodeController.js
> feat(node): Add the ability to apply taints and labels to nodes

- api/bolt/version/version.go
- api/cmd/portainer/main.go
- api/kubernetes/cli/client.go
- api/kubernetes/cli/naming.go
- api/kubernetes/cli/secret.go
- api/kubernetes/cli/service_account.go
- api/portainer.go
> feat(k8s): use instance ID to create unique k8s resources

- app/kubernetes/components/feedback-panel/feedbackPanel.html
- app/kubernetes/components/feedback-panel/feedbackPanel.js
- app/kubernetes/views/dashboard/dashboard.html
> feat(k8s/dashboard): remove the RC banner

- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
> feat(k8s/resource-pool): change default behavior for resource assignment

- app/kubernetes/__module.js
- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.html
- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.js
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/kubernetes/components/datatables/node-applications-datatable/nodeApplicationsDatatable.html
- app/kubernetes/components/datatables/resource-pool-applications-datatable/resourcePoolApplicationsDatatable.html
- app/kubernetes/converters/application.js
- app/kubernetes/converters/deployment.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/helpers/resourceReservationHelper.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/models/application/models/index.js
- app/kubernetes/pod/converter.js
- app/kubernetes/pod/filters.js
- app/kubernetes/pod/models/index.js
- app/kubernetes/pod/service.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/views/applications/console/consoleController.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
- app/kubernetes/views/applications/logs/logsController.js
- app/kubernetes/views/stacks/logs/logsController.js
> feat(application): Support multi-container pods applications

- app/kubernetes/converters/application.js
- app/kubernetes/converters/daemonSet.js
- app/kubernetes/converters/deployment.js
- app/kubernetes/converters/statefulSet.js
- app/kubernetes/filters/applicationFilters.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/models/application/models/constants.js
- app/kubernetes/models/daemon-set/models.js
- app/kubernetes/models/deployment/models.js
- app/kubernetes/models/deployment/payloads.js
- app/kubernetes/models/stateful-set/models.js
- app/kubernetes/node/helper.js
- app/kubernetes/pod/converter.js
- app/kubernetes/pod/models/affinities.js
- app/kubernetes/pod/models/index.js
- app/kubernetes/pod/payloads/affinities.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/applications/edit/applicationController.js
- app/kubernetes/views/applications/edit/components/placements-datatable/template.html
> feat(k8s/application): add/edit placement preferences/constraints

- app/kubernetes/models/application/formValues.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
> feat(k8s/application): add constraints validation

- app/docker/views/dashboard/dashboard.html
- app/docker/views/dashboard/dashboardController.js
- app/kubernetes/views/dashboard/dashboard.html
- app/kubernetes/views/dashboard/dashboardController.js
> fix(dashboard): show endpoint tags

- app/portainer/oauth/components/oauth-settings/oauth-settings-controller.js
> fix(oauth): select no-team by default

- app/portainer/views/home/homeController.js
> fix(endpoints): load endpoints and tags together

- api/kubernetes.go
- api/portainer.go
- app/kubernetes/converters/application.js
- app/kubernetes/converters/service.js
- app/kubernetes/ingress/constants.js
- app/kubernetes/ingress/converter.js
- app/kubernetes/ingress/models.js
- app/kubernetes/ingress/service.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/models/resource-pool/formValues.js
- app/kubernetes/services/resourcePoolService.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
- app/kubernetes/views/configure/configure.html
- app/kubernetes/views/configure/configureController.js
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/create/createResourcePoolController.js
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
Rework of the ingress configuration / management.
> feat(k8s/ingresses): add more granularity to ingress configuration

- app/portainer/views/stacks/create/createstack.html
> feat(stacks): disable creation when editor or template is empty

- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateViewController.js
- app/portainer/views/custom-templates/edit-custom-template-view/editCustomTemplateViewController.js
> feat(custom-templates): validate unique template name

- app/kubernetes/components/datatables/volumes-datatable/volumesDatatableController.js
> fix(k8s/volumes): fix an issue with the system volume filter not working

- build/download_kompose_binary.ps1
- build/download_kubectl_binary.ps1
- gruntfile.js
> feat(ci): add missing powershell scripts & fix related grunt code

- app/portainer/components/datatables/genericDatatableController.js
This pull request will resolve #3741
> #3741 fix(datatables): fixes datatable selection count on text filter

- README.md
> fix(readme): fix grammar errors in readme

- app/app.js
- app/portainer/views/sidebar/sidebarController.js
> feat(frontend): show endpoint.name in page title

- app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
> fix(endpoints): broken datatable sorting

- app/docker/rest/container.js
- app/docker/rest/image.js
- app/docker/rest/network.js
- app/docker/rest/service.js
- app/docker/rest/system.js
- app/docker/rest/task.js
- app/docker/rest/volume.js
- app/integrations/storidge/rest/storidge.js
- app/kubernetes/component-status/rest.js
- app/kubernetes/endpoint/rest.js
- app/kubernetes/horizontal-pod-auto-scaler/rest.js
- app/kubernetes/ingress/rest.js
- app/kubernetes/node/rest.js
- app/kubernetes/rest/configMap.js
- app/kubernetes/rest/controllerRevision.js
- app/kubernetes/rest/daemonSet.js
- app/kubernetes/rest/deployment.js
- app/kubernetes/rest/endpoint.js
- app/kubernetes/rest/event.js
- app/kubernetes/rest/health.js
- app/kubernetes/rest/namespace.js
- app/kubernetes/rest/persistentVolumeClaim.js
- app/kubernetes/rest/pod.js
- app/kubernetes/rest/replicaSet.js
- app/kubernetes/rest/resourceQuota.js
- app/kubernetes/rest/secret.js
- app/kubernetes/rest/service.js
- app/kubernetes/rest/statefulSet.js
- app/kubernetes/rest/storage.js
> fix(rest): remove timeouts for all REST services

- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.html
- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.js
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatableController.js
- app/kubernetes/converters/application.js
- app/kubernetes/filters/applicationFilters.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/helpers/application/rollback.js
- app/kubernetes/helpers/history/index.js
- app/kubernetes/helpers/serviceHelper.js
- app/kubernetes/horizontal-pod-auto-scaler/helper.js
- app/kubernetes/models/application/models/constants.js
- app/kubernetes/models/common/params.js
- app/kubernetes/pod/service.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/services/historyService.js
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
- app/portainer/views/init/endpoint/initEndpointController.js
> feat(k8s/applications): exposed naked pods as applications

- app/kubernetes/services/configMapService.js
> fix(frontend): cannnot access configuration details view containing binary data (#4503)

- app/kubernetes/views/configurations/create/createConfigurationController.js
> fix(frontend): revalidate configuration name when change resource pool (#4553)

- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.html
- app/portainer/views/sidebar/sidebar.html
> fix(k8s/sidebar): accessing cluster setup not expand endpoint sidebar

- app/kubernetes/converters/application.js
> fix(frontend): override configuration keys disappear (#4547)

- app/kubernetes/views/cluster/node/nodeController.js
> fix(k8s/node): sort labels

- app/kubernetes/views/applications/edit/applicationController.js
> fix(k8s/application): refreshing yaml panel doesn't change the selected panel

- app/kubernetes/converters/secret.js
> fix(k8s/configuration): save the owner when updating the configuration

- app/kubernetes/views/applications/applicationsController.js
- app/kubernetes/views/configurations/configurationsController.js
> feat(kube): Add a confirmation modal before deleting one or more application or configuration

- app/docker/models/config.js
Closes #4101 
The solution is to fallback to atob when there is an error in the Unicode base64 decode.
> fix(configs): fix error with binary file

- app/portainer/views/endpoints/edit/endpoint.html
- app/portainer/views/endpoints/edit/endpointController.js
> feat(app/endpoint): edge deployment for windows

- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/create/createendpoint.html
> feat(app/endpoint): add deployment instructions for windows

- gruntfile.js
> chore(build): bump Kompose version

- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
> fix(k8s/application): improve ux for instance count input

- app/kubernetes/views/deploy/deploy.html
> feat(k8s/advanced-deployment): update extra information message

- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationData.html
> feat(k8s/configuration): rename create entry file button

- README.md
> docs(README): update README contribution link

- app/portainer/services/api/endpointService.js
- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/create/createendpoint.html
- app/portainer/views/home/home.html
- app/portainer/views/init/endpoint/initEndpoint.html
- app/portainer/views/init/endpoint/initEndpointController.js
> feat(endpoint): start Portainer without endpoint

- app/kubernetes/views/configure/configure.html
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/portainer/__module.js
- app/portainer/components/accessManagement/porAccessManagement.html
- app/portainer/components/datatables/access-viewer-datatable/accessViewerDatatable.html
- app/portainer/components/datatables/access-viewer-datatable/accessViewerDatatable.js
- app/portainer/components/datatables/registries-datatable/registriesDatatable.html
- app/portainer/components/datatables/roles-datatable/rolesDatatable.html
- app/portainer/components/datatables/roles-datatable/rolesDatatable.js
- app/portainer/views/roles/roles.html
- app/portainer/views/settings/authentication/settingsAuthentication.html
- app/portainer/views/sidebar/sidebar.html
> feat(app): add a preview for business edition features

- app/assets/css/app.css
- app/docker/views/services/create/createServiceController.js
- app/docker/views/services/create/createservice.html
- app/docker/views/services/edit/includes/mounts.html
- app/docker/views/services/edit/serviceController.js
> fix(services): prevent adding volume without source and target

- app/docker/components/log-viewer/log-viewer.js
- app/docker/components/log-viewer/logViewer.html
- app/docker/components/log-viewer/logViewerController.js
- app/docker/views/containers/logs/containerlogs.html
- app/docker/views/services/logs/servicelogs.html
- app/docker/views/tasks/logs/tasklogs.html
> feat(app/logs): add download button on logs views

- api/http/handler/stacks/create_compose_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/http/handler/stacks/stack_update.go
- api/portainer.go
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
- app/portainer/helpers/stackHelper.js
- app/portainer/models/stack.js
- app/portainer/services/api/stackService.js
> feat(docker/stacks): add creation and update dates

- app/docker/views/volumes/edit/volumeController.js
- app/docker/views/volumes/volumesController.js
> feat(app/volumes): add confirmation modal before deleting volumes

- app/kubernetes/converters/application.js
- app/kubernetes/helpers/commonHelper.js
- app/kubernetes/services/configurationService.js
- app/kubernetes/services/resourcePoolService.js
> fix(k8s/application): transform username to be dns compliant (#4595)

- app/kubernetes/services/applicationService.js
> fix(k8s/application): ability to remove naked pods

- api/http/handler/stacks/create_compose_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/http/handler/stacks/stack_update.go
- api/portainer.go
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
- app/portainer/helpers/stackHelper.js
- app/portainer/models/stack.js
- app/portainer/services/api/stackService.js
Reverts portainer/portainer#4418
> Revert "feat(docker/stacks): add creation and update dates"

- build/download_docker_binary.ps1
- build/download_kompose_binary.ps1
- build/download_kubectl_binary.ps1
> Improve windows CI build speed

- gruntfile.js
Reverts portainer/portainer#4475
> Revert "chore(build): bump Kompose version"

- api/portainer.go
* bump the APIVersion to 2.0.1
> fix(2.0.1) bump APIVersion to 2.0.1

- app/kubernetes/templates/advancedDeploymentPanel.html
- app/kubernetes/views/applications/applications.html
- app/kubernetes/views/applications/applicationsController.js
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
- app/kubernetes/views/configurations/configurations.html
- app/kubernetes/views/configurations/configurationsController.js
- app/kubernetes/views/volumes/volumes.html
- app/kubernetes/views/volumes/volumesController.js
> feat(k8s/resources-list-view): add advanced deployment panel to resources list view

- .github/stale.yml
change stalebot to ignore refactor issues for https://github.com/portainer/portainer/issues/4071#issuecomment-753684650
> chore(project): exclude refactors

- app/assets/css/app.css
- app/portainer/views/auth/auth.html
- app/portainer/views/auth/authController.js
> feat(frontend): de-emphasize internal login when OAuth is enabled (#3065)

- app/kubernetes/views/configurations/create/createConfiguration.html
> feat(k8s/configuration): add extra information panel when creating a sensitive configuration

- app/kubernetes/views/configure/configure.html
> feat(k8s/configuration): rename add ingress controller button and changed information text

- api/cmd/portainer/main.go
Fix an issue with portainer not being able to restart
Fixes #4523
> fix(settings): Use default setting if UserSessionTimeout not set

- package.json
- webpack/webpack.common.js
- webpack/webpack.develop.js
- webpack/webpack.production.js
- yarn.lock
> chore(webpack): add source maps

- app/docker/views/services/create/createservice.html
> feat(service): clear source volume when change type

- app/portainer/views/stacks/edit/stack.html
> #4424 style(stack-details): shift button position in stack details

- app/kubernetes/views/applications/create/createApplication.html
> feat(k8s/application): review application creation warning style

- app/docker/views/networks/create/createnetwork.html
> feat(app/network): rename restrict external acces to the network label

- app/docker/components/imageRegistry/porImageRegistry.html
> feat(app/images): in advanced mode, remove tooltip and add information message

- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
> fix(k8s/application): validate load balancer ports inputs

- app/kubernetes/components/datatables/applications-stacks-datatable/applicationsStacksDatatable.html
- app/kubernetes/views/volumes/components/volumes-storages-datatable/template.html
> fix(k8s/datatables): reduce size of collapse/expand column for stacks datatable and storage datatable

- app/index.html
> chore(app): fail on angular components missing nginject

- gruntfile.js
> chore(build): bump Kompose version (#4473)

- api/http/handler/registries/registry_update.go
> fix(registries): update password only when not empty

- app/portainer/services/stateManager.js
> fix(state): check validity of state

- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
> feat(placement): Add a warning notification under the placement tab when an application cannot be scheduled on any node in the cluster

- api/exec/compose_wrapper.go
- api/http/handler/endpoints/endpoint_inspect.go
- api/http/handler/endpoints/endpoint_list.go
- api/http/handler/endpoints/handler.go
- api/http/server.go
- api/libcompose/compose_stack.go
- api/portainer.go
- app/portainer/views/stacks/create/createStackController.js
- app/portainer/views/stacks/create/createstack.html
> feat: pass max supported compose syntax version with each endpoint

- api/http/handler/stacks/handler.go
- api/http/handler/stacks/stack_create.go
- api/internal/authorization/access_control.go
> fix(stack): stacks created via API are incorrectly marked as private with no owner (#3721)

- app/kubernetes/pod/converter.js
- app/kubernetes/pod/payloads/create.js
- app/kubernetes/pod/service.js
- app/kubernetes/rest/pod.js
> fix(kubernetes/pods): save note

- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
> fix(k8s/app): remove advanced deployment panel from app details view

- build/download_kubectl_binary.sh
* fix missing kubectl download
> (fix) missing kubectl download

- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
> fix(k8s) trigger port validation while changing protocol (ce#394)

- app/docker/views/services/edit/includes/mounts.html
> fix(docker/service): enable apply change button when editing mounts section

- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.html
- app/kubernetes/converters/application.js
- app/kubernetes/pod/converter.js
- app/kubernetes/pod/models/index.js
- app/kubernetes/views/applications/edit/application.html
> feat(kube/app): show image pull policy

- app/docker/views/services/create/includes/secret.html
> feat(docker/services): update the information message about default location of secrets

- app/portainer/views/endpoints/edit/endpointController.js
> fix(edge): invalid command displayed for Edge agent deployment on Docker standalone (#4732)

- app/docker/components/datatables/services-datatable/servicesDatatableController.js
- app/docker/views/services/servicesController.js
- app/portainer/components/datatables/genericDatatableController.js
> fix(docker/services): save the settings of the table for auto refresh

- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/create/createendpoint.html
> fix(endpoint): show correct windows agent deploy command

- app/portainer/views/stacks/create/createStackController.js
> feat(docker/stack): update content of code editor when switching custom template

- .github/workflows/rebase.yml
closes [CE-420](https://portainer.atlassian.net/browse/CE-420)
> Add automatic rebase to github

- api/http/handler/stacks/stack_start.go
fix #4839 
fix [CE-411]
[CE-411]: https://portainer.atlassian.net/browse/CE-411
> fix(stack): show correct error message

- api/http/handler/customtemplates/customtemplate_create.go
- app/portainer/services/api/customTemplate.js
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateViewController.js
> fix(customtemplate): create from file

- app/constants.js
- app/kubernetes/helpers/namespaceHelper.js
- app/kubernetes/views/configure/configureController.js
> fix(ingress): remove associated ingresses while removing ingress controller (#4722)

- app/docker/views/containers/edit/containerController.js
- app/docker/views/images/edit/imageController.js
- app/docker/views/services/edit/includes/environmentvariables.html
- app/docker/views/services/edit/serviceController.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/applications/edit/application.html
> feat(app): sort environment variables

- api/internal/snapshot/snapshot.go
fix #4327 [CE-257]
[CE-257]: https://portainer.atlassian.net/browse/CE-257
> fix(snapshot): update snapshot interval

- app/assets/css/app.css
- app/portainer/components/forms/group-form/groupForm.html
- app/portainer/components/tag-selector/tagSelector.html
- app/portainer/components/tag-selector/tagSelectorController.js
> feat(app/endpoint-group): replace the tag dropdown by isteven-multi-select

- app/kubernetes/converters/application.js
- app/kubernetes/converters/persistentVolumeClaim.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/views/applications/create/createApplicationController.js
> fix(application): Can't update application with persisted data, after the storage option is disabled on cluster

- api/bolt/datastore.go
- api/bolt/errors/errors.go
- api/bolt/version/version.go
- api/cmd/portainer/main.go
- api/portainer.go
> fix(bolt): Display error message if current database is for Portainer BE

- app/kubernetes/helpers/application/index.js
> feat(k8s/application): display all environment variables in edition

- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationData.html
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationDataController.js
- app/kubernetes/views/configurations/edit/configurationController.js
> feat(k8s/config): disable edit used config keys

- app/docker/components/container-capabilities/containerCapabilities.html
fix #4825 
fix [CE-404]
[CE-404]: https://portainer.atlassian.net/browse/CE-404
> fix(containers): fix layout in small screens

- app/docker/components/datatables/containers-datatable/containersDatatable.html
- app/docker/components/datatables/containers-datatable/containersDatatableController.js
> feat(app/containers): display IP

- app/kubernetes/components/yaml-inspector/yamlInspector.html
- app/kubernetes/components/yaml-inspector/yamlInspectorController.js
> feat(yaml-inspector): add button to expand/collapse yaml inspector (#4007)

- api/bolt/migrator/migrate_dbversion26.go
fix [CE-460]
[CE-460]: https://portainer.atlassian.net/browse/CE-460
> fix(db): skip resource control migration if stack doesn't exist CE-460

- app/docker/views/services/create/createServiceController.js
- app/docker/views/services/create/createservice.html
> feat(services): hide webhook interface

- app/kubernetes/views/applications/edit/application.html
> feat(k8s/application): add the ability to redeploy external application

- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationData.html
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationDataController.js
- app/kubernetes/helpers/formValidationHelper.js
> feat(k8s): better form validation for configuration keys (#4728)

- api/http/handler/endpoints/endpoint_status_inspect.go
- api/portainer.go
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationData.html
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationDataController.js
- app/kubernetes/helpers/formValidationHelper.js
- app/portainer/components/endpoint-list/endpoint-item/endpoint-item-controller.js
- app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
- app/portainer/views/home/homeController.js
fix #3842 [CE-253]
[CE-253]: https://portainer.atlassian.net/browse/CE-253
> feat(edge): show last check in date

- api/cmd/portainer/main.go
> feat(main): introduce description to fatal errors

- app/docker/views/volumes/create/createVolumeController.js
> feat(volume) change the way portainer creates NFS4 volumes (#4729)

- app/docker/views/services/edit/includes/mounts.html
- app/docker/views/services/edit/serviceController.js
fix #4651 
fix [CE-209]
[CE-209]: https://portainer.atlassian.net/browse/CE-209
> fix(service-details): clear volume source when changing type

- app/docker/helpers/containerHelper.js
- app/portainer/components/stack-duplication-form/stack-duplication-form-controller.js
- app/portainer/components/stack-duplication-form/stack-duplication-form.html
- app/portainer/components/stack-duplication-form/stack-duplication-form.js
- app/portainer/helpers/genericHelper.js
- app/portainer/helpers/stackHelper.js
- app/portainer/views/stacks/create/createStackController.js
- app/portainer/views/stacks/create/createstack.html
- app/portainer/views/stacks/edit/stack.html
- app/portainer/views/stacks/edit/stackController.js
> feat(stack): prevent stack duplication if name already used

- app/portainer/views/templates/templatesController.js
Close [CE-466](https://portainer.atlassian.net/browse/CE-466)
> fix(templates): App templates not loading with error in browser console

- api/docker/snapshot.go
- api/portainer.go
- app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
> feat(home): add node count to endpoint list.

- app/kubernetes/helpers/application/index.js
> fix(k8s): CE-471 variables from configuration showing on environment variables section on application edit screen

- .babelrc
- package.json
- yarn.lock
> chore(deps): install core-js@2

- api/http/handler/endpoints/endpoint_list.go
- app/portainer/views/home/homeController.js
fix [CE-479]
[CE-479]: https://portainer.atlassian.net/browse/CE-479
> fix(endpoints): use default edge checkin interval if n/a

- app/portainer/views/registries/registries.html
Close [CE-485](https://portainer.atlassian.net/browse/CE-485)
> feat(docker/registries): remove the registry usage information panel

- api/http/handler/registries/registry_create.go
- api/http/handler/registries/registry_update.go
- api/portainer.go
- app/docker/helpers/imageHelper.js
- app/portainer/components/forms/registry-form-quay/registry-form-quay.html
- app/portainer/models/registry.js
- app/portainer/services/api/registryService.js
- app/portainer/views/registries/create/createRegistryController.js
- app/portainer/views/registries/edit/registry.html
- app/portainer/views/registries/edit/registryController.js
close #4371 [CE-87]
[CE-87]: https://portainer.atlassian.net/browse/CE-87
> fix(registry): #4371 cannot push to quay.io registry

- api/http/handler/endpoints/endpoint_create.go
fix #4531 
fix [CE-217]
[CE-217]: https://portainer.atlassian.net/browse/CE-217
> fix(endpoints): create roles array in edge endpoint

- app/kubernetes/converters/service.js
> fix(service): change application owner label in createPayload

- app/kubernetes/node/converter.js
- app/kubernetes/node/formValues.js
- app/kubernetes/node/models.js
- app/kubernetes/node/service.js
- app/kubernetes/pod/converter.js
- app/kubernetes/pod/models/index.js
- app/kubernetes/pod/service.js
- app/kubernetes/rest/pod.js
- app/kubernetes/views/cluster/node/node.html
- app/kubernetes/views/cluster/node/nodeController.js
> Enable the ability to cordon/uncordon/drain nodes

- app/docker/views/configs/create/createConfigController.js
- app/docker/views/images/build/buildImageController.js
- app/edge/components/edge-job-form/edgeJobFormController.js
- app/edge/components/edge-job-form/index.js
- app/edge/components/edit-edge-stack-form/editEdgeStackFormController.js
- app/edge/components/edit-edge-stack-form/index.js
- app/edge/views/edge-jobs/createEdgeJobView/createEdgeJobView.html
- app/edge/views/edge-jobs/createEdgeJobView/createEdgeJobViewController.js
- app/edge/views/edge-jobs/edgeJob/edgeJob.html
- app/edge/views/edge-jobs/edgeJob/edgeJobController.js
- app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackViewController.js
- app/edge/views/edge-stacks/editEdgeStackView/editEdgeStackView.html
- app/edge/views/edge-stacks/editEdgeStackView/editEdgeStackViewController.js
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationData.js
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationDataController.js
- app/kubernetes/views/configurations/create/createConfiguration.html
- app/kubernetes/views/configurations/create/createConfigurationController.js
- app/kubernetes/views/configurations/edit/configuration.html
- app/kubernetes/views/configurations/edit/configurationController.js
- app/kubernetes/views/deploy/deployController.js
- app/portainer/services/modalService.js
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateViewController.js
- app/portainer/views/custom-templates/edit-custom-template-view/editCustomTemplateViewController.js
- app/portainer/views/stacks/create/createStackController.js
- app/portainer/views/stacks/edit/stackController.js
> feat(app): Prevent web editor related views from being accidentally closed

- app/kubernetes/views/deploy/deployController.js
fix #4625 
fix [CE-184]
[CE-184]: https://portainer.atlassian.net/browse/CE-184
> fix(kuberenetes/deploy): use default resource pool

- app/kubernetes/__module.js
fix #4550 [CE-143]
[CE-143]: https://portainer.atlassian.net/browse/CE-143
> fix(home): redirect home if edge endpoint is down

- app/docker/helpers/imageHelper.js
> fix(registry): #4371 fix broken GITLAB registry

- app/portainer/components/forms/por-switch-field/por-switch-field.css
> fix(container): fixed pull latest image toggle missing on service update and container recreate modal

- package.json
- yarn.lock
fix #4764 [CE-249]
[CE-249]: https://portainer.atlassian.net/browse/CE-249
> chore(deps): remove grunt-html2js and grunt-karma

- webpack/webpack.common.js
fix #4759 [CE-247]
[CE-247]: https://portainer.atlassian.net/browse/CE-247
> fix(build): ignore chardet missing sourcemaps

- app/portainer/views/init/admin/initAdmin.html
- app/portainer/views/settings/settings.html
> EE-379: add S3 stubs to CE

- api/http/handler/resourcecontrols/resourcecontrol_create.go
- api/http/proxy/factory/azure.go
- api/http/proxy/factory/azure/access_control.go
- api/http/proxy/factory/azure/containergroup.go
- api/http/proxy/factory/azure/containergroups.go
- api/http/proxy/factory/azure/transport.go
- api/http/proxy/factory/factory.go
- api/http/proxy/factory/responseutils/response.go
- api/internal/authorization/access_control.go
- api/portainer.go
- app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.html
- app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.js
- app/azure/models/container_group.js
- app/azure/views/containerinstances/container-instance-details/containerInstanceDetails.html
- app/azure/views/containerinstances/create/createContainerInstanceController.js
- app/azure/views/containerinstances/create/createcontainerinstance.html
- app/portainer/models/resourceControl/resourceControlTypes.js
- app/portainer/services/notifications.js
> feat(ACI): add UAC to ACI

- api/http/handler/resourcecontrols/resourcecontrol_create.go
- api/http/proxy/factory/azure.go
- api/http/proxy/factory/azure/access_control.go
- api/http/proxy/factory/azure/containergroup.go
- api/http/proxy/factory/azure/containergroups.go
- api/http/proxy/factory/azure/transport.go
- api/http/proxy/factory/factory.go
- api/http/proxy/factory/responseutils/response.go
- api/internal/authorization/access_control.go
- api/portainer.go
- app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.html
- app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.js
- app/azure/models/container_group.js
- app/azure/views/containerinstances/container-instance-details/containerInstanceDetails.html
- app/azure/views/containerinstances/create/createContainerInstanceController.js
- app/azure/views/containerinstances/create/createcontainerinstance.html
- app/portainer/models/resourceControl/resourceControlTypes.js
- app/portainer/services/notifications.js
close [CE-414](https://portainer.atlassian.net/browse/CE-414)
> feat(ACI): add UAC to ACI 

- app/kubernetes/filters/applicationFilters.js
- app/kubernetes/helpers/formValidationHelper.js
- app/kubernetes/ingress/converter.js
- app/kubernetes/ingress/models.js
- app/kubernetes/models/resource-pool/formValues.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/create/createResourcePoolController.js
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
> feat(k8s/ingress): create multiple ingress network per kubernetes namespace

- app/portainer/views/endpoints/edit/endpointController.js
> feat(edge) Update the version of agent to 2.4.0 in agent deploy command on the adding edge screen EE-596

- app/portainer/views/endpoints/edit/endpointController.js
Reverts portainer/portainer#5021
> Revert "feat(edge) Update the version of agent to 2.4.0 in agent deploy command on the adding edge screen EE-596"

- app/docker/components/imageRegistry/por-image-registry.html
fix [EE-646]
[EE-646]: https://portainer.atlassian.net/browse/EE-646
> fix(docker/images): show image selector advanced mode

- api/http/proxy/factory/azure/containergroup.go
> fix(ACI): ACI UAC breaks when redeploying container with same name asone already existing EE-645

- app/kubernetes/ingress/service.js
- app/kubernetes/services/resourcePoolService.js
- app/kubernetes/views/configure/configureController.js
fix [EE-651]
[EE-651]: https://portainer.atlassian.net/browse/EE-651
> fix(k8s/ingress): remove only selected ingress

- app/docker/components/imageRegistry/por-image-registry-rate-limits.controller.js
fix [CE-508]
[CE-508]: https://portainer.atlassian.net/browse/CE-508
> fix(docker): set image pulls as valid if failed fetching

- app/portainer/oauth/components/oauth-settings/oauth-settings.html
close [EE-607](https://portainer.atlassian.net/browse/EE-607)
> feat(oauth): add sso, hide internal auth teaser and logout options.

- app/docker/views/services/create/createServiceController.js
fix [EE-719]
[EE-719]: https://portainer.atlassian.net/browse/EE-719
> fix(docker/services): create a service webhook

- api/cmd/portainer/main.go
- api/exec/compose_wrapper.go
- api/exec/compose_wrapper_integration_test.go
cherry-picking commit a6b289c9.
> fix: docker-compose use custom config.json to access private images [CE-401]

- api/portainer.go
- app/docker/views/containers/create/createContainerController.js
fix [EE-705]
[EE-705]: https://portainer.atlassian.net/browse/EE-705
> fix(docker/containers): show sysctl control

- api/http/handler/settings/settings_public.go
- api/http/handler/settings/settings_public_test.go
> feat(publicSettings): public settings response modification for OAuth SSO EE-608

- app/portainer/views/logout/logoutController.js
close [EE-643](https://portainer.atlassian.net/browse/EE-643)
> feat(oauth): updated logout logic with logoutUrl 

- api/http/handler/auth/authenticate.go
- api/http/handler/auth/authenticate_oauth.go
- api/jwt/jwt.go
- api/jwt/jwt_test.go
- api/oauth/oauth.go
- api/portainer.go
> feat(oauth): update new token expiration for OAuth EE-612

- app/portainer/views/stacks/edit/stackController.js
fix [EE-771]
[EE-771]: https://portainer.atlassian.net/browse/EE-771
> fix(stacks): show containers only for standalone

- app/portainer/oauth/components/oauth-settings/oauth-settings.html
Teaser for Enterprise Edition automatic oauth team memberships feature.
> feat(oauth/team-memberships): EE oauth team memberships teaser

- app/portainer/oauth/components/oauth-settings/oauth-settings.html
Reverts portainer/portainer#5084
> Revert "feat(oauth/team-memberships): EE oauth team memberships teaser"

- app/edge/components/edit-edge-stack-form/editEdgeStackFormController.js
- app/kubernetes/components/kubernetes-configuration-data/kubernetesConfigurationDataController.js
- app/portainer/views/custom-templates/edit-custom-template-view/editCustomTemplateViewController.js
- app/portainer/views/stacks/edit/stackController.js
fix [EE-769]
fix #5077 
[EE-769]: https://portainer.atlassian.net/browse/EE-769
> fix(stacks): check for editor change before setting as dirty

- api/http/handler/endpointproxy/proxy_kubernetes.go
fix [EE-800]
[EE-800]: https://portainer.atlassian.net/browse/EE-800
> fix(k8s/proxy): proxy healthz request to k8s api EE-800

- app/portainer/components/forms/stack-from-template-form/stackFromTemplateForm.html
- app/portainer/views/templates/templatesController.js
close [EE-812](https://portainer.atlassian.net/browse/EE-812)
> fix(template): fixed disabled deploy button EE-812

- api/exec/kubernetes_deploy.go
- api/filesystem/filesystem.go
- api/http/handler/edgegroups/edgegroup_list.go
- api/http/handler/edgegroups/edgegroup_list_test.go
- api/http/handler/edgestacks/edgestack_create.go
- api/http/handler/edgestacks/edgestack_create_test.go
- api/http/handler/edgestacks/edgestack_delete.go
- api/http/handler/edgestacks/edgestack_update.go
- api/http/handler/edgestacks/endpoints.go
- api/http/handler/edgestacks/endpoints_test.go
- api/http/handler/edgestacks/handler.go
- api/http/handler/endpointedge/endpoint_edgestack_inspect.go
- api/http/server.go
- api/internal/endpoint/endpoint.go
- api/internal/endpoint/endpoint_test.go
- api/internal/testhelpers/datastore.go
- api/portainer.go
- app/edge/components/edge-groups-selector/edgeGroupsSelector.html
- app/edge/components/edge-groups-selector/index.js
- app/edge/components/edit-edge-stack-form/editEdgeStackForm.html
- app/edge/components/edit-edge-stack-form/editEdgeStackFormController.js
- app/edge/components/group-form/groupFormController.js
- app/edge/services/edge-stack.js
- app/edge/views/edge-groups/editEdgeGroupView/editEdgeGroupViewController.js
- app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackView.html
- app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackViewController.js
- app/edge/views/edge-stacks/editEdgeStackView/editEdgeStackViewController.js
- app/portainer/components/associated-endpoints-selector/associatedEndpointsSelectorController.js
- app/portainer/services/notifications.js
[EE-594]
[EE-594]: https://portainer.atlassian.net/browse/EE-594
> feat(edge): convert compose stacks to kube stacks

- app/portainer/views/custom-templates/custom-templates-view/customTemplatesViewController.js
- app/portainer/views/templates/templatesController.js
close [EE-820](https://portainer.atlassian.net/browse/EE-820)
> fix(templates): checking windows endpoint and template properties.

- app/docker/views/images/build/buildImageController.js
> fix(image) Confirmation modal on builder output view EE-816

- api/bolt/errors/errors.go
Close [EE-575](https://portainer.atlassian.net/browse/EE-575)
> fix(portainer): Fix the type in the downgrade error message

- api/git/azure_integration_test.go
- api/git/git.go
- api/git/git_integration_test.go
- api/git/git_test.go
- api/http/handler/stacks/handler.go
- api/http/handler/stacks/stack_update_git.go
- api/internal/testhelpers/git_service.go
[EE-667]
[EE-667]: https://portainer.atlassian.net/browse/EE-667
> feat(stacks): redeploy git stack api

- api/http/proxy/factory/kubernetes/agent_transport.go
- api/http/proxy/factory/kubernetes/edge_transport.go
- api/http/proxy/factory/kubernetes/transport.go
close [CE-525]
[CE-525]: https://portainer.atlassian.net/browse/CE-525
> fix(kube): fetch dockerhub pull limits

- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/kubernetes/components/datatables/applications-stacks-datatable/applicationsStacksDatatable.html
- app/kubernetes/components/datatables/configurations-datatable/configurationsDatatable.html
- app/kubernetes/components/datatables/node-applications-datatable/nodeApplicationsDatatable.html
- app/kubernetes/components/datatables/resource-pools-datatable/resourcePoolsDatatable.html
- app/kubernetes/components/datatables/volumes-datatable/volumesDatatable.html
- app/kubernetes/components/kubernetes-sidebar-content/kubernetesSidebarContent.html
- app/kubernetes/models/application/formValues.js
- app/kubernetes/views/applications/console/console.html
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/logs/logs.html
- app/kubernetes/views/applications/stats/stats.html
- app/kubernetes/views/configurations/create/createConfiguration.html
- app/kubernetes/views/configurations/edit/configuration.html
- app/kubernetes/views/dashboard/dashboard.html
- app/kubernetes/views/deploy/deploy.html
- app/kubernetes/views/deploy/deployController.js
- app/kubernetes/views/resource-pools/access/resourcePoolAccess.html
- app/kubernetes/views/resource-pools/access/resourcePoolAccessController.js
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/create/createResourcePoolController.js
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
- app/kubernetes/views/resource-pools/resourcePools.html
- app/kubernetes/views/resource-pools/resourcePoolsController.js
- app/kubernetes/views/stacks/logs/logs.html
- app/kubernetes/views/volumes/edit/volume.html
- app/kubernetes/views/volumes/volumesController.js
fix [EE-445]
related to https://github.com/portainer/portainer-ee/pull/333
[EE-445]: https://portainer.atlassian.net/browse/EE-445
> feat(k8s): replace resourcepool with namespace EE-445

- gruntfile.js
closes #4667 
[CE-211]
[CE-211]: https://portainer.atlassian.net/browse/CE-211
> chore(dev-build): custom portainer data folder

- api/cmd/portainer/main.go
- api/http/handler/endpoints/endpoint_create.go
fix [EE-633]
[EE-633]: https://portainer.atlassian.net/browse/EE-633
> fix(docker/settings): fetch correct value for allow sysctl

- app/kubernetes/models/application/formValues.js
- app/kubernetes/views/applications/create/createApplication.html
Close [EE-672](https://portainer.atlassian.net/browse/EE-672)
> feat(k8s/applications): reorder placement policies and select mandatory by default

- api/http/handler/endpoints/endpoint_registries_list.go
- api/http/proxy/factory/docker/transport.go
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
- app/portainer/components/datatables/registries-datatable/registriesDatatable.html
Close [EE-869](https://portainer.atlassian.net/browse/EE-869)
> fix(app): pre review fixes

- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.html
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/kubernetes/components/datatables/integrated-applications-datatable/integratedApplicationsDatatable.html
- app/kubernetes/components/datatables/node-applications-datatable/nodeApplicationsDatatable.html
- app/kubernetes/components/datatables/resource-pool-applications-datatable/resourcePoolApplicationsDatatable.html
Close [EE-352](https://portainer.atlassian.net/browse/EE-352)
> feat(k8s): truncate image name in tables

- api/cmd/portainer/main.go
- api/exec/kubernetes_deploy.go
- api/http/handler/stacks/create_kubernetes_stack.go
- api/internal/endpoint/endpoint.go
- api/portainer.go
> Fix(kube) advanced deployment CE-83 

- app/kubernetes/models/deploy.js
- app/kubernetes/views/deploy/deploy.html
- app/kubernetes/views/deploy/deployController.js
- app/portainer/services/api/stackService.js
close [EE-640](https://portainer.atlassian.net/browse/EE-640)
> feat(stack): UI updates in git repo deployment method for k8s EE-640.

- app/azure/models/container_group.js
- app/azure/views/containerinstances/container-instance-details/containerInstanceDetails.html
> fix(aci): fixed aci with persistence or networking issue.

- app/kubernetes/views/configure/configureController.js
> fix(frontend): When a docker endpoint is selected, configuring a newly added k8s agent fails EE-821

- api/http/handler/stacks/handler.go
- api/http/handler/stacks/stack_associate.go
- api/http/handler/stacks/stack_delete.go
- api/http/handler/stacks/stack_file.go
- api/http/handler/stacks/stack_inspect.go
- api/http/handler/stacks/stack_list.go
- app/docker/__module.js
- app/portainer/components/accessControlForm/por-access-control-form.js
- app/portainer/components/accessControlForm/porAccessControlForm.html
- app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
- app/portainer/components/datatables/stacks-datatable/stacksDatatableController.js
- app/portainer/models/stack.js
- app/portainer/rest/stack.js
- app/portainer/services/api/stackService.js
- app/portainer/views/stacks/edit/stack.html
- app/portainer/views/stacks/edit/stackController.js
- app/portainer/views/stacks/stacksController.js
> Feat(stacks): orphaned stacks #4397

- app/portainer/views/endpoints/edit/endpointController.js
fix local k8s endpoint url not able to saved
> fix(app):fix local k8s endpoint not saved EE-825

- app/docker/rest/response/handlers.js
- app/docker/views/images/build/buildImageController.js
- app/docker/views/images/import/importImageController.js
Fixes #4655
[CE-210]
[CE-210]: https://portainer.atlassian.net/browse/CE-210
> fix(app): parse response with null body

- app/kubernetes/views/applications/create/createApplication.html
Close [EE-418](https://portainer.atlassian.net/browse/EE-418)
> feat(application): Invalid environment variable form validation when creating an application EE-418

- app/constants.js
- app/kubernetes/__module.js
- app/kubernetes/components/datatables/nodes-datatable/nodesDatatable.html
- app/kubernetes/components/datatables/nodes-datatable/nodesDatatable.js
- app/kubernetes/metrics/metrics.js
- app/kubernetes/metrics/rest.js
- app/kubernetes/views/cluster/cluster.html
- app/kubernetes/views/cluster/clusterController.js
- app/kubernetes/views/cluster/node/stats/stats.html
- app/kubernetes/views/cluster/node/stats/stats.js
- app/kubernetes/views/cluster/node/stats/statsController.js
close #4612
This PR is based on branch feat/GH/4391-kube-realtime-metrics. Merge this PR only after #4391 being merged.
> Feat 4612 real time metrics for kube nodes

- api/http/handler/endpoints/endpoint_create.go
> fix(docs): fix swagger param name for endpoint creation EE-948

- app/docker/models/container.js
- app/docker/views/containers/stats/containerStatsController.js
- app/docker/views/containers/stats/containerstats.html
- app/portainer/services/chartService.js
Potentially closes #4260
Related to #4242
This PR is a minimal improvement over #4303 
- #4303 is an existing PR from @DarkAEther
> feat(container-stats): introduce container block I/O stats

- app/kubernetes/views/applications/create/createApplicationController.js
> fix(k8s) Adding a Kube app does not allow Global to be set after removing persisted folder EE-563

- app/docker/views/registries/access/registryAccess.html
- app/docker/views/registries/access/registryAccessController.js
- app/portainer/__module.js
- app/portainer/components/accessManagement/index.js
- app/portainer/components/accessManagement/por-access-management-users-selector/index.js
- app/portainer/components/accessManagement/por-access-management-users-selector/por-access-management-users-selector.html
- app/portainer/components/accessManagement/por-access-management.js
- app/portainer/components/accessManagement/porAccessManagement.html
- app/portainer/components/accessManagement/porAccessManagementController.js
- app/portainer/components/index.js
[EE-953]
- refactor users-selector to a different component
- move filtering of available users to the parent component
- add filtering by group access
[EE-953]: https://portainer.atlassian.net/browse/EE-953
> feat(access-managment): filter users for registry

- api/cmd/portainer/main.go
- api/http/handler/endpointgroups/endpointgroup_update.go
- api/http/handler/endpointgroups/handler.go
- api/http/handler/endpoints/endpoint_update.go
- api/http/handler/endpoints/handler.go
- api/http/server.go
- api/internal/authorization/authorizations.go
- api/internal/authorization/endpint_role_with_override.go
- api/kubernetes/cli/access.go
- api/portainer.go
> fix(k8s) cleaning up namespace access policies when removing users orteams from endpoint or endpoint group EE-718

- api/bolt/migrator/migrate_dbversion30.go
- api/bolt/migrator/migrator.go
- api/cmd/portainer/main.go
- api/http/handler/endpoints/endpoint_registries_inspect.go
- api/http/handler/endpoints/endpoint_registries_list.go
- api/http/handler/endpoints/endpoint_registry_access.go
- api/http/handler/endpoints/handler.go
- api/http/handler/registries/registry_create.go
- api/http/handler/registries/registry_inspect.go
- api/http/proxy/factory/kubernetes/agent_transport.go
- api/http/proxy/factory/kubernetes/edge_transport.go
- api/http/proxy/factory/kubernetes/namespaces.go
- api/http/proxy/factory/kubernetes/secrets.go
- api/http/proxy/factory/kubernetes/transport.go
- api/http/security/authorization.go
- api/internal/endpoint/endpoint.go
- api/kubernetes/cli/client.go
- api/portainer.go
- app/docker/components/dockerSidebarContent/dockerSidebarContent.html
- app/docker/views/containers/create/createContainerController.js
- app/docker/views/containers/edit/container.html
- app/docker/views/images/edit/imageController.js
- app/docker/views/registries/access/registryAccessController.js
- app/kubernetes/registries/kube-registry-access-view/kube-registry-access-view.controller.js
- app/kubernetes/registries/kube-registry-access-view/kube-registry-access-view.html
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/portainer/rest/endpoint.js
- app/portainer/services/api/endpointService.js
this PR minimizes code changes between CE to EE
> refactor(registries): sync code with CE

- app/azure/views/containerinstances/create/createContainerInstanceController.js
> fix(ACI): At least one team or user should be specified when creating a restricted container in Azure ACI EE-578

- app/portainer/components/intervalFormat.js
- app/portainer/helpers/webhookHelper.js
- app/portainer/services/api/stackService.js
- app/portainer/views/stacks/create/createStackController.js
- app/portainer/views/stacks/create/createstack.html
- package.json
- yarn.lock
close [EE-780](https://portainer.atlassian.net/browse/EE-780)
> feat(stack): updated Add Stack view EE-780.

- api/http/handler/stacks/stack_update_git.go
> fix(stack) Unable to update and redeploy a stack created from a git repository if it has failed once EE-1012

- api/http/handler/customtemplates/customtemplate_create.go
- api/http/handler/edgestacks/edgestack_create.go
- api/http/handler/stacks/create_kubernetes_stack.go
- api/http/handler/stacks/stack_create.go
- api/http/handler/stacks/stack_update_git.go
> fix(stack) ignore username and password when authentication is disabled EE-161

- app/portainer/components/forms/git-form/git-form-auth-fieldset/git-form-auth-fieldset.controller.js
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateView.html
fix [EE-1025]
[EE-1025]: https://portainer.atlassian.net/browse/EE-1025
> fix(git-form): show git form and clear auth values

- api/kubernetes/cli/pod.go
- app/kubernetes/components/kubectl-shell/kubectlShell.css
- app/kubernetes/components/kubectl-shell/kubectlShell.html
- app/kubernetes/components/kubectl-shell/kubectlShell.js
- app/kubernetes/components/kubectl-shell/kubectlShellController.js
- app/kubernetes/components/view-header/viewHeader.html
close [EE-927](https://portainer.atlassian.net/browse/EE-927).
> feat(app): kubectl shell ui backport EE-927

- api/http/handler/endpoints/endpoint_delete.go
- api/portainer.go
Close [EE-1027](https://portainer.atlassian.net/browse/EE-1027)
> fix(api/endpoints): update registry access policies on endpoint deletion

- api/http/handler/auth/authenticate.go
- api/http/handler/auth/authenticate_oauth.go
- api/oauth/oauth.go
- api/portainer.go
> fix(OAuth): remove OAuth expiry time copy logic server EE-1046

- app/kubernetes/views/resource-pools/create/createResourcePoolController.js
> fix(app):Set resource assignment default to off EE-1043

- api/http/handler/teams/team_delete.go
- app/portainer/oauth/components/oauth-settings/oauth-settings.html
Teaser for Enterprise Edition automatic oauth team memberships feature.
> feat(oauth/team-memberships): oauth team memberships teaser EE-341

- app/portainer/oauth/components/oauth-settings/oauth-settings-controller.js
- app/portainer/oauth/components/oauth-settings/oauth-settings.html
- app/portainer/views/settings/authentication/settingsAuthentication.html
- app/portainer/views/settings/authentication/settingsAuthenticationController.js
close[ EE-971](https://portainer.atlassian.net/browse/EE-971)
> feat(settings): add admin mapping section EE-971

- app/kubernetes/converters/application.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
close [EE-1072](https://portainer.atlassian.net/browse/EE-1072)
> fix(ingress): fixed hostname field when having multiple ingresses EE-1072

- app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode-item/environment-variables-simple-mode-item.controller.js
- app/portainer/components/environment-variables-panel/environment-variables-simple-mode/environment-variables-simple-mode-item/environment-variables-simple-mode-item.html
- app/portainer/helpers/env-vars.js
> fix EE-1078 Too strict form validation for docker environment variables

- app/kubernetes/ingress/converter.js
> fix(ingress): EE-1049 Ingress config is lost when deleting an application deployed with ingress

- app/edge/views/edge-stacks/createEdgeStackView/createEdgeStackView.html
[EE-392]
[EE-392]: https://portainer.atlassian.net/browse/EE-392
> feat(edgestack): support standalone stacks

- app/kubernetes/helpers/application/index.js
> EE-1110 Ingress routes and their mapping to a application name are not deleted when the application is deleted

- api/http/proxy/factory/docker/transport.go
- api/http/proxy/factory/docker/volumes.go
[EE-553]
[EE-553]: https://portainer.atlassian.net/browse/EE-553
> fix(volumes): fetch resource by docker name

- api/bolt/init.go
- api/http/handler/settings/settings_update.go
- api/portainer.go
> feat(ldap): update LDAP settings for auto admin population EE-992

- app/kubernetes/components/datatables/resource-pools-datatable/resourcePoolsDatatable.js
- app/kubernetes/components/datatables/resource-pools-datatable/resourcePoolsDatatableController.js
- app/kubernetes/views/configure/configure.html
- app/kubernetes/views/configure/configureController.js
- app/kubernetes/views/resource-pools/resourcePools.html
- app/kubernetes/views/resource-pools/resourcePools.js
close [EE-1116](https://portainer.atlassian.net/browse/EE-1116)
> feat(k8s): add restrict default namespace option EE-1116

- api/bolt/migrator/migrate_dbversion32.go
- api/bolt/migrator/migrate_dbversion32_test.go
- api/bolt/migrator/migrator.go
- api/http/handler/auth/authenticate.go
- api/http/handler/ldap/handler.go
- api/http/handler/ldap/ldap_check.go
- api/http/handler/ldap/ldap_groups.go
- api/http/handler/ldap/ldap_test_login.go
- api/http/server.go
- api/ldap/ldap.go
- api/portainer.go
> feat(ldap): auto admin group mapping EE-994

- api/http/handler/stacks/stack_update.go
- app/portainer/views/stacks/edit/stack.html
[EE-554]
[EE-554]: https://portainer.atlassian.net/browse/EE-554
> feat(stacks): update stopped stack

- app/kubernetes/models/application/formValues.js
[EE-1137]
[EE-1137]: https://portainer.atlassian.net/browse/EE-1137
> fix(kube/app): show resource allocation

- app/kubernetes/ingress/converter.js
close [EE-1176](https://portainer.atlassian.net/browse/EE-1176)
> fix(k8s): fixed generating kube auction summary issue

- api/http/handler/endpoints/endpoint_update.go
- api/http/proxy/factory/kubernetes.go
- api/http/proxy/factory/kubernetes/token.go
- api/http/proxy/factory/kubernetes/transport.go
- api/kubernetes/cli/access.go
- api/kubernetes/cli/service_account.go
- api/portainer.go
- package.json
Closes [EE-1117](https://portainer.atlassian.net/browse/EE-1117).
> feat(k8s): Update K8s SetupUserServiceAccount (#1117)

- app/kubernetes/views/cluster/node/nodeController.js
fix [EE-583]
[EE-583]: https://portainer.atlassian.net/browse/EE-583
> fix(kube/nodes): show node events

- app/portainer/services/chartService.js
> fix(frontend): Fix charts scale issue with browser zoom EE-1142

- app/portainer/services/chartService.js
> fix(docker): Charts scale issue with browser zoom fixed EE-1142

- app/portainer/views/stacks/create/createStackController.js
- app/portainer/views/stacks/edit/stackController.js
[EE-678]
[EE-678]: https://portainer.atlassian.net/browse/EE-678
> fix(stacks): prevent stack creation when container_name already exists

- api/http/handler/endpoints/endpoint_list.go
- app/edge/components/group-form/groupFormController.js
- app/edge/views/edge-stacks/editEdgeStackView/editEdgeStackViewController.js
- app/portainer/components/associated-endpoints-selector/associatedEndpointsSelectorController.js
- app/portainer/services/api/endpointService.js
[EE-691]
[EE-691]: https://portainer.atlassian.net/browse/EE-691
> feat(endpoints): filter endpoints by a list of types

- api/git/types/types.go
- api/http/handler/stacks/stack_delete.go
- api/http/handler/stacks/stack_start.go
- api/http/handler/stacks/stack_stop.go
- api/http/handler/stacks/stack_update_git.go
> fix(swagger): add swagger annotation for pull and redeploy stack [release] EE-1131

- api/git/types/types.go
- api/http/handler/stacks/stack_delete.go
- api/http/handler/stacks/stack_start.go
- api/http/handler/stacks/stack_stop.go
- api/http/handler/stacks/stack_update.go
- api/http/handler/stacks/stack_update_git.go
> fix(swagger): add swagger annotation for pull and redeploy stack [develop] EE-1131

- app/portainer/components/stack-duplication-form/stack-duplication-form-controller.js
- app/portainer/components/stack-duplication-form/stack-duplication-form.html
> fix(stack): show warning if endpoint is selected

- app/docker/helpers/imageHelper.js
[EE-956]
[EE-956]: https://portainer.atlassian.net/browse/EE-956
> fix(images): ensure latest image

- api/exec/compose_stack.go
- api/exec/swarm_stack.go
- api/http/handler/stacks/create_swarm_stack.go
- api/portainer.go
> fix(app): fix create stack with capital letters or space issue EE-908

- app/docker/components/datatables/containers-datatable/containersDatatable.html
- app/docker/components/datatables/containers-datatable/containersDatatableController.js
- app/docker/filters/filters.js
> fix(app): Fix ports displayed twice when using docker EE-706

- app/docker/views/images/imagesController.js
> fix(docker):Fix image pulled errorDetails not showing EE-936

- app/portainer/views/stacks/edit/stack.html
closes #3441
related to #5098
[EE-828]
[EE-828]: https://portainer.atlassian.net/browse/EE-828
> feat(stacks): allow standalone to edit env vars

- api/cmd/portainer/main.go
- api/exec/kubernetes_deploy.go
- api/http/handler/stacks/create_kubernetes_stack.go
- api/http/handler/websocket/handler.go
- api/http/handler/websocket/pod.go
- api/http/handler/websocket/proxy.go
- api/http/handler/websocket/types.go
- api/http/proxy/factory/kubernetes/token.go
- api/http/proxy/factory/kubernetes/token_cache.go
- api/http/proxy/factory/kubernetes/transport.go
- api/http/server.go
- api/kubernetes/cli/exec.go
- api/portainer.go
> fix(advance deploy): EE-1141 A standard user can escalate to cluster administrator privileges on Kubernetes

- api/http/handler/endpoints/endpoint_dockerhub_status.go
- app/docker/components/imageRegistry/por-image-registry-rate-limits.controller.js
Fixes [EE-1035](https://portainer.atlassian.net/browse/EE-1035)
> Fix(handler): Quota exceeded with github pro account EE-1035

- api/http/handler/endpoints/endpoint_association_delete.go
- api/http/handler/endpoints/handler.go
- app/portainer/rest/endpoint.js
- app/portainer/services/api/endpointService.js
- app/portainer/services/modalService.js
- app/portainer/views/endpoints/edit/endpoint.html
- app/portainer/views/endpoints/edit/endpointController.js
> feat(edge): Provide a way to re-associate an Edge endpoint to a new Edge agent EE-424

- app/portainer/views/stacks/create/createStackController.js
close [EE-1302](https://portainer.atlassian.net/browse/EE-1302)
> fix(stack): authentication toggle off by default

- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.controller.js
- app/portainer/views/stacks/create/createStackController.js
close [EE-1306](https://portainer.atlassian.net/browse/EE-1306)
> fix(stack): auto update interval default to 5m

- api/http/handler/auth/authenticate.go
- api/http/handler/auth/authenticate_oauth.go
- api/oauth/oauth.go
- api/portainer.go
> fix(oauth): remove expiry time copy logic EE-1085

- api/http/proxy/factory/utils/json.go
Fix [EE-731](https://portainer.atlassian.net/browse/EE-731)
> fix(proxy): use media-type not content-type for unmarshalling logic EE-731

- app/portainer/components/forms/registry-form-proget/registry-form-proget.html
[EE-1059]
[EE-1059]: https://portainer.atlassian.net/browse/EE-1059
> feat(registries): add proget notice

- .github/workflows/label-conflcts.yaml
[DTD-66]
[DTD-66]: https://portainer.atlassian.net/browse/DTD-66
> chore(github): add label conflicts workflow

- app/kubernetes/views/configure/configure.html
Close [EE-1178]
[EE-1178]: https://portainer.atlassian.net/browse/EE-1178
> feat(app/configure): reword metrics features enabling switch and information

- api/portainer.go
fix(api): increment api version to latest [EE-1402]
[EE-1402]: https://portainer.atlassian.net/browse/EE-1402
> fix(api): increment api version to latest [EE-1402]

- app/portainer/views/init/admin/initAdminController.js
[EE-1354]
[EE-1354]: https://portainer.atlassian.net/browse/EE-1354
> feat(backup): reload if restore fails

- api/exec/compose_stack.go
- api/exec/compose_stack_test.go
- api/go.mod
- api/go.sum
using stack's dir as a working dir to let compose picking default .env file
> fix(stacks): deploy a stack from stack's directory [EE-1310]

- app/docker/views/containers/edit/container.html
- app/docker/views/containers/edit/containerController.js
- app/docker/views/images/edit/image.html
- app/docker/views/images/edit/imageController.js
[EE-1262]
[EE-1262]: https://portainer.atlassian.net/browse/EE-1262
> fix(docker): pass endpoint to image component

- app/portainer/components/forms/git-form/git-form-auth-fieldset/git-form-auth-fieldset.html
- app/portainer/components/forms/git-form/git-form-auth-fieldset/index.js
- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.controller.js
- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.html
close [EE-1425](https://portainer.atlassian.net/browse/EE-1425)
> feat(stack): enable save button when password exists

- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePool.html
Close [EE-1053](https://portainer.atlassian.net/browse/EE-1053)
> refactor(k8s/namespaces): rename Storages sections to Storage

- api/http/handler/endpoints/endpoint_association_delete.go
- api/http/handler/endpoints/handler.go
- api/http/server.go
> feat(edge): provide a way to re-associate an Edge endpoint with a new Edge key EE-947 

- app/portainer/components/code-editor/codeEditorController.js
- app/portainer/components/custom-template-selector/custom-template-selector.controller.js
- app/portainer/components/custom-template-selector/custom-template-selector.html
- app/portainer/components/custom-template-selector/index.js
- app/portainer/components/form-components/index.js
- app/portainer/components/form-components/web-editor-form/index.js
- app/portainer/components/form-components/web-editor-form/web-editor-form.controller.js
- app/portainer/components/form-components/web-editor-form/web-editor-form.html
- app/portainer/components/forms/git-form/git-form-additional-files-panel/git-form-additional-file-item/git-form-additional-file-item.controller.js
- app/portainer/components/index.js
- app/portainer/views/stacks/create/createStackController.js
- app/portainer/views/stacks/create/createstack.html
[EE-1418]
[EE-1418]: https://portainer.atlassian.net/browse/EE-1418
> refactor(stacks): move custom templates selector to component

- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.controller.js
close [EE-1334](https://portainer.atlassian.net/browse/EE-1334)
> fix(stack): show success notification when redeploy succeeds

- api/http/handler/endpointproxy/handler.go
- api/http/handler/endpointproxy/proxy_docker.go
- api/http/handler/endpointproxy/proxy_kubernetes.go
- api/http/handler/handler.go
- app/agent/rest/dockerhub.js
close [EE-1384](https://portainer.atlassian.net/browse/EE-1384).
> feat(dockerhub): new endpoint prefix for proxying requests to agent EE-1384

- app/portainer/views/registries/registries.html
Close [EE-951](https://portainer.atlassian.net/browse/EE-951)
> feat(app/registries): add indicator about registries accesses relocation

- api/http/handler/kubernetes/kubernetes_config.go
Closes [EE-1485](https://portainer.atlassian.net/browse/EE-1485), [EE-1487](https://portainer.atlassian.net/browse/EE-1487).
> feat(kubernetes/kubeconfig): remove request tls check EE-1485 EE-1487

- app/kubernetes/components/kubectl-shell/kubectl-shell.controller.js
- app/kubernetes/components/kubectl-shell/kubectl-shell.css
- app/portainer/services/terminal-window.js
> fix(kubectl): fix kubectl terminal not showing bottom line in some browser EE-1414

- api/http/handler/kubernetes/kubernetes_config.go
- app/kubernetes/services/kubeconfigService.js
blocked by https://github.com/portainer/portainer-ee/pull/451
[EE-1159]
[EE-1159]: https://portainer.atlassian.net/browse/EE-1159
> feat(kubernetes): fetch config file with endpoint name

- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/portainer/components/forms/kubernetes-app-git-form/kubernetes-app-git-form.html
- app/portainer/components/forms/kubernetes-app-git-form/kubernetes-app-git-form.js
close [EE-1502](https://portainer.atlassian.net/browse/EE-1502)
> fix(stack): fixed issue auth detail not remembered EE-1502

- api/http/handler/stacks/create_kubernetes_stack.go
- app/kubernetes/converters/application.js
- app/kubernetes/models/application/models/constants.js
- app/kubernetes/models/application/models/index.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/applications/edit/application.html
- app/kubernetes/views/applications/edit/applicationController.js
- app/portainer/components/form-components/web-editor-form/index.js
- app/portainer/components/forms/git-form/git-form-auth-fieldset/index.js
- app/portainer/components/forms/git-form/git-form-info-panel/git-form-info-panel.html
- app/portainer/components/forms/git-form/git-form-info-panel/index.js
- app/portainer/components/forms/git-form/index.js
- app/portainer/components/forms/kubernetes-app-git-form/kubernetes-app-git-form.controller.js
- app/portainer/components/forms/kubernetes-app-git-form/kubernetes-app-git-form.html
- app/portainer/components/forms/kubernetes-app-git-form/kubernetes-app-git-form.js
- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.html
- app/portainer/services/api/stackService.js
- app/portainer/views/stacks/create/createStackController.js
close [EE-1199](https://portainer.atlassian.net/browse/EE-1199)
> feat(stack): front end backport changes to CE EE-1199

- app/kubernetes/ingress/converter.js
- app/kubernetes/ingress/payloads.js
- app/kubernetes/ingress/rest.js
Close [EE-1143]
[EE-1143]: https://portainer.atlassian.net/browse/EE-1143
> feat(app/k8s): update ingress scheme from v1beta1 to v1

- api/exec/compose_stack.go
- api/exec/compose_stack_test.go
Reverts portainer/portainer#5506
> Revert "fix(stacks): allow root based compose file paths [EE-1473]"

- build/linux/dev-toolkit/run.sh
- build/linux/dev-toolkit/toolkit.Dockerfile
- gruntfile.js
Closes [EE-1547](https://portainer.atlassian.net/browse/EE-1547)
See https://github.com/portainer/portainer/pull/4887 for the instructions on how to use this.
> chore(build-system): update dev-toolkit (#4887)

- api/http/handler/stacks/update_kubernetes_stack.go
> fix(k8s): file content overridden when deployment failed with compose format EE-1548

- api/bolt/init.go
- api/bolt/migrator/migrate_dbversion31.go
- api/cmd/portainer/main.go
- api/http/handler/kubernetes/handler.go
- api/http/handler/kubernetes/kubernetes_config.go
- api/http/handler/settings/settings_update.go
- api/http/server.go
- api/internal/testhelpers/datastore.go
- api/jwt/jwt.go
- api/jwt/jwt_kubeconfig.go
- api/jwt/jwt_kubeconfig_test.go
- api/jwt/jwt_test.go
- api/portainer.go
- app/portainer/models/settings.js
- app/portainer/views/settings/settings.html
- app/portainer/views/settings/settingsController.js
> feat(kubeconfig): Introduce the ability to change the expiry of a kubeconfig EE-1153

- api/kubernetes/cli/role.go
- api/kubernetes/cli/service_account.go
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
close [EE-1304](https://portainer.atlassian.net/browse/EE-1304).
> feat(rbac) remove list ingresses permissions EE-1304

- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.controller.js
- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.html
close [EE-1291](https://portainer.atlassian.net/browse/EE-1291) [EE-1292](https://portainer.atlassian.net/browse/EE-1291)
> fix(stack): git form validation improvement. EE-1291 EE-1292

- api/go.mod
- api/go.sum
- api/http/handler/settings/settings_update.go
- api/http/handler/users/user_helm_repos.go
Closes [EE-1554](https://portainer.atlassian.net/browse/EE-1554)
> feat(helm) use libhelm url validator and improved path assembly EE-1554

- api/http/handler/stacks/update_kubernetes_stack.go
> fix(k8s): file content overridden when deployment failed with compose format EE-1556

- api/http/handler/users/handler.go
- api/http/handler/users/user_helm_repos.go
- app/kubernetes/components/helm/helm-templates/helm-templates.controller.js
- app/portainer/rest/user.js
Fixes [EE-1562](https://portainer.atlassian.net/browse/EE-1562)
> feat(helm/userrepos) fix getting global repo for ordinary users EE-1562

- api/http/handler/users/user_helm_repos.go
- user cannot add existing repo if suffix is '/'
> feat(helm/repo-add): user added helm repo validations

- api/http/handler/helm/helm_delete.go
- api/http/handler/helm/helm_install.go
- api/http/handler/helm/helm_list.go
- api/http/handler/helm/helm_repo_search.go
- api/http/handler/helm/helm_show.go
- api/http/handler/users/user_helm_repos.go
Fix docs in [EE-1278](https://portainer.atlassian.net/browse/EE-1278)
> feat(helm/docs) fix broken swagger docs EE-1278

- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
Close [EE-1505]
[EE-1505]: https://portainer.atlassian.net/browse/EE-1505
> fix(app/namespace): allow default-ns registries edit from namespace page

- api/http/handler/stacks/create_kubernetes_stack.go
> fix(k8s): Git authentication info not persisted in DB EE-1574

- app/portainer/services/api/endpointService.js
- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/edit/endpointController.js
close [EE-1454](https://portainer.atlassian.net/browse/EE-1454)
> fix(k8s): add tag ids to request payload for creating local k8s endpoint. EE-1454

- app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.html
Closes [EE-1569](https://portainer.atlassian.net/browse/EE-1569).
> feat(helm): frontend helm repo url validation for user added repo EE-1569

- api/go.mod
- api/go.sum
- app/kubernetes/helm/rest.js
- app/kubernetes/helm/service.js
- app/kubernetes/helpers/application/index.js
Closes [EE-1581](https://portainer.atlassian.net/browse/EE-1581).
> fix(helm): helm app deletion fix EE-1581

- app/portainer/helpers/env-vars.js
Close [EE-1424]
Close #5395 
[EE-1424]: https://portainer.atlassian.net/browse/EE-1424
> fix(app/env-vars): make equal sign usable in env vars

- app/kubernetes/registries/kube-registry-access-view/kube-registry-access-view.controller.js
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
- app/portainer/views/registries/registriesController.js
Close [EE-1096]
[EE-1096]: https://portainer.atlassian.net/browse/EE-1096
> feat(app/registries): add warning modal on registries deletion

- app/kubernetes/views/resource-pools/create/createResourcePool.html
Close [EE-1564]
[EE-1564]: https://portainer.atlassian.net/browse/EE-1564
> fix(k8s/namespace): missing header in namespace creation view

- app/kubernetes/converters/deployment.js
close [EE-1553](https://portainer.atlassian.net/browse/EE-1553)
> fix(k8s): fixed apply a note to k8s application

- api/http/proxy/factory/kubernetes/secrets.go
> fix(k8s): non-admin users cannot deploy charts containing secrets EE-1591 

- api/exec/kubernetes_deploy.go
- api/http/handler/stacks/create_kubernetes_stack.go
- api/http/handler/stacks/stack_update_git_redeploy.go
- api/http/handler/stacks/update_kubernetes_stack.go
- api/portainer.go
- api/stacks/deployer.go
> feat(k8s): utilize user token for k8s auto update EE-1594

- app/kubernetes/components/kubectl-shell/kubectl-shell.controller.js
- app/kubernetes/components/kubectl-shell/kubectl-shell.html
Closes [EE-1453](https://portainer.atlassian.net/browse/EE-1453).
> fix(kubernetes/shell): websocket error on close EE-1453 

- app/kubernetes/helpers/application/index.js
Closes [EE-1601](https://portainer.atlassian.net/browse/EE-1601).
> fix(helm): k8s app list view fixed for helm charts with deployments containing multiple pods EE-1601

- app/assets/css/app.css
- app/portainer/components/sensitive-details/sensitive-details.css
- app/portainer/components/sensitive-details/sensitive-details.html
- app/portainer/components/show-hide/show-hide.html
Closes [EE-1600](https://portainer.atlassian.net/browse/EE-1600).
> fix(kubernetes): app list view fix for secrets with long keys or values EE-1600

- app/kubernetes/helpers/application/index.js
- app/kubernetes/helpers/configurationHelper.js
- app/kubernetes/views/applications/applicationsController.js
Closes [EE-1619](https://portainer.atlassian.net/browse/EE-1619).
> fix(helm): helm apps bundling issue across different namespaces EE-1619

- api/http/handler/helm/helm_repo_search_test.go
- api/internal/testhelpers/integration.go
Addresses issue [EE-1599](https://portainer.atlassian.net/browse/EE-1599)
> feat(helm/test) disable slow helm search test by default EE-1599

- api/http/handler/stacks/create_kubernetes_stack.go
> fix(k8s): manifest file not persisted when deploying with manifest URL EE-1586

- api/http/handler/settings/settings_public.go
- app/kubernetes/components/kube-config-download-button/kube-config-download-button.controller.js
- app/kubernetes/components/kube-config-download-button/kube-config-download-button.html
- app/portainer/models/settings.js
> feat(k8s):add kubeconfig expiry days on mouse hover EE-1300

- api/api-description.md
- api/swagger.yaml
> chore(doc): Remove references to deviantony gist EE-1052

- app/kubernetes/views/applications/applicationsController.js
close [EE-1635](https://portainer.atlassian.net/browse/EE-1635)
> feat(k8s): remove stack deletion in k8s app list page.

- api/http/handler/handler.go
- api/portainer.go
- package.json
Closes [EE-1621](https://portainer.atlassian.net/browse/EE-1621).
> update(portainer): version updated

- app/kubernetes/components/helm/helm-templates/helm-templates.html
Closes [EE-1682](https://portainer.atlassian.net/browse/EE-1682).
> fix(helm): helm templates blog post link fix EE-1682

- app/kubernetes/converters/application.js
- app/kubernetes/helpers/application/index.js
- app/kubernetes/models/application/models/index.js
- app/kubernetes/views/applications/applicationsController.js
Closes [EE-1659](https://portainer.atlassian.net/browse/EE-1659).
> fix(helm): duplicate helm apps tree structure fix EE-1659

- api/go.mod
- api/go.sum
- api/http/handler/helm/helm_repo_search.go
- api/http/handler/helm/helm_repo_search_test.go
Closes [EE-1599](https://portainer.atlassian.net/browse/EE-1599)
Allow the SearchRepo handler to be testable.
> feat(helm/tests): update libhelm with new search mock EE-1599

- app/docker/views/images/edit/imageController.js
Closes [EE-1697](https://portainer.atlassian.net/browse/EE-1697).
> fix(docker/images): docker image pull toast notification text fixed EE-1697

- api/exec/kubernetes_deploy.go
- api/http/handler/stacks/create_kubernetes_stack.go
- api/http/handler/stacks/stack_delete.go
- api/http/handler/stacks/stack_migrate.go
- api/portainer.go
> feat(k8s): support delete kub stack

- app/portainer/views/endpoints/edit/endpointController.js
> fix(UI) Fix the agent version number in the UI EE-1657

- app/docker/views/images/edit/imageController.js
Closes [EE-1697](https://portainer.atlassian.net/browse/EE-1697).
source of fix: https://github.com/portainer/portainer/commit/a78102107217b74a2033c6edba8de83f90ff8a73#commitcomment-56661943
> fix(docker): image pull error scenario text fix EE-1697

- app/kubernetes/views/applications/applicationsController.js
close [EE-1635](https://portainer.atlassian.net/browse/EE-1635)
> fix(app): updated logic to delete stack for different kind apps.

- app/kubernetes/views/applications/create/createApplication.html
Closes [EE-1685](https://portainer.atlassian.net/browse/EE-1685).
> fix(kubernetes): edit app dropdown configuration default value EE-1685 

- api/http/handler/customtemplates/customtemplate_create.go
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateViewController.js
> fix(templaate): fix icon not displayed when template created via upload file EE-1712

- api/http/handler/customtemplates/customtemplate_create.go
- app/portainer/views/custom-templates/create-custom-template-view/createCustomTemplateViewController.js
> fix(template): fix icon not displayed when template created via upload file EE-1712

- app/kubernetes/node/service.js
> fix(stats): fix error description on stats for non-admin user EE-1710

- app/kubernetes/node/service.js
> fix(stats): fix error description on stats for non-admin users EE-1710

- app/portainer/views/stacks/create/createStackController.js
> fix(stack): fix git stack authentication on by default EE-1709

- app/portainer/views/stacks/create/createStackController.js
> fix(stack): fix authentication toggle on by default EE-1709

- app/portainer/components/endpoint-list/endpoint-item/endpoint-item-controller.js
- app/portainer/components/endpoint-list/endpoint-item/endpointItem.js
- app/portainer/components/endpoint-list/endpoint-list.js
- app/portainer/components/endpoint-list/endpointList.html
- app/portainer/views/home/home.html
- app/portainer/views/home/homeController.js
> fix(edge): fix edge heartbeat turn red when use search filter EE-1686

- app/portainer/components/endpoint-list/endpoint-item/endpoint-item-controller.js
- app/portainer/components/endpoint-list/endpoint-item/endpointItem.js
- app/portainer/components/endpoint-list/endpoint-list.js
- app/portainer/components/endpoint-list/endpointList.html
- app/portainer/views/home/home.html
- app/portainer/views/home/homeController.js
> fix(edge): fix edge heartbeat show red when use search filter EE-1686

- app/portainer/components/forms/git-form/git-form-auth-fieldset/git-form-auth-fieldset.css
- app/portainer/components/forms/git-form/git-form-auth-fieldset/git-form-auth-fieldset.html
- app/portainer/components/forms/git-form/git-form-auth-fieldset/index.js
close [EE-1636](https://portainer.atlassian.net/browse/EE-1636)
> fix(k8s): fixed qusetion mark alignment issue in PAT field.

- app/portainer/components/forms/git-form/git-form-auth-fieldset/git-form-auth-fieldset.html
close [EE-1707](https://portainer.atlassian.net/browse/EE-1707)
> fix(stack): deploy git stack without username. EE-1707

- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
> fix(k8s):fix difficulties selecting mixed protocols when creating k8s application EE-1073

- app/assets/css/theme.css
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.css
> fix(ui): fix application table background not working with dark mode EE-1653

- app/portainer/services/notifications.js
> fix(notification): fix error in kube application stack name with space EE-1726

- app/portainer/views/wizard/wizard-view.html
> fix(wizard): rename endpoint to environment in wizard breadcrumb header EE-1736

- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.js
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatableController.js
- app/kubernetes/views/applications/applications.html
Closes [EE-1730](https://portainer.atlassian.net/browse/EE-1730).
> fix(helm): helm apps in system namespace not shown in dropdown EE-1730

- app/assets/css/vendor-override.css
> fix(theme): fix danger button hover color EE-1638

- app/kubernetes/components/helm/helm-templates/helm-templates.html
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/configurations/create/createConfiguration.html
- app/kubernetes/views/deploy/deploy.html
- app/kubernetes/views/deploy/deployController.js
> fix(k8s): fix error handling for namespace restricted user EE-1703

- api/bolt/migrator/migrate_dbversion31.go
> fix(migration): add debug logging for volume migration

- app/kubernetes/views/summary/summaryController.js
close [EE-1678](https://portainer.atlassian.net/browse/EE-1678)
> fix(name): fixed namespace creation issue when a registry attached.

- api/bolt/migrate_data.go
- api/bolt/migrator/migrate_ce.go
Addresses [EE-1742](https://portainer.atlassian.net/browse/EE-1742)
> feat(migration): wrap migration errors to provide context for failure EE-1742

- app/kubernetes/components/datatables/application/containers-datatable/containersDatatable.html
- app/kubernetes/pod/converter.js
> feat(pod): show ip address of pod(s) EE-1565

- app/kubernetes/components/helm/helm-templates/helm-add-repository/helm-add-repository.controller.js
- app/kubernetes/components/helm/helm-templates/helm-templates.html
- app/kubernetes/components/kubectl-shell/kubectl-shell.controller.js
- app/kubernetes/components/view-header/viewHeader.html
- app/kubernetes/custom-templates/kube-custom-templates-view/kube-custom-templates-view.html
- app/kubernetes/registries/kube-registry-access-view/kube-registry-access-view.controller.js
- app/kubernetes/views/applications/applicationsController.js
- app/kubernetes/views/applications/create/createApplicationController.js
- app/kubernetes/views/applications/edit/applicationController.js
- app/kubernetes/views/applications/helm/helm.controller.js
- app/kubernetes/views/cluster/node/nodeController.js
- app/kubernetes/views/configurations/configurationsController.js
- app/kubernetes/views/configurations/edit/configurationController.js
- app/kubernetes/views/resource-pools/access/resourcePoolAccessController.js
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
- app/kubernetes/views/resource-pools/resourcePoolsController.js
- app/kubernetes/views/volumes/edit/volumeController.js
- app/kubernetes/views/volumes/volumesController.js
- app/portainer/components/forms/kubernetes-app-git-form/kubernetes-app-git-form.controller.js
- app/portainer/views/endpoints/access/endpointAccessController.js
Closes [EE-1628](https://portainer.atlassian.net/browse/EE-1628).
> feat(kubectl-shell): page state refreshes in k8s endpoint do not close shell EE-1628

- api/http/handler/users/user_inspect.go
- api/http/handler/users/user_list.go
- api/portainer.go
for #5136
I didn't find the docs for updating the swagger docs - I presume its a build step that is automated?
> fix(swagger): EE-868: elide the password field in the swagger docs

- app/portainer/components/endpoint-list/endpoint-item/endpoint-item-controller.js
> fix(edge): add wiggle room back to edge endpoint EE-1747

- app/docker/models/container.js
Signed-off-by: Sven Dowideit <sven@mini.home.org.au>
for #4818
This needs re-testing for Docker, running on cgroups v1 and v2
> fix(docker): EE-348: fix Docker stats when using cgroups v2

- app/assets/css/theme.css
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/portainer/components/status-indicator/index.js
- app/portainer/components/status-indicator/status-indicator.css
- app/portainer/components/status-indicator/status-indicator.html
add colored status to applications datatable:
> feat(applications): show status indication [EE-1623]

- api/exec/exectest/kubernetes_mocks.go
- api/exec/kubernetes_deploy.go
- api/go.mod
- api/go.sum
- api/http/handler/helm/handler.go
- api/http/handler/helm/helm_delete_test.go
- api/http/handler/helm/helm_install.go
- api/http/handler/helm/helm_install_test.go
- api/http/handler/helm/helm_list_test.go
- api/http/handler/stacks/create_kubernetes_stack.go
- api/http/server.go
- api/kubernetes/yaml.go
- api/kubernetes/yaml_test.go
- app/kubernetes/helpers/application/index.js
Closes [EE-1624](https://portainer.atlassian.net/browse/EE-1624).
> feat(helm): helm apps deployed by portainer not marked as external EE-1624

- api/bolt/datastore.go
> fix(DB): modify new data store checking logic

- app/kubernetes/models/application/formValues.js
> fix(k8s): set isolated as default for k8s app deploy EE-1743

- app/assets/css/app.css
- app/assets/css/vendor-override.css
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/create/createResourcePoolController.js
- app/portainer/components/be-feature-indicator/be-feature-indicator.css
- app/portainer/components/box-selector/box-selector-item/box-selector-item.controller.js
- app/portainer/feature-flags/feature-flags.css
- app/portainer/feature-flags/feature-flags.service.js
- app/portainer/feature-flags/feature-ids.js
- app/portainer/feature-flags/index.js
- app/portainer/feature-flags/limited-feature.directive.js
- app/portainer/views/settings/settings.html
- app/portainer/views/settings/settingsController.js
[EE-1740]
[EE-1740]: https://portainer.atlassian.net/browse/EE-1740
> feat(feature-flags): enhance framework

- app/kubernetes/views/applications/edit/applicationController.js
> fix(k8s): fix showing create from application form when create from url EE-1598

- app/kubernetes/components/datatables/applications-datatable/applicationsDatatable.html
- app/kubernetes/components/datatables/applications-datatable/applicationsDatatableController.js
Closes [EE-1627](https://portainer.atlassian.net/browse/EE-1627).
This pr introduce filter for kubernetes application types:
- Deployment
- Daemonset
- Statefulset
- Pod
- Helm
> feat(k8s): add filter for k8s application type EE-1627

- app/portainer/views/auth/authController.js
> fix(ui): fix custom logo not updated EE-1660

- app/portainer/components/sidebar/sidebar.css
> fix(ui): fix icon line up issue in sidebar EE-1773

- app/config.js
- app/portainer/views/init/admin/initAdminController.js
- gruntfile.js
- webpack/webpack.testing.js
fix [EE-1374]
[EE-1374]: https://portainer.atlassian.net/browse/EE-1374
> chore(build): set node_env to testing

- app/assets/css/app.css
- app/portainer/components/be-feature-indicator/be-feature-indicator.css
- app/portainer/components/be-feature-indicator/be-feature-indicator.html
- app/portainer/components/forms/por-switch/por-switch.css
- app/portainer/feature-flags/feature-flags.css
- app/portainer/views/settings/settings.html
close [EE-1674](https://portainer.atlassian.net/browse/EE-1674)
> feat(s3): backport S3 backup component and added BE highlight value

- app/portainer/components/datatables/registries-datatable/registriesDatatable.html
Close [EE-1734]
[EE-1734]: https://portainer.atlassian.net/browse/EE-1734
> fix(template): remove no registries message EE-1734

- api/bolt/datastore.go
- api/bolt/migrate_data_test.go
- api/bolt/teststore.go
- api/cmd/portainer/main.go
Fixed  [EE-1775](https://portainer.atlassian.net/browse/EE-1775)
> fix(migration) datastore always marked new and migrations skipped EE-1775

- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePoolController.js
[EE-1784]
[EE-1784]: https://portainer.atlassian.net/browse/EE-1784
> fix(k8s/ns): limit features when editing

- app/portainer/components/box-selector/box-selector-item/box-selector-item.controller.js
- app/portainer/components/box-selector/box-selector-item/box-selector-item.html
- app/portainer/components/box-selector/box-selector-item/index.js
- app/portainer/oauth/components/oauth-settings/oauth-settings.controller.js
- app/portainer/oauth/components/oauth-settings/oauth-settings.html
- app/portainer/settings/authentication/ldap/ldap-settings-custom/ldap-settings-custom.html
[EE-1786]
this fixes the issues in EE-1786 and the issue with updating existing oauth settings without providing the client secret
[EE-1786]: https://portainer.atlassian.net/browse/EE-1786
> fix(oauth): clear authentication when moving from custom

- app/portainer/components/box-selector/box-selector-item/box-selector-item.html
- app/portainer/feature-flags/feature-flags.css
- app/portainer/feature-flags/limited-feature.directive.js
- app/portainer/settings/authentication/ldap/ad-settings/ad-settings.html
- app/portainer/settings/authentication/ldap/ldap-connectivity-check/index.js
- app/portainer/settings/authentication/ldap/ldap-connectivity-check/ldap-connectivity-check.html
- app/portainer/settings/authentication/ldap/ldap-custom-group-search/index.js
- app/portainer/settings/authentication/ldap/ldap-custom-group-search/ldap-custom-group-search.html
- app/portainer/settings/authentication/ldap/ldap-custom-user-search/index.js
- app/portainer/settings/authentication/ldap/ldap-custom-user-search/ldap-custom-user-search.html
- app/portainer/settings/authentication/ldap/ldap-group-search-item/index.js
- app/portainer/settings/authentication/ldap/ldap-group-search-item/ldap-group-search-item.html
- app/portainer/settings/authentication/ldap/ldap-group-search/index.js
- app/portainer/settings/authentication/ldap/ldap-group-search/ldap-group-search.html
- app/portainer/settings/authentication/ldap/ldap-settings-custom/ldap-settings-custom.controller.js
- app/portainer/settings/authentication/ldap/ldap-settings-custom/ldap-settings-custom.html
- app/portainer/settings/authentication/ldap/ldap-settings-dn-builder/index.js
- app/portainer/settings/authentication/ldap/ldap-settings-dn-builder/ldap-settings-dn-builder.html
- app/portainer/settings/authentication/ldap/ldap-settings-group-dn-builder/index.js
- app/portainer/settings/authentication/ldap/ldap-settings-group-dn-builder/ldap-settings-group-dn-builder.html
- app/portainer/settings/authentication/ldap/ldap-settings-openldap/ldap-settings-openldap.html
- app/portainer/settings/authentication/ldap/ldap-settings-security/index.js
- app/portainer/settings/authentication/ldap/ldap-settings-security/ldap-settings-security.html
- app/portainer/settings/authentication/ldap/ldap-settings-test-login/index.js
- app/portainer/settings/authentication/ldap/ldap-settings-test-login/ldap-settings-test-login.html
- app/portainer/settings/authentication/ldap/ldap-user-search-item/index.js
- app/portainer/settings/authentication/ldap/ldap-user-search-item/ldap-user-search-item.html
- app/portainer/settings/authentication/ldap/ldap-user-search/index.js
- app/portainer/settings/authentication/ldap/ldap-user-search/ldap-user-search.html
[EE-1785]
[EE-1785]: https://portainer.atlassian.net/browse/EE-1785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ldap): make BE fields uselectable

- app/portainer/components/box-selector/box-selector-item/box-selector-item.css
> fix(box-selector): fixed icon position in different view port.

- api/http/handler/handler.go
- api/http/handler/ldap/handler.go
- api/http/handler/ldap/ldap_check.go
- api/http/handler/settings/handler.go
- api/http/server.go
- api/ldap/ldap.go
- api/portainer.go
[EE-1801]
[EE-1801]: https://portainer.atlassian.net/browse/EE-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ldap): test connectivity

- app/portainer/oauth/components/oauth-settings/oauth-settings.controller.js
- app/portainer/oauth/components/oauth-settings/oauth-settings.html
> fix(oauth): custom oauth config disappears EE-1821

- app/kubernetes/views/deploy/deployController.js
Closes [EE-1792](https://portainer.atlassian.net/browse/EE-1792)
> fix(deployment): remove compose path default value [EE-1792]

- api/bolt/migrator/migrate_dbversion31.go
> fix(migration): ignore volumes with no created timestamp EE-1966

- api/bolt/migrator/migrate_dbversion31.go
> fix(migration): ignore volumes with no created timestamp EE-1966 [release]

- app/azure/models/container_group.js
> fix(frontend/EE-1555) Allow undefined values for container port [EE-1555]

- app/kubernetes/components/kubernetes-sidebar/kubernetes-sidebar.html
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/configure/configure.html
- app/kubernetes/views/resource-pools/create/createResourcePool.html
- app/kubernetes/views/resource-pools/edit/resourcePool.html
- app/portainer/__module.js
- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/endpoints/edit/endpoint.html
- app/portainer/views/init/endpoint/initEndpointController.js
> fix(ui): fix cluster setup page route EE-1994

- api/http/handler/stacks/stack_update_git.go
> fix(stack): git credential got reset when updating docker stack EE-1967

- api/chisel/tunnel.go
> fix(edge) EE-2027 cannot connect to edge agent with high network latency

- api/http/handler/endpoints/handler.go
> fix(docker): fix docker pull limit not showed to non admin EE-2037

- api/http/handler/customtemplates/customtemplate_create.go
> fix(custom-templates): avoid creation of template if the compose file does not exist EE-1470

- app/assets/css/vendor-override.css
- app/portainer/components/theme/theme-settings.controller.js
- app/portainer/services/authentication.js
- app/portainer/services/themeManager.js
- app/portainer/views/logout/logoutController.js
- app/portainer/views/main/mainController.js
> feat(ui): add option to sync portainer with system theme EE-1788

- api/cli/cli.go
- api/cli/pairlistbool.go
- api/cmd/portainer/main.go
- api/cmd/portainer/main_test.go
~~note: we don't test for persistence of the feature flags (since from discussions that maybe subject to change in future).~~
> Unit tests for `enableFeaturesFromFlags` function

- app/docker/models/event.js
> fix(docker-event-display): EE-1968: support the exec exited event type

- app/portainer/components/forms/git-form/git-form-auto-update-fieldset/git-form-auto-update-fieldset.html
- app/portainer/components/forms/stack-redeploy-git-form/stack-redeploy-git-form.controller.js
> fix(k8s): fixed force redeployment info text

- app/config.js
- app/portainer/hooks/useLocalStorage.ts
- app/portainer/services/axios.ts
- package.json
- yarn.lock
[EE-1896]
[EE-1896]: https://portainer.atlassian.net/browse/EE-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(app): add axios [EE-1896]

- app/kubernetes/views/deploy/deploy.html
- app/kubernetes/views/deploy/deployController.js
> fix(k8s): k8s deployment manifest file placeholder

- app/react-tools/RootProvider.tsx
- app/react-tools/react2angular.tsx
[EE-2023]
[EE-2023]: https://portainer.atlassian.net/browse/EE-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(app): wrap react with StrictMode [EE-2023]

- app/portainer/components/form-components/FormControl/FormControl.stories.tsx
- app/portainer/components/form-components/FormControl/FormControl.test.tsx
- app/portainer/components/form-components/FormControl/FormControl.tsx
- app/portainer/components/form-components/FormControl/index.ts
- app/portainer/components/form-components/Input/BaseInput.tsx
- app/portainer/components/form-components/Input/NumberInput.stories.tsx
- app/portainer/components/form-components/Input/NumberInput.tsx
- app/portainer/components/form-components/Input/Select.stories.tsx
- app/portainer/components/form-components/Input/Select.tsx
- app/portainer/components/form-components/Input/TextInput.stories.tsx
- app/portainer/components/form-components/Input/TextInput.tsx
- app/portainer/components/form-components/Input/Textarea.tsx
- app/portainer/components/form-components/Input/index.ts
- app/portainer/components/form-components/Input/types.ts
- yarn.lock
Closes [EE-2007](https://portainer.atlassian.net/browse/EE-2007)
> feat(app): added Input components [EE-2007]

- app/portainer/services/stateManager.js
- app/portainer/views/endpoints/endpointsController.js
- app/portainer/views/sidebar/sidebarController.js
> fix(sidebar): clear current endpoint if deleted [EE-873]

- .eslintrc.yml
- app/portainer/components/Button/ButtonGroup.tsx
- app/portainer/components/form-components/ButtonSelector/ButtonSelector.module.css
- app/portainer/components/form-components/ButtonSelector/ButtonSelector.stories.tsx
- app/portainer/components/form-components/ButtonSelector/ButtonSelector.tsx
[EE-2004]
[EE-2004]: https://portainer.atlassian.net/browse/EE-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(app): introduce button selector component [EE-2004]

- app/portainer/components/form-components/Slider/Slider.module.css
- app/portainer/components/form-components/Slider/Slider.stories.tsx
- app/portainer/components/form-components/Slider/Slider.test.tsx
- app/portainer/components/form-components/Slider/Slider.tsx
- package.json
- yarn.lock
Closes [EE-2002](https://portainer.atlassian.net/browse/EE-2002)
> feat(app): add Slider component [EE-2002]

- app/docker/components/log-viewer/logViewerController.js
closes https://github.com/portainer/portainer/issues/4318
closes [EE-1957]
[EE-1957]: https://portainer.atlassian.net/browse/EE-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(logs): strip trailing comma [EE-1957]

- app/portainer/views/settings/settings.html
closes https://github.com/portainer/portainer/issues/4437
closes [EE-1698]
[EE-1698]: https://portainer.atlassian.net/browse/EE-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(settings): move custom logo url [EE-1698]

- app/assets/css/index.js
- app/portainer/components/Button/AddButton.tsx
- app/portainer/components/form-components/Input/BaseInput.tsx
- app/portainer/components/form-components/Input/Select.tsx
- app/portainer/components/form-components/Input/TextInput.tsx
- app/portainer/components/form-components/InputList/InputList.module.css
- app/portainer/components/form-components/InputList/InputList.stories.tsx
- app/portainer/components/form-components/InputList/InputList.tsx
- app/portainer/components/form-components/InputList/index.ts
- app/portainer/components/form-components/InputList/utils.test.ts
- app/portainer/components/form-components/InputList/utils.ts
- yarn.lock
[EE-2003]
[EE-2003]: https://portainer.atlassian.net/browse/EE-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(app): introduce input list component [EE-2003]

- api/http/handler/stacks/create_kubernetes_stack.go
- app/kubernetes/views/deploy/deployController.js
this pr provide the ability for user to specify their own namespace from manifest rather than using the "namespace selector" when they need it. 
close EE-1545
> feat(k8s): change the namespace selector behaviour EE-1545

- app/assets/css/app.css
- app/portainer/components/form-components/Input/NumberInput.tsx
- app/portainer/components/form-components/Input/Select.tsx
- app/portainer/components/form-components/Input/TextInput.tsx
- app/portainer/components/form-components/Input/Textarea.tsx
- app/portainer/components/form-components/Input/types.ts
- app/portainer/components/form-components/InputGroup/InputGroup.stories.tsx
- app/portainer/components/form-components/InputGroup/InputGroup.tsx
- app/portainer/components/form-components/InputGroup/InputGroupAddon.tsx
- app/portainer/components/form-components/InputGroup/InputGroupButtonWrapper.tsx
- app/portainer/components/form-components/InputGroup/index.ts
[EE-2062]
[EE-2062]: https://portainer.atlassian.net/browse/EE-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(app): introduce input-group component [EE-2062]

- build/download_helm_binary.sh
- build/download_kompose_binary.sh
- build/download_kubectl_binary.sh
- gruntfile.js
usage: `grunt download_binaries:darwin:amd64`
> chore(build): allow darwin binaries download [EE-2070]

- app/portainer/views/endpoints/create/createEndpointController.js
- app/portainer/views/wizard/wizard-endpoints/wizard-endpoint-docker/wizard-docker.controller.js
Reverts portainer/portainer#5895
> Revert "fix(endpoints): use the right command for windows agent EE-1877"

- api/bolt/settings/settings.go
- api/hostmanagement/openamt/authorization.go
- api/hostmanagement/openamt/configCIRA.go
- api/hostmanagement/openamt/configDomain.go
- api/hostmanagement/openamt/configProfile.go
- api/hostmanagement/openamt/configWireless.go
- api/http/handler/hostmanagement/openamt/openamt.go
- api/portainer.go
- app/portainer/settings/general/open-amt/open-amt.controller.js
- app/portainer/settings/general/open-amt/open-amt.html
Backport fixes from [latest commit](https://github.com/portainer/portainer-ee/pull/1070/commits/978c69a20241e3bc01ecc35cca1ed5131ac7825b) in [EE](https://github.com/portainer/portainer-ee/pull/1070)
> fix(openamt): fix IsFeatureFlagEnabled, rename MPS Url to MPS Server [INT-6]

- app/docker/components/imageRegistry/por-image-registry.controller.js
- app/docker/components/imageRegistry/por-image-registry.html
> fix(registry): fix order of registries in drop down menu EE-1939

- api/apikey/apikey.go
- api/apikey/cache.go
- api/apikey/cache_test.go
- api/apikey/service.go
- api/apikey/service_test.go
- api/http/handler/users/user_update.go
- api/http/handler/users/user_update_test.go
Closes [EE-2113](https://portainer.atlassian.net/browse/EE-2113).
> fix(api-keys): user role change evicts user keys in cache EE-2113

- app/kubernetes/ingress/converter.js
- app/kubernetes/models/application/formValues.js
- app/kubernetes/services/applicationService.js
- app/kubernetes/views/applications/create/createApplication.html
- app/kubernetes/views/applications/create/createApplicationController.js
- tsconfig.json
[EE-1927]
[EE-1927]: https://portainer.atlassian.net/browse/EE-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(k8s/ingress): ensure new ports are only added to ingress only if app is published via ingress

- app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
feat(home): show cpu and ram for non local endpoints EE-2077
> feat(home): show cpu and ram for non local endpoints EE-2077

- app/portainer/components/widget/WidgetTitle.tsx
Closes [EE-2118](https://portainer.atlassian.net/browse/EE-2118)
> fix(react): use ctrl directive in WidgetTitle component [EE-2118]

- api/bolt/settings/settings.go
- api/hostmanagement/openamt/authorization.go
- api/hostmanagement/openamt/configCIRA.go
- api/hostmanagement/openamt/configDomain.go
- api/hostmanagement/openamt/configProfile.go
- api/hostmanagement/openamt/configWireless.go
- api/http/handler/hostmanagement/openamt/openamt.go
- api/portainer.go
- app/portainer/settings/general/open-amt/open-amt.controller.js
- app/portainer/settings/general/open-amt/open-amt.html
Reverts portainer/portainer#6172
> Revert "fix(openamt): fix IsFeatureFlagEnabled, rename MPS Url to MPS Server [INT-6]"

- api/bolt/settings/settings.go
- api/hostmanagement/openamt/authorization.go
- api/hostmanagement/openamt/configCIRA.go
- api/hostmanagement/openamt/configDomain.go
- api/hostmanagement/openamt/configProfile.go
- api/hostmanagement/openamt/configWireless.go
- api/http/handler/hostmanagement/openamt/openamt.go
- api/portainer.go
- app/portainer/settings/general/open-amt/open-amt.controller.js
- app/portainer/settings/general/open-amt/open-amt.html
Safely re-apply this PR that got reverted.
Backport fixes from [latest commit](https://github.com/portainer/portainer-ee/pull/1070/commits/978c69a20241e3bc01ecc35cca1ed5131ac7825b) in [EE](https://github.com/portainer/portainer-ee/pull/1070)
> fix(openamt): fix IsFeatureFlagEnabled, rename MPS Url to MPS Server

- api/hostmanagement/openamt/configDevice.go
- api/hostmanagement/openamt/openamt.go
- api/http/handler/endpoints/endpoint_list.go
- api/http/handler/hostmanagement/openamt/amtconfiguration.go
- api/http/handler/hostmanagement/openamt/amtdevices.go
- api/http/handler/hostmanagement/openamt/amtrpc.go
- api/http/handler/hostmanagement/openamt/handler.go
- api/http/handler/hostmanagement/openamt/openamt.go
- api/http/server.go
- api/internal/endpointutils/endpoint_test.go
- api/internal/endpointutils/endpointutils.go
- api/portainer.go
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatable.html
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatable.js
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatableController.js
- app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
- app/portainer/components/datatables/endpoints-datatable/endpointsDatatableController.js
- app/portainer/helpers/endpointHelper.js
- app/portainer/rest/openAMT.js
- app/portainer/services/api/openAMTService.js
- app/portainer/views/endpoints/edit/endpoint.html
- app/portainer/views/endpoints/edit/endpointController.js
Closes [INT-8](https://portainer.atlassian.net/browse/INT-8)
Show raw AMT RPC information in edit endpoint view  (only for Docker environments)
Show managed devices information in endpoint list view
disconnected:
connected:
> feat(openamt): add AMT Devices information in Environments view [INT-8]

- app/portainer/components/widget/WidgetCustomHeader.tsx
> fix(template): fix app templates symbol EE-2098

- app/portainer/components/widget/WidgetCustomHeader.tsx
> fix(template): fix app template symbol EE-2098

- api/bolt/webhook/webhook.go
- api/http/handler/webhooks/handler.go
- api/http/handler/webhooks/webhook_create.go
- api/http/handler/webhooks/webhook_execute.go
- api/http/handler/webhooks/webhook_update.go
- api/internal/registryutils/access/access.go
- api/internal/registryutils/auth_header.go
- api/internal/registryutils/permissions.go
- api/portainer.go
- app/docker/views/services/create/createServiceController.js
- app/docker/views/services/edit/serviceController.js
- app/portainer/rest/webhooks.js
- app/portainer/services/api/webhookService.js
> feat(webhook) EE-2125 send registry auth haeder when update swarms service via webhook

- api/http/handler/kubernetes/kubernetes_config.go
- api/kubernetes/cli/client.go
- api/kubernetes/cli/naming.go
- api/kubernetes/cli/service_account.go
- api/kubernetes/cli/service_account_test.go
- app/portainer/components/endpoint-list/endpointList.html
Closes [EE-2123](https://portainer.atlassian.net/browse/EE-2123)
> fix(kubeconfig): show kubeconfig download button for non admin users [EE-2123]

- api/http/handler/kubernetes/kubernetes_config.go
- api/kubernetes/cli/client.go
- api/kubernetes/cli/naming.go
- api/kubernetes/cli/service_account.go
- api/kubernetes/cli/service_account_test.go
- app/portainer/components/endpoint-list/endpointList.html
Closes [EE-2123](https://portainer.atlassian.net/browse/EE-2123)
> fix(kubeconfig): show kubeconfig download button for non admin users [EE-2123] RELEASE

- app/kubernetes/components/kubernetes-sidebar/kubernetes-sidebar.html
> fix(cy): fix data-cy for k8s cluster menu EE-2131

- api/hostmanagement/openamt/configDevice.go
- api/hostmanagement/openamt/deviceFeatures.go
- api/hostmanagement/openamt/openamt.go
- api/http/handler/hostmanagement/openamt/amtdevices.go
- api/http/handler/hostmanagement/openamt/handler.go
- api/portainer.go
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatable.html
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatableController.js
- app/portainer/rest/openAMT.js
- app/portainer/services/api/openAMTService.js
- app/portainer/views/endpoints/kvm/KVMControl.css
- app/portainer/views/endpoints/kvm/KVMControl.tsx
- app/portainer/views/endpoints/kvm/endpointKVM.html
Closes [INT-25](https://portainer.atlassian.net/browse/INT-25)
> feat(openamt): Enable KVM by default [INT-25]

- api/fdo/ownerclient/aux.go
- api/fdo/ownerclient/client.go
- api/go.mod
- api/go.sum
- api/http/handler/handler.go
- api/http/handler/hostmanagement/fdo/handler.go
- api/http/handler/hostmanagement/fdo/list.go
- api/http/handler/hostmanagement/fdo/register.go
- api/http/server.go
> feat(fdo): implement Owner client INT-17

- api/exec/common.go
- api/exec/compose_stack.go
- api/exec/compose_stack_test.go
> fix(docker): provide workaround to save network name variable 

- app/portainer/settings/general/open-amt/open-amt.html
This is only supported for Windows 10  systems
> feat(openamt): hide wireless config in OpenAMT form

- api/docker/client.go
- api/docker/snapshot.go
- api/hostmanagement/openamt/openamt.go
- api/http/handler/hostmanagement/openamt/amtactivation.go
- api/http/handler/hostmanagement/openamt/amtrpc.go
- api/http/handler/stacks/handler.go
- api/http/handler/webhooks/webhook_execute.go
- api/http/proxy/factory/docker/access_control.go
- api/http/proxy/factory/docker/volumes.go
- app/portainer/components/datatables/endpoints-datatable/endpointsDatatableController.js
Closes [INT-30](https://portainer.atlassian.net/browse/INT-30)
> feat(openamt): Increase OpenAMT timeouts [INT-30]

- app/assets/css/app.css
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatable.html
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatableController.js
Closes [INT-36](https://portainer.atlassian.net/browse/INT-36)
> feat(openamt): Disable the ability to use KVM and OOB actions on a MPS disconnected device [INT-36]

- api/go.mod
- api/go.sum
- api/http/handler/file/handler.go
using https://pkg.go.dev/github.com/gorilla/handlers?utm_source=godoc#CompressHandler from https://github.com/gorilla/handlers
> feat: gzip static resources

- api/datastore/datastore_test.go
Closes [EE-2112](https://portainer.atlassian.net/browse/EE-2112)
> feat(store): implement store tests EE-2112

- api/http/handler/hostmanagement/openamt/amtdevices.go
- app/portainer/views/endpoints/edit/endpointController.js
- app/portainer/views/settings/settings.html
Closes [INT-29](https://portainer.atlassian.net/browse/INT-29)
> feat(openamt): Do not fetch OpenAMT details for an unassociated Edge endpoint

- app/portainer/settings/general/open-amt/open-amt.controller.js
- app/portainer/settings/general/open-amt/open-amt.html
- app/portainer/views/settings/settings.html
[EE-2166]
[EE-2166]: https://portainer.atlassian.net/browse/EE-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(intel): fix switches params [EE-2166]

- app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.js
- app/portainer/components/datatables/endpoints-datatable/endpointsDatatableController.js
- app/portainer/views/endpoints/endpoints.html
- app/portainer/views/endpoints/endpointsController.js
Closes [INT-39](https://portainer.atlassian.net/browse/INT-39)
> feat(openamt): Better UI/UX for AMT activation loading [INT-39]

- api/hostmanagement/openamt/openamt.go
- api/http/handler/hostmanagement/openamt/amtconfiguration.go
- api/http/handler/hostmanagement/openamt/amtdevices.go
- api/http/handler/hostmanagement/openamt/handler.go
- api/portainer.go
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatable.html
- app/portainer/components/datatables/amt-devices-datatable/amtDevicesDatatableController.js
- app/portainer/rest/openAMT.js
- app/portainer/services/api/openAMTService.js
- app/portainer/views/endpoints/kvm/endpointKVMController.js
Closes [INT-37](https://portainer.atlassian.net/browse/INT-37)
> feat(openamt): change kvm redirection for pop up, always enable features [INT-37]

- app/portainer/oauth/components/oauth-settings/oauth-settings.controller.js
- app/portainer/settings/authentication/ldap/ad-settings/ad-settings.controller.js
[EE-1896]
[EE-1896]: https://portainer.atlassian.net/browse/EE-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(app): main services [EE-1896]

- package.json
- webpack/webpack.analyze.js
- webpack/webpack.common.js
- webpack/webpack.optimize.js
- yarn.lock
[EE-2132]
[EE-2132]: https://portainer.atlassian.net/browse/EE-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(build): add script to analyze webpack bundle [EE-2132]

- app/assets/css/app.css
> fix(ui): fix scroolbar shown in confirmation dialogs EE-2150

- app/portainer/views/home/homeController.js
> fix(home): display tags properly [EE-2153]

- api/dataservices/team/team.go
- api/dataservices/team/tests/team_test.go
- api/dataservices/team/tests/utils.go
fixes [EE-2184]
[EE-2184]: https://portainer.atlassian.net/browse/EE-2184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(teams): create more then one team [EE-2184]

- app/portainer/services/modal.service/prompt.ts
Closes [EE-2325](https://portainer.atlassian.net/browse/EE-2325)
> fix(kubeconfig): fix modal inputType [EE-2325]

- .eslintrc.yml
- app/angulartics.matomo/analytics-services.ts
- app/angulartics.matomo/index.js
> feat(react): migrate analytics interface to react.

- app/portainer/environments/environment.service/create.ts
- app/portainer/environments/environment.service/index.ts
- app/portainer/environments/environment.service/registries.ts
- app/portainer/services/api/userService.js
- app/portainer/services/axios.ts
> refactor(app): parse axios errors [EE-2327]

- app/edge/views/edge-stacks/createEdgeStackView/create-edge-stack-view.controller.js
- app/edge/views/edge-stacks/createEdgeStackView/docker-compose-form/docker-compose-form.controller.js
- app/edge/views/edge-stacks/createEdgeStackView/kube-manifest-form/kube-manifest-form.controller.js
- app/kubernetes/custom-templates/kube-create-custom-template-view/kube-create-custom-template-view.controller.js
- app/portainer/components/form-components/FileUpload/FileUploadField.module.css
- app/portainer/components/form-components/FileUpload/FileUploadField.stories.tsx
- app/portainer/components/form-components/FileUpload/FileUploadField.test.tsx
- app/portainer/components/form-components/FileUpload/FileUploadField.tsx
- app/portainer/components/form-components/FileUpload/FileUploadForm.stories.tsx
- app/portainer/components/form-components/FileUpload/FileUploadForm.test.tsx
- app/portainer/components/form-components/FileUpload/FileUploadForm.tsx
- app/portainer/components/form-components/FileUpload/index.ts
- app/portainer/components/form-components/file-upload-form/file-upload-form.html
- app/portainer/components/form-components/index.js
Closes [EE-2336](https://portainer.atlassian.net/browse/EE-2336)
> feat(react): add FileUploadField and FileUploadForm components [EE-2336]

- app/portainer/environments/environment.service/create.ts
- app/portainer/environments/environment.service/index.ts
- app/portainer/environments/environment.service/registries.ts
- app/portainer/environments/environment.service/utils.ts
- app/portainer/environments/types.ts
fixes [EE-2346]
[EE-2346]: https://portainer.atlassian.net/browse/EE-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(environments): remove angular dep from service [EE-2346]

- app/portainer/components/BoxSelector/BoxSelector.module.css
[EE-1816]
[EE-1816]: https://portainer.atlassian.net/browse/EE-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ldap): show BE border correctly [EE-1816]

- app/kubernetes/ingress/converter.js
- app/kubernetes/ingress/payloads.js
> feat(k8s): add ingressClassName to payload EE-2129

- api/dataservices/edgestack/edgestack.go
- api/dataservices/interface.go
- api/http/handler/edgestacks/edgestack_create.go
[EE-2178]
[EE-2178]: https://portainer.atlassian.net/browse/EE-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(edgestacks): create new stack [EE-2178]

- app/portainer/components/BoxSelector/BoxSelectorItem.css
> fix(theme): fix background color for boxselector in dark/high contrast theme EE-2355

- api/http/handler/auth/authenticate.go
- api/http/handler/users/user_create.go
[EE-648]
[EE-648]: https://portainer.atlassian.net/browse/EE-648
> fix(auth): prevent login for non admin for ldap and oauth

- app/docker/containers/components/ContainersDatatable/ContainersDatatable.tsx
- app/docker/containers/components/ContainersDatatable/ContainersDatatableContainer.tsx
- app/docker/containers/components/ContainersDatatable/ContainersDatatableSettings.tsx
- app/portainer/components/datatables/components/SearchBar.tsx
- app/portainer/components/datatables/components/useRepeater.ts
- app/portainer/rest/stack.js
- app/portainer/views/stacks/edit/stack.html
- package.json
[EE-2359]
[EE-2359]: https://portainer.atlassian.net/browse/EE-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(stacks): show stack containers [EE-2359]

- api/http/proxy/factory/azure/containergroup.go
fixes [EE-2334]
[EE-2334]: https://portainer.atlassian.net/browse/EE-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(azure): parse validation error [EE-2334]

- api/http/handler/endpoints/endpoint_list.go
- app/edge/devices/components/AMTDevicesDatatable/columns/actions.tsx
- app/edge/devices/components/AMTDevicesDatatable/columns/power-state.tsx
- app/edge/devices/components/AMTDevicesDatatable/columns/status.tsx
- app/edge/devices/components/EdgeDevicesDatatable/EdgeDevicesDatatableActions.tsx
- app/edge/devices/components/EdgeDevicesDatatable/columns/actions.tsx
- app/portainer/environments/environment.service/index.ts
- app/portainer/environments/types.ts
- app/portainer/environments/utils.ts
- app/portainer/views/home/homeController.js
Closes [EE-2365](https://portainer.atlassian.net/browse/EE-2365)
> feat(intel): OpenAMT UI/UX adjustments

- app/portainer/oauth/components/oauth-settings/oauth-settings.html
> fix(ui): fix automatic team membership toggle issue EE-2358

- app/portainer/oauth/components/oauth-settings/oauth-settings.controller.js
- app/portainer/oauth/components/oauth-settings/providers.js
fixes [EE-2044]
[EE-2044]: https://portainer.atlassian.net/browse/EE-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(oauth): change default microsoft logout url [EE-2044]

- app/edge/devices/components/EdgeDevicesDatatable/EdgeDevicesDatatableActions.tsx
- app/edge/devices/components/EdgeDevicesDatatable/columns/heartbeat.tsx
- app/portainer/settings/edge-compute/SettingsFDO/SettingsFDO.tsx
- app/portainer/settings/edge-compute/SettingsOpenAMT/SettingsOpenAMT.tsx
- app/portainer/views/endpoints/kvm/endpointKVM.html
https://portainer.atlassian.net/browse/EE-2402
https://portainer.atlassian.net/browse/EE-2403
https://portainer.atlassian.net/browse/EE-2405
https://portainer.atlassian.net/browse/EE-2401
> feat(edge): minor Edge Devices (AMT) UI fixes

- app/kubernetes/rest/kubeconfig.js
close [EE-2352](https://portainer.atlassian.net/browse/EE-2352)
> fix(kube): fixed kube config download info issue.

- app/kubernetes/helpers/application/index.js
> fix(release): fix application edit error for manifest pod application EE-2416

- app/kubernetes/helpers/application/index.js
> fix(k8s): fix error when edit pod application EE-2416

- api/dataservices/resourcecontrol/resourcecontrol.go
> fix(bolt) EE-2415 return nil err when resource controller not found in db

- api/cmd/portainer/main.go
- api/connection.go
- api/database/boltdb/db.go
- api/database/boltdb/db_test.go
- api/datastore/datastore.go
Resolves [EE-2414](https://portainer.atlassian.net/browse/EE-2414)
The logic didn't take into account a new database and made a bad assumption
I've also added a go test for it.
> Fix(db): needs encryption migration function fixed EE-2414

- app/portainer/components/forms/group-form/groupForm.html
- app/portainer/components/group-association-table/group-association-table.js
- app/portainer/components/group-association-table/groupAssociationTable.html
> test(datacy): add data-cy to groupform table EE-2174

- api/http/handler/stacks/stack_migrate.go
fixes [EE-2412]
[EE-2412]: https://portainer.atlassian.net/browse/EE-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(stacks): migrate stack resource control [EE-2412]

- app/assets/css/theme.css
- app/portainer/components/UsersSelector/UsersSelector.css
- app/portainer/components/UsersSelector/UsersSelector.tsx
- app/portainer/components/datatables/datatable.css
- app/portainer/components/pagination-controls/pagination-controls.css
> fix(ui): fix unreadable components in dark mode EE-2417

- app/assets/css/theme.css
- app/portainer/components/UsersSelector/UsersSelector.css
- app/portainer/components/UsersSelector/UsersSelector.tsx
- app/portainer/components/datatables/datatable.css
- app/portainer/components/pagination-controls/pagination-controls.css
> fix(ui): fix components have unreadable text in dark mode EE-2417

- api/cmd/portainer/main.go
> fix(db) EE-2425 http-disabled flag does not work

- app/assets/css/theme.css
> fix(ui): fix input text color in dark mode EE-2448

- app/portainer/services/modal.service/prompt.ts
- app/portainer/services/modal.service/utils.ts
- app/portainer/services/registryModalService.js
Closes [EE-2426](https://portainer.atlassian.net/browse/EE-2426)
> fix(images): fix registryModal [EE-2426]

- api/backup/restore.go
- api/cmd/portainer/main.go
Closes [EE-2435](https://portainer.atlassian.net/browse/EE-2435)
> fix(restore): restore the database file correctly EE-2435

- app/kubernetes/components/kube-services/kube-services-item/kube-services-item.controller.js
- app/kubernetes/components/kube-services/kube-services-item/kube-services-item.html
fix [EE-2445]
[EE-2445]: https://portainer.atlassian.net/browse/EE-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(k8s/app): populate ingress details [EE-2445]

- app/docker/services/containerService.js
- app/portainer/services/axios.ts
fix [EE-2433]
closes [EE-2433] 
auth header use to create a new object of headers, instead of just adding the auth header and it removed the target header from time to time.
[EE-2433]: https://portainer.atlassian.net/browse/EE-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EE-2433]: https://portainer.atlassian.net/browse/EE-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(agent): add agent header [EE-2433]

- app/portainer/components/Tip/Tooltip/Tooltip.module.css
> fix(tooltip): inconsistent tooltip component EE-2472

- api/go.mod
- api/go.sum
closes [EE-2145]
[EE-2145]: https://portainer.atlassian.net/browse/EE-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): upgrade libhttp [EE-2145]
