gruntFile.js

shipping minified scripts

---

app/components/container/container.html
app/components/containerLogs/containerlogs.html
app/components/containers/containers.html
app/components/dashboard/dashboard.html
app/components/image/image.html
app/components/images/images.html
app/components/network/network.html
app/components/networks/networks.html
app/components/stats/stats.html
app/components/stats/statsController.js
app/components/swarm/swarm.html
app/components/volumes/volumes.html
app/directives/header-content.js
app/directives/header-title.js
app/directives/header.js
index.html

Added header directive and updated breadcrumb in each view

---

app/app.js
app/components/container/container.html
app/components/containers/containers.html
app/components/image/image.html
app/components/images/images.html
app/components/network/network.html
app/components/network/networkController.js
app/components/networks/networks.html
app/components/swarm/swarm.html
app/components/volumes/volumes.html
app/components/volumes/volumesController.js
bower.json
gruntFile.js
index.html

switch to angular-ui-router

---

app/components/containers/containers.html
app/components/images/images.html
app/components/networks/networks.html
app/components/swarm/swarm.html
app/components/volumes/volumes.html
app/directives/header-title.js
assets/css/app.css

add a refresh link for each entity view

---

README.md
app/components/containers/containersController.js
dockerui.go

feat(global): hide containers with labels using -l flag

---

Dockerfile
README.md
dockerui.go
gruntFile.js

fix(binary): persist CSRF auth file in a volume

---

app/components/startContainer/startContainerController.js

feat(ui): automatically pull the image when creating a container

---

app/components/containers/containersController.js

feat(ui): display an error message when trying to remove a running container

---

app/components/container/container.html
app/components/container/containerController.js
app/components/containerLogs/containerLogsController.js
app/components/containerLogs/containerlogs.html
app/components/containers/containers.html
app/components/containers/containersController.js
app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html
app/components/createNetwork/createNetworkController.js
app/components/createNetwork/createnetwork.html
app/components/createVolume/createVolumeController.js
app/components/createVolume/createvolume.html
app/components/images/images.html
app/components/images/imagesController.js
app/components/network/network.html
app/components/network/networkController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js
app/shared/services.js
bower.json
gruntFile.js

feat(ui): replace ViewSpinner with JQuery animations

---

app/components/containers/containers.html
app/shared/services.js

feat(ui): default to display all containers

---

app/components/dashboard/dashboardController.js
app/components/swarm/swarm.html
gruntFile.js

This PR also removes the containers displayed in the Swarm view.

fix(ui): hidden containers (using label) are now removed from dashboard and swarm view

---

app/components/images/images.html
app/components/images/imagesController.js

feat(ui): add the ability to pull an image from a private registry

---

README.md
dockerui.go
gruntFile.js

feat(dockerui): add support for TLS enabled engines

---

app/components/containers/containers.html
app/components/containers/containersController.js
app/shared/filters.js
app/shared/viewmodel.js

feat(ui): docker 1.9 support

---

README.md
dockerui.go
gruntFile.js

feat(dockerui): Docker CLI compliant flags

---

README.md

docs(docker): add info about Docker version support

---

app/components/dashboard/dashboard.html
app/components/dashboard/dashboardController.js
app/shared/filters.js
assets/css/app.css

feat(ui): new dashboard view

---

app/components/images/images.html
app/components/networks/networks.html
app/components/volumes/volumes.html

style(ui): add table-hover class to all entity tables

---

app/directives/widget-header.js

style(ui): fix extra space in widget-header

---

app/components/docker/docker.html

style(ui): fix typo in Engine view

---

app/components/images/images.html
app/shared/filters.js
app/shared/viewmodel.js
assets/css/app.css

feat(ui): replace repository field with tags field in image view

---

app/app.js
app/components/events/events.html
app/components/events/eventsController.js
app/shared/filters.js
app/shared/services.js
app/shared/viewmodel.js
bower.json
gruntFile.js
index.html

This PR adds an event view for Docker only (Swarm is not supported at the moment).
It also removes all the dependencies related to Oboe.js.
Close #71

feat(ui): add events view

---

app/components/swarm/swarm.html
app/components/swarm/swarmController.js
app/shared/viewmodel.js

feat(ui): add more info about nodes in Swarm view

---

api/api.go
api/config.go
api/exec.go
api/flags.go
api/handler.go
api/hijack.go
api/main.go
api/ssl.go
app/app.js
app/components/container/container.html
app/components/containerConsole/containerConsole.html
app/components/containerConsole/containerConsoleController.js
app/shared/services.js
assets/css/app.css
bower.json
gruntFile.js

This PR brings a few changes:
* backend restructuration (golang)
* container exec support via websocket
Close #34

feat(global): add container exec support

---

app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js

feat(ui): remove the ability to select all entities from list views

---

app/components/image/image.html
app/components/image/imageController.js
app/shared/filters.js
app/shared/responseHandlers.js
app/shared/services.js
assets/css/app.css

This PR brings a new image view and fixes issues when deleting tags/image from this view.

refactor(ui): updated image view

---

app/components/images/imagesController.js
gruntFile.js

fix(images): display an error message when unable to remove an image

---

app/components/dashboard/dashboardController.js

fix(dashboard): fix an error when no volumes are availables

---

app/components/container/container.html
app/components/events/events.html
app/components/images/images.html
app/shared/filters.js
test/unit/app/shared/filters.spec.js

feat(ui): format all dates to use ISO8601

---

app/components/networks/networks.html
app/components/networks/networksController.js

feat(ui): network creation support for standalone engine

---

README.md
api/main.go
api/settings.go
index.html

feat(global): add the --logo flag to specify an external logo picture

---

app/components/image/image.html
app/components/image/imageController.js
app/shared/responseHandlers.js
app/shared/services.js

feat(image): add the ability to push an image tag

---

app/shared/responseHandlers.js
app/shared/services.js

refactor(handlers): remove duplicated code

---

app/components/image/image.html
app/components/image/imageController.js
app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js
app/shared/filters.js
app/shared/responseHandlers.js
app/shared/services.js
assets/css/app.css
gruntFile.js

Dup #114, re-merge due to conflict.

Fix 113 images view delete

---

README.md
api/main.go
api/settings.go
app/app.js
app/components/createNetwork/createNetworkController.js
app/components/createNetwork/createnetwork.html
app/components/createVolume/createVolumeController.js
app/components/createVolume/createvolume.html
app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js

This PR removes all the changes only related to internal. A bad merge occurred with the internal branch.
DAMN.

refactor(global): revert merge with internal

---

app/components/image/image.html
app/components/image/imageController.js

feat(image): add the ability to tag an image

---

app/components/containerConsole/containerConsoleController.js

feat(console): add protocol awareness to switch between ws:// and wss://

---

README.md

docs(reverse-proxy): add reverse proxy instructions

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html

This PR reverts changes related to the internal merge.

refactor(container-creation): remove changes related to internal version

---

README.md
assets/css/app.css

docs(logo): add documentation about the --logo flag

---

app/components/containers/containers.html

feat(containers): rename the column header Host to Host IP

---

app/components/images/imagesController.js
app/shared/responseHandlers.js

fix(image): display a valid error message when deleting an image

---

app/components/container/container.html
app/components/container/containerController.js
app/components/image/image.html
app/components/image/imageController.js
app/shared/filters.js
app/shared/services.js
assets/css/app.css

This PR brings a new container view, closing #146 .
It also fixes a bug with container name edition and allows to commit a container (close #144).

feat(container): container view overhaul

---

Dockerfile
README.md
api/api.go
api/handler.go
api/main.go
api/settings.go
api/templates.go
app/app.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/shared/services.js
assets/css/app.css
bower.json
gruntFile.js
index.html

feat(global): add templates support ('apps')

---

app/components/templates/templates.html
app/components/templates/templatesController.js

feat(templates): support env variables with default value

---

app/components/templates/templates.html
index.html

style(template): Update title and section name

---

app/app.js
app/components/container/containerController.js
app/components/containers/containersController.js
app/components/createContainer/createContainerController.js
app/components/dashboard/dashboardController.js
app/components/image/imageController.js
app/components/templates/templatesController.js
app/shared/helpers.js

This PR introduce helpers function to centralize some methods.
Related to #168

refactor(ui): introduce helpers functions to centralize code

---

app/components/network/networkController.js
app/components/networks/networksController.js
app/shared/responseHandlers.js
app/shared/services.js

Related to #95.
This PR brings support to network deletion from Docker 1.9 to 1.12.

feat(network): define a response handler for image deletion

---

app/components/image/imageController.js
app/components/images/imagesController.js
app/components/networks/networksController.js
app/shared/responseHandlers.js

feat(image): define a new response handler for image deletion

---

app/components/container/containerController.js
app/components/containers/containersController.js
app/components/createContainer/createContainerController.js
app/components/templates/templatesController.js

feat(container): do not pass HostConfig when starting a container

---

app/components/container/containerController.js
app/components/containerConsole/containerConsoleController.js
app/components/containerLogs/containerLogsController.js
app/components/containers/containersController.js
app/components/createContainer/createContainerController.js
app/components/createNetwork/createNetworkController.js
app/components/createVolume/createVolumeController.js
app/components/events/eventsController.js
app/components/image/imageController.js
app/components/images/imagesController.js
app/components/networks/networksController.js
app/components/stats/statsController.js
app/shared/services.js

feat(ui): new exception management

---

app/components/templates/templatesController.js
app/components/volumes/volumesController.js

feat(ui): add missing exception management

---

README.md

docs(version): update Docker versions support section

---

app/components/containers/containersController.js

fix(containers): make hidden containers labels available in the $scope

---

app/shared/responseHandlers.js
app/shared/services.js

fix(image): support array in Messages.error

---

app/components/containers/containers.html
app/components/image/image.html
app/components/images/images.html
app/components/networks/networks.html
app/components/volumes/volumes.html
assets/css/app.css

style(actions): add icons for every actions

---

app/components/networks/networks.html
app/components/networks/networksController.js

feat(networks): add a quick network creation form

---

app/components/network/network.html
app/components/network/networkController.js
app/shared/filters.js

Close #200 
Close #85 as containers are no longer available in the network view.

feat(network): new network view

---

app/app.js
app/components/containers/containers.html
app/components/containers/containersController.js
app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html
app/components/createNetwork/createNetworkController.js
app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/dashboard/dashboard.html
app/components/dashboard/dashboardController.js
app/components/dashboard/master-ctrl.js
app/components/images/imagesController.js
app/components/networks/networksController.js
app/components/service/service.html
app/components/service/serviceController.js
app/components/services/services.html
app/components/services/servicesController.js
app/components/swarm/swarm.html
app/components/swarm/swarmController.js
app/components/task/task.html
app/components/task/taskController.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/shared/filters.js
app/shared/helpers.js
app/shared/services.js
app/shared/viewmodel.js
gruntFile.js
index.html

This PR brings support for Swarm mode introduced in Docker 1.12:
Updated views:
New view:
Close #208

feat(global): swarm mode support

---

index.html

style(index): add a github icon next to the github link

---

app/components/container/container.html
app/components/containerLogs/containerlogs.html
app/components/containers/containers.html
app/components/dashboard/dashboard.html
app/components/stats/stats.html

style(ui): use fa-server icon instead of fa-tasks for container entity

---

LICENSE
README.md
api/main.go
bower.json
examples/nginx-basic-auth/docker-compose.yml
index.html
package.json

chore(global): replace CloudInovasi with Portainer.io

---

app/components/containers/containers.html

fix(containers): fix the ability to sort containers by status

---

app/components/containers/containers.html

feat(containers): change exposed port format

---

app/shared/viewmodel.js

Close #239 
+ support for container attach event

feat(events): support new events

---

app/components/dashboard/dashboard.html
app/components/swarm/swarmController.js

feat(swarm): support Swarm replica management

---

app/components/dashboard/dashboard.html
app/components/stats/statsController.js
app/components/swarm/swarm.html
app/shared/filters.js
bower.json
gruntFile.js
test/unit/app/shared/filters.spec.js

fix(general): fix the size display using the filesize library

---

app/components/containerConsole/containerConsoleController.js
gruntFile.js

fix(console): fix issue with undefined socket

---

index.html

feat(index): hide Events and Docker view when swarm-mode is enabled

---

app/components/templates/templates.html

fix(templates): fix bad container display when swarm-mode enabled

---

bower.json

chore(xterm): update xterm.js version to 1.1.3

---

app/components/containerConsole/containerConsoleController.js
bower.json
gruntFile.js

Fix #256 
Also fix #261 as the `vendor.js` file was broken.

fix(container-console): use xterm.js v2

---

app/components/containers/containers.html
app/components/containers/containersController.js
app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js
assets/css/app.css

feat(global): display a message when no item available in a list view

---

app/components/containers/containers.html
app/components/containers/containersController.js
app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/services/services.html
app/components/services/servicesController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js

feat(global): display a loading text in list views

---

app/components/templates/templates.html
app/components/templates/templatesController.js
app/directives/widget-custom-header.js
assets/css/app.css
bower.json
gruntFile.js

style(templates): new effect on hover

---

assets/css/app.css

refactor(css): remove useless css classes

---

app/app.js
app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html
app/components/images/imagesController.js
app/components/templates/templates.html
app/shared/helpers.js

feat(templates): advanced template creation

---

app/app.js
app/components/createContainer/createContainerController.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/shared/helpers.js

feat(templates): allow to edit template port mapping

---

app/components/createContainer/createContainerController.js

fix(container-creation): fix default network on Windows platform

---

api/handler.go
app/app.js

Disable CSRF protection

---

app/shared/viewmodel.js

- Fix: labels do not show up in service view.

#304 fix(service): labels not showing in service view

---

api/api.go

feat(backend): add a simple log message to indicate portainer startup

---

app/shared/viewmodel.js

fix(containers): fix an issue with container IP in overlay network

---

app/components/dashboard/master-ctrl.js
index.html

I don't know if you want to get rid of the complete settings object in the scope, that's why I only re-add the logo attribute

Restore the ability to customize the logo image.

---

app/components/container/container.html
app/components/container/containerController.js

- Add overview of joined networks in container view
- Add option to leave a joined network

feat(container): show list of joined networks

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html

- Add ability to add labels on service creation
- Closes #280

Add ability to add labels on service creation

---

app/components/service/service.html
app/components/service/serviceController.js

- Add ability to add / remove and change environment variables of a service.
- Add ability to change the image of a service.
- Change saving of an edited service now happens when pressing save instead of after a change. This is done to let you change multiple values at the same time when updating the service. Also adds a reset option to restore changed values to before they were edited.
- Initial work for #304.

Add change environment variables and image for service

---

gruntFile.js

- Add a option to start Portainer using the local docker socket in swarm mode.
I use this for starting Portainer locally on my laptop in Swarm mode.

chore(grunt): add local swarm option

---

app/components/service/service.html
assets/css/app.css

style(service-details): fix wrong display for some fields

---

build.sh
gruntFile.js

chore(build-system): add a release for macos task

---

app/components/service/service.html

fix(service-details): fix a sorting issue when ordering by last update

---

app/components/templates/templates.html
app/components/templates/templatesController.js

Implements #371 
[![image](https://s13.postimg.org/ceuhp6dtj/screen_2.gif)](https://postimg.org/image/crlvvcw37/)

#371 feat(templates): automatically scroll up to the app template after selecting template

---

app/components/dashboard/dashboardController.js

fix(dashboard): add missing dependency to Messages service

---

app/components/container/container.html

Simple change just added a form and called renameContainer method
Close #186

#186 feat(container): bind the enter key when renaming container

---

app/components/containers/containers.html
app/components/containers/containersController.js
app/shared/filters.js
app/shared/viewmodel.js

feat(containers): add the ability to filter by state

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/service/service.html
app/components/service/serviceController.js
app/shared/viewmodel.js

- Adds the ability to change the update configuration of a service on service creation
- Adds the ability to change the update configuration of a service after service creation

#304 Add editable service update configuration

---

app/components/createNetwork/createNetworkController.js
app/components/createNetwork/createnetwork.html

Add the ability to add labels on network create in the create-network view.

feat(create-network): add labels on network create

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html

Pretty much the same implementation as for networks and services. So that might mean there needs to be some shared component for this.
Close #411

#411 feat(container-creation): add ability to specify labels

---

app/app.js

fix(global): strip leading '/' in front of endpoints

---

app/components/service/serviceController.js
gruntfile.js

fix(service-details): allow to specify the 0 value for replicas

---

app/components/container/containerController.js
app/components/createContainer/createContainerController.js
app/components/image/imageController.js
app/components/images/imagesController.js
app/components/templates/templatesController.js

fix(global): remove automatic lowercase processing on image names

---

app/components/service/service.html

style(service-details): update style for update failure action field

---

api/cmd/portainer/main.go
api/file/file.go

fix(api): creates the data directory if not exist

---

app/components/container/container.html

feat(templates): display container restart policy in container dashboard (#434)

---

api/cli/cli.go
api/cli/defaults.go
api/cli/defaults_windows.go
build/windows/microsoftservercore/Dockerfile
build/windows/nanoserver/Dockerfile

feat(api): create platform dependant default values for CLI flags

---

app/components/containers/containers.html
app/components/containers/containersController.js
app/components/images/images.html
app/components/images/imagesController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/components/volumes/volumes.html
app/components/volumes/volumesController.js

#372 feat(UX): Implement select all functionality

---

app/components/containers/containers.html

style(containers): update header text for published ports

---

api/file/file.go
build/windows/microsoftservercore/Dockerfile
build/windows/nanoserver/Dockerfile

fix(api): disable data directory creation

---

app/shared/responseHandlers.js

fix(images): fix an issue when deleting images with multiple tags

---

app/components/createContainer/createcontainer.html

style(container-creation): remove useless labels section

---

app/components/sidebar/sidebar.html

style(sidebar): add active class on Docker section

---

app/components/swarm/swarm.html

fix(swarm): fix sorting issue with node table

---

app/app.js
app/components/node/node.html
app/components/node/nodeController.js
app/components/swarm/swarm.html
app/shared/helpers.js
app/shared/services.js
app/shared/viewmodel.js

- Adds the ability to inspect a Swarm mode Node.
- Adds the ability to update a node's name, Availability and Labels.
Close #414

feat(node-details): add ability to view and edit Swarm mode nodes

---

api/cli/cli.go
api/cli/defaults.go
api/cli/defaults_windows.go
api/cmd/portainer/main.go
api/http/auth_handler.go
api/http/middleware.go
api/http/server.go
api/portainer.go
app/app.js
app/components/auth/authController.js
app/components/sidebar/sidebar.html
app/directives/header-content.js
app/directives/header-title.js
app/services/authentication.js
app/services/localStorage.js
app/services/stateManager.js

This PR adds a `--no-auth` flag to the Portainer CLI. When enabled, it will bypass the internal authentication mechanism.

feat(authentication): add a --no-auth flag to disable authentication

---

app/helpers/containerHelper.js
app/models/template.js
app/services/templateService.js
bower.json
gruntfile.js

Close #584 
This PR uses https://github.com/deviantony/splitargs to split a command string into an array.

feat(templates): add support for the command field

---

app/components/templates/templatesController.js
app/models/template.js

feat(templates): add support for the network field

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html

feat (container): add publish all ports option (#558)

---

app/app.js
bower.json
gruntfile.js
package.json

This adds Google Analytics inside the app. The tracking ID is only added when creating a release (to avoid recording stats during development).
It sends a page view event upon change state.
Close #598

feat(project): add google analytics in app

---

app/components/containers/containersController.js
app/services/entityListService.js

Hello,
It solves #151
Cheers
Romain

feat (container): remember selection when refreshing a list view (#151)

---

app/models/template.js
app/services/templateService.js

 #643 feat(templates): add privileged flag to templates

---

app/app.js

fix(app): use lodash startsWith method instead of ECMAScript 2015 one

---

app/components/swarm/swarm.html
app/components/swarm/swarmController.js

fix(swarm): fix an issue when trying to access node view

---

api/bolt/datastore.go

feat(backend): check for the full database path to verify its existence

---

assets/css/app.css

fix(sidebar): fix a display issue on low resolution

---

app/components/templates/templatesController.js

fix(templates): fix an issue where container links would fail

---

README.md

Updated public demo username to admin, misspelled it first time, closed the original request.

Updated public demo username to admin

---

app/components/image/image.html
app/components/image/imageController.js
app/components/images/imagesController.js
app/components/templates/templatesController.js
app/models/imageDetails.js
app/services/imageService.js
app/services/messages.js
app/services/templateService.js

This PR refactors the following controllers:
* ImageController
* ImagesController
They're now using the ImageService as the single interface to manage images. A new model for the image-details section has been created.

refactor(image): refactor the code used in image and image details controller

---

api/http/docker_handler.go

fix(backend): use a thread-safe implementation of map for proxies

---

app/components/services/services.html
app/components/services/servicesController.js
app/helpers/nodeHelper.js
app/models/service.js

#689 - feat(services) - add exposed ports

---

app/components/services/services.html

style(services): update empty service list text alignment

---

app/models/service.js

Closes #739
Get real exposed ports (Endpoint) instead of Spec

#739 - fix(services) - Fix exposed ports

---

app/components/templates/templatesController.js
app/services/networkService.js

#641 feat(templates): add swarm attachable networks

---

app/components/createService/createservice.html

fix(service-creation): fix invalid mount specs

---

app/components/createNetwork/createnetwork.html

fix(network-creation): fix internal network switch

---

app/components/service/serviceController.js

fix(service-details): display spinner when updating the service

---

app/components/service/serviceController.js

fix(service-details): fix an update issue when no ports are defined

---

app/components/endpointInit/endpointInit.html
app/components/endpointInit/endpointInitController.js
app/services/endpointService.js

fix(endpoint-init): fix an issue when connecting to a remote TLS endpoint

---

api/http/docker_handler.go
api/http/endpoint_handler.go
api/http/proxy.go
api/http/server.go
api/portainer.go
app/components/endpoint/endpointController.js
app/services/endpointService.js
app/services/fileUpload.js

fix(endpoints): add the ability to update TLS for an existing endpoint

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html

Implements the feature request [#515](https://github.com/portainer/portainer/issues/515) after merge [#715](https://github.com/portainer/portainer/pull/715)

Feat515-rebase715-device-option

---

app/components/container/container.html
app/components/container/containerController.js
app/components/containers/containers.html
app/components/containers/containersController.js
app/components/service/serviceController.js
app/components/services/servicesController.js
app/components/user/userController.js
app/components/users/usersController.js
app/rest/container.js
app/services/modalService.js

#354 - feat(containers) - Allow force remove with confirm

---

app/components/container/container.html
app/components/container/containerController.js
app/filters/filters.js

fixes #672 
Now we can see created date for all containers
And this show `created since` for created containers

 #672 - fix(container) - correct since for created containers

---

app/components/container/containerController.js
app/components/containers/containersController.js
app/rest/container.js
app/services/modalService.js
assets/css/app.css
bower.json

WIP
fixes #808
TODO : 
I open this PR to discuss how to manage the modal
Here I just use a bootbox prompt with a checkbox form
I just change the container view, I'll adapt containers view after discuss
Screenshot :

WIP : #808 - feat(containers) - clean associated volumes when remove container

---

api/http/endpoint_handler.go
api/portainer.go
app/components/containers/containers.html
app/components/containers/containersController.js
app/components/endpoint/endpoint.html
app/components/endpoint/endpointController.js
app/components/endpointInit/endpointInitController.js
app/components/endpoints/endpoints.html
app/components/endpoints/endpointsController.js
app/components/sidebar/sidebarController.js
app/models/container.js
app/services/endpointProvider.js
app/services/endpointService.js
app/services/localStorage.js

fixes #799
This PR add a new optional parameter to remote endpoints : URLPublish
If not set, will take value of endpoint IP/url
Next, this parameter is used in containers view to link to exposed services
TODO :

#799 - feat(endpoint) - Add URLPublish param to endpoint

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/service/includes/ports.html
app/components/service/serviceController.js

Adds the ability to specify the publish mode for ports during service create and service update. Default value is ingress.
This PR closes #811.

#811 feat(service): ability to publish ports using host mode

---

app/components/createService/createServiceController.js
app/components/service/serviceController.js

 Fix empty environment variables are not maintained

---

app/components/sidebar/sidebarController.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/directives/template-widget.js
app/helpers/templateHelper.js
app/models/template.js
app/models/templateLinuxServer.js
app/services/templateService.js
assets/css/app.css
gruntfile.js

This PR changes the layout of the templates view and introduces support to filter templates by platform and category.
Documentation for the new fields must be added.
Close #272 
Related to #273

feat(templates): new templates capabilities

---

app/components/container/container.html

fix(container-details): fix an issue with duplicate env var

---

app/app.js
gruntfile.js
package.json

Disable Angular debug information during the release process.
Close #851

feat(app): disable Angular debug information

---

build.sh
gruntfile.js

chore(build-system): add support for ppc64le architecture

---

build.sh
gruntfile.js

chore(build-system): add support for linux 386 architecture

---

app/components/image/imageController.js
app/helpers/imageHelper.js
app/services/imageService.js

fix(image-details): fix the ability to pull an image from a tag

---

app/components/image/image.html
app/components/image/imageController.js
app/models/imageDetails.js

fix(image-details): fix invalid CMD with images using HEALTHCHECK

---

app/components/createService/createServiceController.js

#880 - fix(createService) - bind mount

---

app/components/task/task.html

Fix https://github.com/portainer/portainer/issues/888
Signed-off-by: Renno Reinurm rreinurm@gmail.com

#888 Show state message in Task Details

---

app/models/api/template.js
app/models/api/templateLinuxServer.js
app/services/templateService.js

feat(templates): add support for a restart_policy field

---

api/errors.go
api/http/handler/file.go

fix(api): add restrictions for the files served by the API

---

app/components/container/containerController.js

fix(container-details): fix an issue when renaming a container

---

app/components/createContainer/createContainerController.js
app/services/docker/imageService.js

fix(container-creation): ignore error when pulling an image

---

app/components/service/includes/tasks.html
app/components/service/serviceController.js

fix(service-details): fix the ability to sort tasks

---

app/components/users/usersController.js

Fix #925.
I am an absolute angularjs beginner, so please verify twice if this doesn't break anything...
Cheers.

#925 fix(users): sanitize username and password when user is created

---

app/models/api/template.js

fix(templates): display templates without platform

---

app/components/endpoint/endpoint.html
app/components/endpoints/endpoints.html
app/components/endpoints/endpointsController.js

feat(endpoint): remove the active endpoint edition restriction

---

app/components/container/container.html
app/components/container/containerController.js

submitting a PR for item #848, via northshore networks
Close #848

#848 feat(container-details): add section to join networks

---

app/components/volumes/volumes.html

feat(volumes): display mount point for each volume

---

app/components/endpoints/endpoints.html
app/components/registries/registries.html

feat(endpoints): update information message

---

app/components/containerConsole/containerConsole.html
app/components/containerConsole/containerConsoleController.js
app/directives/tooltip.js
assets/css/app.css

If a username isn't provided command will be executed with a default user.
In case if a username is invalid error message will appear in the terminal.
Known issue: with invalid username error popup appear with an error on terminal resizing.
Fixes #890

#890 feat(container-console): add ability to enter user

---

app/components/container/containerController.js

fix(container-details): fix the ability to commit a container

---

app/services/docker/secretService.js

fix(secrets): fix an issue when removing a secret that is in use

---

app/components/containerConsole/containerConsole.html
app/components/containerConsole/containerConsoleController.js

Form looks as @deviantony described in https://github.com/portainer/portainer/pull/563#issuecomment-313915717
Implements #259 and closes #563

feat(console): allow the user to specify a command in the console section (#259)

---

app/components/containerConsole/containerConsoleController.js
bower.json

Update the xtermjs version to the latest, fixing some issues when using the container console.

chore(deps): update xtermjs version

---

app/directives/accessManagement/porAccessManagementController.js

fix(access): fix an issue where an access would disappear

---

app/components/container/container.html

feat(container-details): show container ID

---

app/components/sidebar/sidebarController.js

feat(sidebar): sort available endpoints alphabetically

---

app/components/volumes/volumes.html
app/filters/filters.js

feat(volumes): new truncate method for volume paths

---

app/components/containerConsole/containerConsole.html
app/components/containerConsole/containerConsoleController.js
app/services/docker/containerService.js
app/services/docker/execService.js

This PR changes the displayed error notification upon error. It also changes the message displayed after hitting the connect button to show the user and command used.

feat(container-console): improve container console UX

---

app/rest/docker/system.js

fix(images): fix the system/df call to display unused images

---

app/filters/filters.js

Fix #1023 
Available via `portainer/portainer:pr1048`

fix(containers): add support for the 'dead' status

---

app/components/volumes/volumes.html

#1051 style(volumes): replace label 'Dangling' with 'Unused'

---

app/components/images/images.html
app/components/images/imagesController.js

fix(images): show image usage only if endpoint API version >= 1.25

---

app/rest/docker/containerLogs.js
app/rest/docker/containerTop.js
app/rest/docker/serviceLogs.js

fix(rest): fix an issue with rest factories using $http

---

api/http/handler/templates.go

feat(templates): update LinuxServer.io templates feed URL

---

app/components/containerConsole/containerConsoleController.js
vendor.yml

I'm not sure about the window.onresize call, but let me know if anything needs to be improved!
Fix #932

fix(container-console) fix an issue with scrollbar (#932)

---

app/components/container/container.html

fix(container): connected network section disappearing (#1091)

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/service/includes/updateconfig.html
app/components/service/serviceController.js
app/models/docker/service.js

This PR introduces support for the Order field in a service update configuration.
Fix #1096 
Close #1100

feat(service): support the Order field for Update Configuration

---

app/components/team/team.html
app/components/teams/teams.html

fix(team-details): fix an issue when sorting columns

---

api/swagger.yaml

Add a section about how to execute Docker requests.

docs(api): update swagger.yml

---

app/components/auth/authController.js

fix(authentication): do not use $sanitize with LDAP authentication

---

app/components/dashboard/dashboard.html

feat(dashboard): remove driver information in volumes

---

app/components/templates/templates.html
app/models/api/template.js

Deprecation Warning:
Template Volumes:
Close #777

#777 feat(templates): add support for binding to host path

---

api/cmd/portainer/main.go

feat(api): display version in startup logs

---

app/components/createNetwork/createNetworkController.js
app/components/createNetwork/createnetwork.html
app/services/docker/pluginService.js

feat(network): network dropdown for drivers (#1016)

---

app/components/swarmVisualizer/swarmVisualizer.html
assets/css/app.css

This PR adds an icon representing the platform of the node next to the node name.

feat(swarm-visualizer): add a platform icon next to node name

---

api/http/proxy/socket.go

feat(api): write Docker response code when using local proxy

---

app/components/sidebar/sidebar.html

feat(sidebar): restrict access to Events for administrators only

---

api/http/handler/resource_control.go
api/http/proxy/decorator.go
api/http/proxy/filter.go
api/http/proxy/networks.go
api/http/proxy/transport.go
api/portainer.go
app/components/createNetwork/createNetworkController.js
app/components/createNetwork/createnetwork.html
app/components/network/network.html
app/components/network/networkController.js
app/components/networks/networks.html
app/components/networks/networksController.js
app/models/docker/network.js
app/services/docker/networkService.js
app/services/notifications.js

Introduces UAC for networks.
Close #1194

feat(networks): add UAC

---

app/components/containers/containersController.js
app/services/localStorage.js

feat(containers): store show all filter value in a cookie

---

api/http/proxy/filter.go
api/http/proxy/tasks.go
api/http/proxy/transport.go

feat(api): filter tasks based on service UAC

---

app/services/notifications.js

feat(notifications): do not display invalid JWT token notifications

---

app/app.js
app/components/engine/engine.html
app/components/engine/engineController.js
app/components/sidebar/sidebar.html

feat(sidebar): rename Docker to Engine

---

api/ldap/ldap.go

fix(ldap): prevent panic if search error arise

---

app/components/auth/authController.js
app/components/container/containerController.js
app/components/containerConsole/containerConsoleController.js
app/components/containerLogs/containerLogsController.js
app/components/containerStats/containerStatsController.js
app/components/createContainer/createContainerController.js
app/components/endpoint/endpointController.js
app/components/endpointAccess/endpointAccessController.js
app/components/image/imageController.js
app/components/network/networkController.js
app/components/node/nodeController.js
app/components/registry/registryController.js
app/components/registryAccess/registryAccessController.js
app/components/secret/secretController.js
app/components/secrets/secretsController.js
app/components/service/serviceController.js
app/components/serviceLogs/serviceLogsController.js
app/components/services/servicesController.js
app/components/task/taskController.js
app/components/team/teamController.js
app/components/templates/templatesController.js
app/components/user/userController.js
app/components/volume/volumeController.js
app/routes.js
bower.json

This PR upgrades the version of https://github.com/angular-ui/ui-router and remove the deprecated usage `$stateParams`.

refactor(app): upgrade to the latest version of ui-router

---

api/crypto/tls.go

fix(tls): fix an issue with TLSConfig ignored when using LDAP StartTLS

---

app/components/endpoint/endpointController.js

fix(endpoint-details): fix an issue when updating the local endpoint

---

app/components/userSettings/userSettings.html
app/components/userSettings/userSettingsController.js

fix(userSettings): allow to change admin password when using LDAP auth

---

assets/css/app.css

Update the font-size of task to 10px.

style(swarm-visualizer): update font-size

---

api/cli/cli.go
api/cmd/portainer/main.go
api/file/file.go
api/portainer.go

feat(cli): Allow adding admin password using docker secrets (#1199)

---

api/bolt/migrate_dbversion4.go
api/bolt/migrator.go
api/cmd/portainer/main.go
api/http/handler/settings.go
api/portainer.go
app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html
app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/settings/settings.html
app/components/settings/settingsController.js
app/components/templates/templates.html
app/components/templates/templatesController.js
app/models/api/settings/settings.js
gruntfile.js

feat(settings): add a setting to disable bind mounts for non-admins

---

api/bolt/migrate_dbversion5.go
api/bolt/migrator.go
api/cmd/portainer/main.go
api/http/handler/settings.go
api/portainer.go
app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html
app/components/settings/settings.html
app/components/settings/settingsController.js
app/models/api/settings/settings.js

feat(settings): add a setting to disable privileged mode for non-admins

---

app/components/containerStats/containerStats.html
app/components/containerStats/containerStatsController.js

fix(container-stats): adapt stats view when networks stats unavailable

---

app/components/createContainer/createContainerController.js
app/components/createContainer/createcontainer.html
app/components/createService/createServiceController.js
app/components/createService/includes/resources-placement.html
app/directives/slider/porSliderController.js

Closes #1040 
This PR add resource management for createContainer
This add 3 fields : 
- Cpu Limit
- Memory Limit
- Memory Reservation

feat(container) - Add container resource management

---

app/models/docker/container.js

fix(templates): add missing NetworkSettings field

---

app/components/settingsAuthentication/settingsAuthentication.html

#1117 style(authentication/ldap) replace LDAP URL label

---

app/components/endpoints/endpointsController.js

#1171 prevent specification of protocol in Endpoints Url

---

build.sh

s390x works, too -- keep in parallel with other Linux architectures.

Add linux-s390x

---

app/components/swarm/swarm.html

Reverts portainer/portainer#1320

Revert "Use isAdmin only if authentication is enabled"

---

app/components/network/networkController.js

fix(network-details): fix an issue caused by stopped containers

---

assets/css/app.css

style(sidebar): automatically adjust sidebar font-size based on height

---

assets/ico/browserconfig.xml
assets/ico/manifest.json
index.html

fix(ico) make URLs for favicons relative (fix #1342)

---

api/exec/stack_manager.go
api/http/handler/stack.go
api/portainer.go
app/components/createStack/createStackController.js
app/components/createStack/createstack.html
app/components/stack/stack.html
app/components/stack/stackController.js
app/helpers/formHelper.js
app/models/api/stack.js
app/services/api/stackService.js
app/services/fileUpload.js

This PR adds the ability to specify environment variables when deploying/updating a stack.

feat(stacks): add the ability to specify env vars when deploying stacks

---

app/components/services/servicesController.js
app/models/docker/service.js

feat(services) - Fix count for global services

---

app/components/createContainer/createcontainer.html
app/components/createService/createservice.html
app/directives/imageRegistry/por-image-registry.js
app/directives/imageRegistry/porImageRegistry.html
app/directives/imageRegistry/porImageRegistryController.js

Enable image name suggestion when creating a container or a service. Solves #169

Give the ability to select an image in Portainer when creating containers and services

---

app/components/createContainer/createcontainer.html
app/components/createService/createservice.html
app/directives/imageRegistry/por-image-registry.js
app/directives/imageRegistry/porImageRegistry.html
app/directives/imageRegistry/porImageRegistryController.js

Reverts portainer/portainer#1355

revert(images): revert image autocompletion

---

app/components/createConfig/createConfigController.js
app/components/createContainer/createContainerController.js
app/components/createNetwork/createNetworkController.js
app/components/createSecret/createSecretController.js
app/components/createService/createServiceController.js
app/components/createStack/createStackController.js
app/components/createVolume/createVolumeController.js
app/components/templates/templatesController.js

Encountered some code where there is an unecessary if statement. Removed it in all locations this was used.

refactor(webapp): simplify isAdmin statement

---

app/components/createContainer/createcontainer.html
app/components/createService/createservice.html
app/components/service/service.html
app/components/service/serviceController.js
app/directives/imageRegistry/por-image-registry.js
app/directives/imageRegistry/porImageRegistry.html
app/directives/imageRegistry/porImageRegistryController.js
app/services/docker/imageService.js

Auto complete feature for images when creating services and containers

---

app/components/configs/configs.html
app/components/containers/containers.html
app/components/endpoints/endpoints.html
app/components/images/images.html
app/components/networks/networks.html
app/components/registries/registries.html
app/components/services/services.html
app/components/stacks/stacks.html
app/components/teams/teams.html
app/components/users/users.html
app/components/volumes/volumes.html

feat(tables) change background color for selected items

---

assets/css/app.css

style(sidebar): prevent icon of active item moving on hover

---

app/components/createService/createServiceController.js
app/components/createService/createservice.html
app/components/service/includes/restart.html
app/components/service/includes/updateconfig.html
app/components/service/serviceController.js
app/models/docker/service.js

#1378 service restart policy

---

app/services/chartService.js
app/services/docker/pluginService.js
assets/css/app.css

This PR [fixes](https://codeclimate.com/github/portainer/portainer/pull/1340#ratings) three files currently graded `F` at codeclimate. It also fixes compatility issues in `app.css`.

refactor(quality-f) Hopefully improve 'F' graded files

---

api/http/handler/handler.go

fix(stacks): fix an issue with stacks using docker in their name

---

app/components/dashboard/dashboard.html

feat(dashboard): add a link to the visualizer

---

app/components/container/container.html
app/components/container/containerController.js

feat(container-details): display loading when using recreate

---

app/directives/ui/datatables/networks-datatable/networksDatatable.html

#1494 fix(networks): fix the label of the add button

---

app/directives/ui/datatables/containers-datatable/containersDatatableController.js

fix(containers): fix the ability to stop/pause a healthy container

---

app/components/containerLogs/containerLogsController.js

fix(container-logs): add missing dependency to Notifications

---

app/components/users/users.html
app/directives/ui/datatables/users-datatable/usersDatatable.html
app/directives/ui/datatables/users-datatable/usersDatatable.js

fix(users): fix invalid Authentication value

---

app/directives/ui/datatables/containers-datatable/containersDatatable.html
app/filters/filters.js

fix(containers) display a subset of the sha images name in the containers datatable fixes #1509

#1509 Display a subset of the sha image names in containers

---

codefresh.yml

Update the commands used in the build_frontend step after merging #1416 
Issue reported in #1540

chore(codefresh): fix the build_frontend step

---

app/filters/filters.js

feat(containers): trim the @sha256 suffix in the image name

---

app/models/docker/container.js
app/models/docker/network.js
app/models/docker/volume.js

fix(UAC): fix an issue with network/volume ownership update

---

app/models/api/stack.js

fix(stack-details): fix an issue related to env vars

---

app/components/service/serviceController.js

bug(service) - Edit fail with no endpoint spec

---

app/components/templates/templates.html
app/components/templates/templatesController.js
app/helpers/templateHelper.js
app/models/api/template.js
app/services/templateService.js

Adds "labels" under section "Show advanced options"
Close #646

feat(templates): add labels to container template

---

api/swagger.yaml

This PR documents how to manage Docker stacks using the Portainer API.

docs(api): document the stack management endpoint

---

app/directives/autofocus.js
app/directives/onEnterKey.js
app/directives/ui/datatables/services-datatable/servicesDatatable.html

feat(services): bind enter key when scaling a service

---

app/directives/ui/datatables/stack-services-datatable/stackServicesDatatable.js

fix(stack-details): fix broken link for services published ports

---

app/extensions/storidge/rest/cluster.js
app/extensions/storidge/services/clusterService.js
app/extensions/storidge/views/cluster/cluster.html
app/extensions/storidge/views/cluster/clusterController.js

Add the ability to shutdown a Storidge cluster.

extension(storidge): support cluster shutdown

---

app/services/stateManager.js

fix(state): ensure API version >= 1.25 before extension check

---

api/cli/cli.go
api/portainer.go

refactor(api): remove CLI deprecation related code

---

app/components/container/container.html

"Running since xx minutes" => "Running for xx minutes"
Fixes #1617.
I'm still relatively new to portainer, but it's a very useful tool, so I'd like to help. Feel free to shoot this down if this has other effects I'm not familiar with.

Typo Fix in Container Status

---

app/components/container/container.html

Reverts portainer/portainer#1618

Revert "Typo Fix in Container Status"

---

app/portainer/services/codeMirror.js

fix(config-creation): fix an issue setting config editor as read-only

---

app/docker/components/datatables/configs-datatable/configsDatatable.html
app/docker/components/datatables/container-processes-datatable/containerProcessesDatatable.html
app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/events-datatable/eventsDatatable.html
app/docker/components/datatables/images-datatable/imagesDatatable.html
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/components/datatables/node-tasks-datatable/nodeTasksDatatable.html
app/docker/components/datatables/nodes-datatable/nodesDatatable.html
app/docker/components/datatables/nodes-ss-datatable/nodesSSDatatable.html
app/docker/components/datatables/secrets-datatable/secretsDatatable.html
app/docker/components/datatables/services-datatable/servicesDatatable.html
app/docker/components/datatables/tasks-datatable/tasksDatatable.html
app/docker/components/datatables/volumes-datatable/volumesDatatable.html
app/extensions/storidge/components/cluster-events-datatable/storidgeClusterEventsDatatable.html
app/extensions/storidge/components/nodes-datatable/storidgeNodesDatatable.html
app/extensions/storidge/components/profiles-datatable/storidgeProfilesDatatable.html
app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
app/portainer/components/datatables/registries-datatable/registriesDatatable.html
app/portainer/components/datatables/stack-services-datatable/stackServicesDatatable.html
app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
app/portainer/components/datatables/teams-datatable/teamsDatatable.html
app/portainer/components/datatables/users-datatable/usersDatatable.html

This PR introduces an automatic focus on the search input when clicking on the search button in any datatable.
Partially solves #1621

feat(ux): enable auto-focus on search field

---

api/exec/stack_manager.go
api/http/handler/stack.go
api/portainer.go

fix(api): ignore Docker login errors during stack deployment

---

app/docker/components/datatables/containers-datatable/containersDatatable.html

Hi, I added title attributes within the links of the quick actions.

#1652 style(containers): update quick actions tooltips messages

---

app/docker/components/datatables/services-datatable/servicesDatatable.html
app/docker/components/datatables/services-datatable/servicesDatatable.js
app/docker/helpers/nodeHelper.js
app/docker/views/services/services.html
app/docker/views/services/servicesController.js

fix(services): use the Public URL instead of a manager IP

---

app/docker/filters/filters.js

style(containers): update label color for unhealthy containers

---

api/http/security/bouncer.go
api/http/server.go

feat(security): check user existence for each protected requests

---

app/docker/filters/filters.js
app/docker/views/swarm/visualizer/swarmVisualizerController.js
app/docker/views/swarm/visualizer/swarmvisualizer.html

A bit of refactor following #1683

refactor(swarm-visualizer): move task border logic to a filter

---

app/portainer/views/registries/edit/registry.html
app/portainer/views/registries/edit/registryController.js
app/portainer/views/registries/registries.html
app/portainer/views/registries/registriesController.js

feat(registries): remove actual password from registry password input

---

app/config.js
app/docker/views/containers/console/containerConsoleController.js
package.json
yarn.lock

refactor(xterm): update xtermjs to latest version

---

app/docker/views/services/logs/servicelogs.html

This PR fix services log view un-clickable breadcrumb link.

fix(services): fix services log view breadcrumb link

---

api/http/handler/extensions.go

refactor(extensions): review bouncer settings for extensions endpoint

---

gruntfile.js

Fix an issue with the release process after the merge of #1712

fix(build-system): fix task order after fontawesome5 integration

---

api/filesystem/filesystem.go

fix(api): ignore directory existence check and use os.MkdirAll

---

app/docker/components/datatables/configs-datatable/configsDatatable.html
app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/nodes-datatable/nodesDatatable.html
app/docker/components/datatables/services-datatable/servicesDatatable.html
app/docker/components/datatables/tasks-datatable/tasksDatatable.html
app/docker/components/dockerSidebarContent/dockerSidebarContent.html
app/docker/views/containers/edit/container.html
app/docker/views/containers/inspect/containerinspect.html
app/docker/views/images/build/buildimage.html
app/docker/views/images/edit/image.html
app/docker/views/services/edit/service.html
app/docker/views/stacks/create/createstack.html
app/docker/views/tasks/edit/task.html
app/portainer/components/datatables/users-datatable/usersDatatable.html
app/portainer/components/header-title.js
app/portainer/views/about/about.html
vendor.yml

This PR drops the usage of regular Font Awesome icons for solid icons.
Also fix an incorrect icon in the stack creation view.

style(app): update icon style

---

app/portainer/views/init/admin/initAdminController.js
gruntfile.js

Fix an issue where the Storidge extension would not be available post admin user init.

fix(extensions): init endpoint extensions after admin user creation

---

app/docker/views/templates/templatesController.js

fix(templates): fix app templates stack deployment

---

api/http/handler/dockerhub.go
api/http/handler/registry.go
api/http/proxy/factory.go
api/http/proxy/manager.go
api/http/proxy/registry.go
api/http/proxy/transport.go
api/http/security/authorization.go
api/http/security/filter.go
api/http/server.go
api/portainer.go
app/portainer/services/api/registryService.js

fix(api): manage registry authentication in the API

---

app/docker/views/services/edit/includes/mounts.html
app/docker/views/services/edit/serviceController.js

fix(service-details): prevent regular users from using bind mounts

---

api/swagger.yaml

docs(api): add missing supported resource control types

---

app/config.js

I force to remove charset from content-type of post/put/patch request in agular.
Related to https://github.com/portainer/portainer/issues/1785

Force to remove charset from content-type of post/put/patch.

---

gruntfile.js

chore(docker): upgrade Docker CLI version

---

api/swagger.yaml

docs(api): update resource control creation docs

---

api/swagger.yaml

docs(api): update endpoint creation documentation

---

app/portainer/components/accessControlPanel/porAccessControlPanel.html

fix(access-control): fix access control panel layout

---

app/portainer/views/settings/settings.html

Also add ability to submit form by pressing "Enter" key
Closes #1860

feat(settings): allow hide container with label with no value (#1860)

---

.codefresh/codefresh_develop.yml
.codefresh/codefresh_pullrequest.yml
codefresh.yml

Update codefresh pipelines

---

app/docker/views/containers/edit/container.html

Switching container port mapping around to match docker, closes #1871

Switching container port mapping around.

---

app/docker/components/datatables/tasks-datatable/tasksDatatable.html
app/docker/helpers/serviceHelper.js
app/docker/views/services/edit/includes/tasks.html
app/docker/views/services/edit/serviceController.js
app/docker/views/stacks/edit/stack.html
app/docker/views/stacks/edit/stackController.js

feat(tasks): change task name format in tasks datatable

---

app/portainer/views/sidebar/sidebar.html
app/portainer/views/sidebar/sidebarController.js
assets/css/app.css

This PR introduce a new text color for the selected endpoint and also sorts alphabetically the available groups/endpoints in the endpoint selector.

feat(sidebar): update endpoint selection UX

---

api/http/handler/websocket.go

fix(websocket): copy Host header during websocket request proxy

---

app/docker/components/datatables/tasks-datatable/tasksDatatable.html
app/docker/helpers/serviceHelper.js

fix(tasks): fix an issue when filtering tasks

---

app/docker/components/log-viewer/log-viewer.js
app/docker/components/log-viewer/logViewer.html
app/docker/views/containers/logs/containerlogs.html
app/docker/views/services/logs/servicelogs.html
app/docker/views/tasks/logs/tasklogs.html

Add lines field in container/service/task logs viewer
Close #1894

#1894 Add lines field in container logs viewer

---

app/docker/components/datatables/services-datatable/servicesDatatable.html
app/portainer/components/datatables/stack-services-datatable/stackServicesDatatable.html

feat(service): automatically focus replica input after clicking on scale

---

api/cmd/portainer/main.go
api/http/handler/settings.go
api/portainer.go
api/swagger.yaml
app/portainer/__module.js
app/portainer/components/header-title.js
app/portainer/models/settings/settings.js
app/portainer/services/stateManager.js
app/portainer/views/about/about.html
app/portainer/views/settings/settings.html
app/portainer/views/settings/settingsController.js
app/portainer/views/support/support.html

Adds a new view to display support options.

feat(support): add support view

---

api/http/handler/endpoint.go
api/http/proxy/factory.go
app/azure/components/azure-endpoint-config/azure-endpoint-config.js
app/azure/components/azure-endpoint-config/azureEndpointConfig.html
app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
app/portainer/components/endpoint-selector/endpointSelector.html
app/portainer/filters/filters.js
app/portainer/services/api/endpointService.js
app/portainer/views/endpoints/edit/endpoint.html
app/portainer/views/endpoints/edit/endpointController.js

This PR brings some UX enhancements regarding endpoints:
* Add details about endpoint type in the endpoint list
* Add the ability to inspect/update an Azure ACI endpoint 
* Disable the ability to click on the placeholder in the endpoint selector
Related to #1936

feat(endpoints): UX enhancements

---

app/docker/views/dashboard/dashboard.html

Displays information about the agent setup when connected to a Swarm manager.

feat(dashboard): update dashboard info

---

app/docker/components/datatables/containers-datatable/containersDatatable.html

feat(containers): add a tooltip with full container name on hover

---

app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/containers-datatable/containersDatatableController.js

feat(containers): do not remember selected items

---

api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/create_swarm_stack.go

fix(stack-creation): use numeric value for stack root folder name

---

app/docker/components/imageRegistry/porImageRegistry.html
app/extensions/storidge/views/profiles/create/createprofile.html
app/extensions/storidge/views/profiles/edit/profile.html
app/portainer/components/forms/group-form/groupForm.html
app/portainer/components/forms/template-form/templateForm.html
app/portainer/views/endpoints/create/createendpoint.html
app/portainer/views/tags/tags.html
app/portainer/views/tags/tagsController.js
app/portainer/views/teams/teams.html
app/portainer/views/teams/teamsController.js
assets/css/app.css

Update form validation warning message color.
Bind the enter key to submit for tag creation and team creation forms.

feat(ux): update form input validation

---

app/docker/components/datatables/containers-datatable/actions/containersDatatableActionsController.js

fix(containers): fix an issue when removing a container with agent proxy

---

app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.html
app/docker/components/datatables/configs-datatable/configsDatatable.html
app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.html
app/docker/components/datatables/container-processes-datatable/containerProcessesDatatable.html
app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/events-datatable/eventsDatatable.html
app/docker/components/datatables/images-datatable/imagesDatatable.html
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/components/datatables/node-tasks-datatable/nodeTasksDatatable.html
app/docker/components/datatables/nodes-datatable/nodesDatatable.html
app/docker/components/datatables/secrets-datatable/secretsDatatable.html
app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatable.html
app/docker/components/datatables/services-datatable/servicesDatatable.html
app/docker/components/datatables/tasks-datatable/tasksDatatable.html
app/docker/components/datatables/volumes-datatable/volumesDatatable.html
app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
app/portainer/components/datatables/endpoints-snapshot-datatable/endpointsSnapshotDatatable.html
app/portainer/components/datatables/groups-datatable/groupsDatatable.html
app/portainer/components/datatables/registries-datatable/registriesDatatable.html
app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
app/portainer/components/datatables/tags-datatable/tagsDatatable.html
app/portainer/components/datatables/teams-datatable/teamsDatatable.html
app/portainer/components/datatables/users-datatable/usersDatatable.html
assets/css/app.css

Fix #1920 .
Bug introduced by PR #1770 .
Replaces PR #1923 in a generic way.

fix(style): wrap long text in tables cells (#1920)

---

app/docker/helpers/infoHelper.js
app/docker/views/containers/containers.html
app/docker/views/containers/create/createcontainer.html
app/docker/views/dashboard/dashboard.html
app/docker/views/images/build/buildimage.html
app/docker/views/images/images.html
app/docker/views/networks/create/createnetwork.html
app/docker/views/networks/networks.html
app/docker/views/volumes/create/createvolume.html
app/docker/views/volumes/volumes.html
app/portainer/views/stacks/edit/stack.html

This PR introduces support to connect Portainer to an agent deployed on a standalone engine.

feat(agent): support agent deployed on standalone engine endpoint

---

api/libcompose/compose_stack.go

fix(libcompose): fix an issue with TLS enabled endpoints

---

api/git/git.go
api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/create_swarm_stack.go
api/http/handler/stacks/git.go
api/portainer.go
api/swagger.yaml
app/portainer/services/api/stackService.js
app/portainer/views/stacks/create/createStackController.js
app/portainer/views/stacks/create/createstack.html

I added reference support for stack deploy.
Closes #1948

feat(stack-creation): add the ability to specify git reference (#1948)

---

api/http/handler/endpoints/endpoint_inspect.go
api/http/handler/endpoints/handler.go
api/swagger.yaml
app/docker/filters/filters.js
app/docker/views/dashboard/dashboard.html
app/docker/views/dashboard/dashboardController.js

This PR adds more info to the endpoint dashboard (tags, URL).

style(dashboard): update dashboard information

---

build.sh
gruntfile.js

fix(build-system): fix invalid template copy step

---

app/portainer/views/auth/authController.js
app/portainer/views/sidebar/sidebarController.js

fix(authentication): fix an issue with the --no-auth flag

---

api/http/handler/endpoints/endpoint_list.go
api/http/handler/registries/registry_list.go
api/http/handler/users/user_list.go

fix(api): filter sensitive information from API response

---

build/windows2016/nanoserver/Dockerfile

chore(windows): added own dockerfile for srv 2016

---

app/docker/views/containers/edit/container.html

add the image name to the container details in addition to the sha 
Closes #1369

feat(container-details)

---

api/cmd/portainer/main.go
api/http/handler/settings/settings_public.go
api/http/handler/settings/settings_update.go
api/http/handler/templates/handler.go
api/http/handler/templates/template_list.go
api/http/server.go
api/portainer.go
app/portainer/models/settings.js
app/portainer/views/settings/settings.html
app/portainer/views/settings/settingsController.js
app/portainer/views/templates/templates.html
app/portainer/views/templates/templatesController.js

feat(templates): re-introduce external template management

---

app/docker/components/volumesNFSForm/volumes-nfs-form.js
app/docker/components/volumesNFSForm/volumesNFSFormController.js
app/docker/components/volumesNFSForm/volumesNFSFormModel.js
app/docker/components/volumesNFSForm/volumesnfsForm.html
app/docker/views/volumes/create/createVolumeController.js
app/docker/views/volumes/create/createvolume.html

Adding possibility to use NFS with 'local' driver on volume creation.
Closes #2083

feat(volume-creation) : NFS volume creation (#2083)

---

app/docker/views/containers/edit/containerController.js

Change order of container recreation

---

api/docker/snapshot.go
app/docker/views/dashboard/dashboard.html
app/portainer/components/endpoint-list/endpoint-item/endpointItem.html

Show correct number of cpus and total memory for swarm

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

feat(containers): add runtime option in the container creation(#2162)

---

app/docker/components/container-restart-policy/container-restart-policy-controller.js
app/docker/components/container-restart-policy/container-restart-policy.html
app/docker/components/container-restart-policy/container-restart-policy.js
app/docker/rest/container.js
app/docker/services/containerService.js
app/docker/views/containers/edit/container.html
app/docker/views/containers/edit/containerController.js

Add option to update restart-policy for containers

---

app/docker/components/datatables/macvlan-nodes-datatable/macvlanNodesDatatable.html
app/docker/components/datatables/macvlan-nodes-datatable/macvlanNodesDatatable.js
app/docker/components/network-macvlan-form/network-macvlan-form.js
app/docker/components/network-macvlan-form/networkMacvlanForm.html
app/docker/components/network-macvlan-form/networkMacvlanFormController.js
app/docker/components/network-macvlan-form/networkMacvlanFormModel.js
app/docker/models/network.js
app/docker/views/networks/create/createNetworkController.js
app/docker/views/networks/create/createnetwork.html
assets/css/app.css

Adding the MACVLAN driver for network creation in Portainer.
Closes #2082 .

feat(network-creation): macvlan driver for swarm mode (#2082)

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

This PR is making some order in the container-creation controller to help with #1261

Refactor container creation order

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/edit/containerController.js

feat(container-details): update re-creation flow

---

app/docker/__module.js
app/docker/components/datatables/configs-datatable/configsDatatable.html
app/docker/views/configs/create/createConfigController.js
app/docker/views/configs/create/createconfig.html
app/docker/views/configs/edit/config.html

Implement clone config feature. Cloned configs have '_Copy' suffix.
Closes #1911

#1911 feat(configs): implements clone config feature

---

api/http/handler/file/handler.go
api/http/security/bouncer.go
app/portainer/views/teams/teamsController.js

feat(security): update secured headers and sanitize team name

---

api/cmd/portainer/main.go

Re-add the CLI for external template management

Populate TemplatesURL from Command Line

---

api/cmd/portainer/main.go
app/docker/components/datatables/tasks-datatable/tasksDatatable.html

fix(service-details): disable auto-focus on task datatable

---

api/http/handler/endpoints/endpoint_create.go

fix(api): fix invalid error message in endpoint creation handler

---

api/docker/snapshotter.go

fix(snapshots): close Docker client after snapshot

---

app/docker/components/container-restart-policy/container-restart-policy-controller.js
app/docker/components/container-restart-policy/container-restart-policy.html
app/docker/views/containers/edit/container.html
app/docker/views/containers/edit/containerController.js

feat(container-details): update container-restart-policy component

---

gruntfile.js

feat(build-system): update shippedDockerVersion to 18.06.1-ce

---

app/portainer/views/endpoints/create/createEndpointController.js
app/portainer/views/endpoints/create/createendpoint.html

This PR adds an information message in the endpoint creation to give instructions on how to deploy the agent.

feat(endpoint-creation): add requirement message for agent endpoint

---

app/portainer/models/template.js
app/portainer/views/templates/edit/templateController.js

Enable selection of network on template creation

---

app/portainer/components/endpoint-list/endpoint-list-controller.js
app/portainer/components/endpoint-list/endpoint-list.js
app/portainer/components/endpoint-list/endpointList.html

Support searching into multiple endpoint fields in the home view

---

api/http/handler/file/handler.go
api/http/security/bouncer.go

 fix(rest): remove x frame option from rest headers

---

app/docker/views/swarm/visualizer/swarmvisualizer.html

- sorts the tasks on each node in alphabetical order to make it easier to track what has changed when it automatically refreshes
- Closes #1992

Sort tasks in alphabetical order on refresh

---

app/portainer/__module.js
app/portainer/components/datatables/stacks-datatable/stacksDatatable.html

fix(app): fix invalid state name

---

app/agent/rest/browse.js
app/agent/services/volumeBrowserService.js

Move volume id to query params

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

Closes #2314.
Let the docker daemon choose the correct value for runtime when default value for runtime is selected during container creation.

fix(containers): docker-runc

---

api/swagger.yaml

docs(swagger): update StackUpdateRequest model

---

app/portainer/views/init/admin/initAdminController.js

feat(ux): Redirect from init/admin to home when admin already exists

---

api/archive/tar.go
api/cmd/portainer/main.go
api/docker/client.go
api/docker/jobservice.go
api/http/handler/endpoints/endpoint_job.go
api/http/handler/endpoints/handler.go
api/http/proxy/build.go
api/http/server.go
api/portainer.go

Create job execution API

---

api/swagger.yaml

Related to https://github.com/portainer/portainer/pull/2361

docs(swagger): document the endpoint job execution

---

README.md

FIxed the build status on the README page.

Fixed the build status badge on the README page

---

app/docker/views/services/create/includes/config.html
app/docker/views/services/create/includes/secret.html
app/docker/views/services/edit/includes/configs.html
app/docker/views/services/edit/includes/secrets.html

fix(sorting): Alphabetically sort configs and secrets in service details select box

---

app/docker/models/container.js
app/docker/views/containers/stats/containerStatsController.js
app/portainer/services/chartService.js

Display cache in memory usage chart. fixes #2380

Display cache in memory usage chart

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

Add functionality to override default log driver when creating new containers.
Closes #2376

feat(containers): add logdriver configuration to container create view

---

app/docker/components/log-viewer/log-viewer.js
app/docker/components/log-viewer/logViewer.html
app/docker/components/log-viewer/logViewerController.js
app/docker/filters/filters.js
app/docker/services/containerService.js
app/docker/services/serviceService.js
app/docker/services/taskService.js
app/docker/views/containers/logs/containerLogsController.js
app/docker/views/containers/logs/containerlogs.html
app/docker/views/services/logs/serviceLogsController.js
app/docker/views/services/logs/servicelogs.html
app/docker/views/tasks/logs/taskLogsController.js
app/docker/views/tasks/logs/tasklogs.html

**Related to** : https://github.com/portainer/portainer/issues/1942#issuecomment-430246378

 chore(log-viewer): enhance the log-viewer with parameters `since` and `lineCount`

---

app/docker/components/container-quick-actions/containerQuickActions.html
app/docker/components/container-quick-actions/containerQuickActions.js
app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatable.html
app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatableController.js
app/docker/components/datatables/tasks-datatable/tasksDatatable.html
app/docker/components/datatables/tasks-datatable/tasksDatatable.js
app/docker/components/datatables/tasks-datatable/tasksDatatableController.js

feat(ux): normalize quick actions buttons

---

api/cmd/portainer/main.go
api/http/handler/schedules/schedule_create.go
api/portainer.go

feat(api): add created property for schedules

---

api/filesystem/filesystem.go
api/http/handler/schedules/handler.go
api/http/handler/schedules/schedule_create.go
api/http/handler/schedules/schedule_delete.go
api/http/handler/schedules/schedule_file.go
api/http/handler/schedules/schedule_update.go
api/portainer.go
app/portainer/components/forms/schedule-form/scheduleForm.html
app/portainer/models/schedule.js
app/portainer/rest/schedule.js
app/portainer/services/api/scheduleService.js
app/portainer/views/schedules/edit/schedule.html
app/portainer/views/schedules/edit/scheduleController.js

feat(schedules): add the ability to update a schedule script

---

app/docker/helpers/containerHelper.js

feat(containers): allow escaped quotes in command field

---

app/docker/models/container.js
app/docker/views/containers/stats/containerStatsController.js
app/portainer/services/chartService.js

Fixing the CPU and Memory charts on Windows containers

---

api/cron/job_snapshot.go
api/http/handler/endpoints/endpoint_snapshot.go

fix(endpoints): ensure endpoint is up to date after snapshot

---

api/http/handler/endpoints/endpoint_snapshot.go
api/http/handler/endpoints/endpoint_snapshots.go
api/http/handler/endpoints/handler.go
app/portainer/components/information-panel-offline/informationPanelOffline.html
app/portainer/components/information-panel-offline/informationPanelOffline.js
app/portainer/components/information-panel-offline/informationPanelOfflineController.js
app/portainer/rest/endpoint.js
app/portainer/services/api/endpointService.js
app/portainer/views/home/homeController.js

feat(endpoints): add the last snapshot timestamp in offline banner

---

api/http/handler/endpointproxy/proxy_docker.go
app/docker/interceptors/containersInterceptor.js
app/docker/interceptors/imagesInterceptor.js
app/docker/interceptors/infoInterceptor.js
app/docker/interceptors/networksInterceptor.js
app/docker/interceptors/versionInterceptor.js
app/docker/interceptors/volumesInterceptor.js
app/portainer/interceptors/endpointStatusInterceptor.js

Closes #2443 .
Fixes offline browsing performance issues.

fix2443: offline browsing performance

---

assets/css/app.css

Changing blocklist-item border color to more confortable color that makes UI look more consistence

style(dashboard): change blocklist-item border color

---

app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
app/portainer/components/endpoint-list/endpoint-list-controller.js
app/portainer/components/endpoint-list/endpointList.html
app/portainer/filters/filters.js

feat2469: add url to endpoints list

---

app/docker/models/container.js

fix2480: containers-stats js error

---

app/docker/views/dashboard/dashboard.html
app/portainer/components/endpoint-list/endpoint-item/endpointItem.html

Hopefully these changes should be adequate in order to fix the issue described in #2473.

fix2473: use plural form only when required

---

app/portainer/services/fileUpload.js

Uploading a tar with multiple images wont display an error anymore.

fix(images-upload): error on tar upload with multiple images inside

---

gruntfile.js

Bumps up Docker binary version to 18.09.0.

chore(docker): update docker binary version to 18.09.0

---

app/portainer/components/forms/template-form/template-form.js
app/portainer/views/templates/templatesController.js

Fix env vars sent with default values

---

api/cmd/portainer/main.go

Stop portainer instance after 5 minutes if no admin was created

---

api/bolt/migrator/migrate_dbversion15.go
api/bolt/migrator/migrator.go
api/portainer.go

fix(api): set a default value for potentially empty snapshot interval

---

app/portainer/components/endpoint-list/endpoint-item/endpointItem.html

fix(home): only display group name if available

---

app/app.js
app/config.js
app/docker/views/networks/create/createNetworkController.js
app/portainer/services/httpRequestHelper.js

fix(network-creation): force overlay network creation on manager node

---

app/portainer/interceptors/endpointStatusInterceptor.js
app/portainer/services/endpointProvider.js

Closes #2556 .
Removing a status update forgotten with PR #2454 .

fix2556: frequent offline mode

---

app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.html

Fix wrong network link in container view

---

app/docker/views/containers/create/createContainerController.js

Load container logger info in duplicate screen

---

app/docker/views/networks/edit/network.html

fix2598: displaying all subnets and gateways on network details

---

app/extensions/registry-management/views/repositories/edit/registryRepositoryController.js

When I remove all tags, removeTags() will reload and do initView() again, but data.tags response null, that trigger data.tags.length got error.

fix repository reload got error in remove tags

---

app/docker/views/containers/create/createContainerController.js

Revert state if create container failed

---

api/bolt/datastore.go
api/bolt/migrator/migrate_dbversion16.go
api/bolt/migrator/migrator.go
api/cmd/portainer/main.go
api/exec/extension.go
api/http/handler/extensions/extension_create.go
api/http/handler/extensions/extension_list.go
api/portainer.go
app/portainer/components/extension-list/extension-item/extensionItem.html
app/portainer/components/extension-list/extension-item/extensionItemController.js
app/portainer/components/product-list/product-item/productItem.html
app/portainer/views/extensions/inspect/extension.html

fix(extensions): fix an issue with extensions with expired licenses

---

app/portainer/views/endpoints/create/createendpoint.html

feat(endpoint-creation): fix invalid link

---

app/app.js
app/portainer/__module.js
app/portainer/views/auth/authController.js

Preserve url when redirected to login

---

build/build_binary.ps1
build/build_binary_devops.ps1
gruntfile.js

Reference: https://dev.azure.com/portainer/Portainer%20CI/_build/results?buildId=144

Fix to allow DevOps pipeline to leverage webpack

---

app/portainer/views/home/homeController.js

Fix an issue preventing the user to connect to an Azure ACI endpoint.

fix(home): fix an issue when trying to connect to an Azure ACI endpoint

---

gruntfile.js
package.json

feat(build-system): update build system

---

app/portainer/__module.js

fix(templates): redirect to home if endpoint not yet selected

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

Create container with Auto Remove option (docker run --rm)

Create container with Auto Remove option

---

app/app.js
app/portainer/__module.js
app/portainer/views/auth/authController.js

Rollbacks #2591 
Re-opens #724

fix(auth): rollback changes introduced via #2591

---

app/docker/components/datatables/volumes-datatable/volumesDatatable.html
app/docker/models/volume.js
app/docker/views/volumes/edit/volume.html

Show Volume Created date column in Volume list
Show Volume Created date field in Volume details

feat(volumes): Show Volume Created column

---

gruntfile.js

Update docker binary to version 18.09.3 for Linux.

feat(dep): update docker binary version to 18.09.3

---

api/http/handler/motd/motd.go
api/portainer.go
app/portainer/models/motd.js
app/portainer/views/home/home.html

feat(api): add support for an externally fetched title for motd

---

build/build_binary_devops.ps1

Fix azuredevops build

---

app/portainer/views/teams/edit/teamController.js

fix(team): fix invalid team leader count

---

app/portainer/components/accessManagement/porAccessManagementController.js

fix(group-access): fix authorize/deny

---

webpack/webpack.common.js

fix(build-system): fix lodash imports

---

app/portainer/services/notifications.js

fix(notifications): fix create user errormessage

---

app/docker/helpers/labelHelper.js

fix(labels): fix labels with blank names assigning

---

app/portainer/views/users/users.html

style(users): fix typo/grammar

---

app/docker/components/host-view-panels/swarm-node-details-panel/swarm-node-details-panel.html
app/portainer/filters/filters.js

fix(node-details): engine labels were displayed as Objects

---

api/http/handler/webhooks/webhook_execute.go

This is to add tag support for webhook calls as a query parameter.
Closes #2752

feat(webhooks): Add Tag Support

---

app/portainer/components/product-list/product-item/productItem.html
app/portainer/views/support/product/product.html

fix(support): enforce minimum purchase amount

---

package.json
yarn.lock

feat(security): update jquery to patched version

---

package.json
webpack/webpack.common.js
yarn.lock

feat(security): remove webpack-bundle-analyzer

---

app/docker/views/containers/create/createcontainer.html

style(container-creation): clarify port mapping

---

app/portainer/services/api/extensionService.js
app/portainer/services/stateManager.js

Remove cached status for extensions but RBAC.

fix(rbac): extensions cache for rbac only

---

.eslintrc.yml
app/config.js
gruntfile.js
webpack/webpack.common.js

Set the anonymizeIP property to `true` for GA.

feat(app): set anonymizeIp property for GA

---

app/app.js

fix(endpoints): always reset agent headers when switching state

---

app/portainer/components/datatables/registries-datatable/registriesDatatable.html
app/portainer/components/datatables/registries-datatable/registriesDatatable.js
app/portainer/views/registries/registries.html
app/portainer/views/registries/registriesController.js

feat(registry): disable browse for quay.io registry

---

app/portainer/components/endpoint-list/endpoint-list-controller.js
app/portainer/components/endpoint-list/endpointList.html
app/portainer/views/home/home.html

Closes #2977 .
Add pagination for endpoints list on homepage.

feat(home): pagination on endpoints list

---

api/bolt/endpoint/endpoint.go
api/http/handler/endpoints/endpoint_list.go
app/extensions/rbac/components/access-viewer/accessViewerController.js
app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
app/portainer/components/endpoint-list/endpoint-list-controller.js
app/portainer/components/endpoint-list/endpoint-list.js
app/portainer/components/endpoint-list/endpointList.html
app/portainer/rest/endpoint.js
app/portainer/rest/transform/getEndpointsTotalCount.js
app/portainer/services/api/endpointService.js
app/portainer/views/auth/authController.js
app/portainer/views/endpoints/endpointsController.js
app/portainer/views/groups/create/createGroupController.js
app/portainer/views/groups/edit/groupController.js
app/portainer/views/home/home.html
app/portainer/views/home/homeController.js
app/portainer/views/init/admin/initAdminController.js
app/portainer/views/schedules/create/createScheduleController.js
app/portainer/views/schedules/edit/scheduleController.js
app/portainer/views/stacks/edit/stackController.js

Frontend part of endpoint backend pagination.
Must be merged before merging #2989

feat(home): front - endpoint backend pagination

---

app/portainer/views/auth/auth.html
app/portainer/views/auth/authController.js

feat(auth): login spinner

---

app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.js
app/portainer/components/datatables/endpoints-datatable/endpointsDatatableController.js
app/portainer/views/endpoints/endpoints.html
app/portainer/views/endpoints/endpointsController.js

Backend pagination for Endpoints View.
Needed for environments with a high number of endpoints.
cc @deviantony

feat(endpoints): backend pagination for endpoints view

---

api/cron/scheduler.go

fix(api): AddCron fix after library update

---

api/cron/scheduler.go

Reverts portainer/portainer#3014

Revert "fix(api): AddCron fix after library update"

---

.github/stale.yml
stale.yml

chore(project): stalebot integration

---

.github/ISSUE_TEMPLATE/Bug_report.md

chore(project): clarify bug template

---

app/docker/views/containers/create/createcontainer.html

style(container-creation): clarify ports mapping

---

app/docker/views/containers/edit/containerController.js

Multiple clics on image commit button were creating a lot of images for the container.
Related to #2442 .

fix(containers): multiple clics on image commit

---

app/docker/views/containers/stats/containerstats.html

style(container-stats): clarify network graph is aggregate

---

.github/stale.yml

chore(project): adjust stalebot config

---

app/docker/components/datatables/containers-datatable/containersDatatableController.js
app/docker/components/datatables/host-jobs-datatable/jobsDatatableController.js
app/docker/components/datatables/images-datatable/imagesDatatableController.js
app/docker/components/datatables/networks-datatable/networksDatatableController.js
app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatableController.js
app/docker/components/datatables/services-datatable/servicesDatatableController.js
app/docker/components/datatables/tasks-datatable/tasksDatatableController.js
app/docker/components/datatables/volumes-datatable/volumesDatatableController.js
app/integrations/storidge/components/drives-datatable/storidgeDrivesDatatableController.js
app/integrations/storidge/components/nodes-datatable/storidgeNodesDatatableController.js
app/portainer/components/access-datatable/accessDatatableController.js
app/portainer/components/datatables/genericDatatableController.js
app/portainer/components/datatables/schedules-datatable/schedulesDatatableController.js
app/portainer/components/datatables/stacks-datatable/stacksDatatableController.js

fix(datatables): default orderby now applied correctly

---

app/portainer/services/localStorage.js

Closes #2932 .
@deviantony cookies have 30 days validity by default. Do we want to set a higher limit date or do we assume that if there is no UI modification (so no cookie update), we reset to default values after 30 days ?

fix(app): UI settings persistency

---

api/docker/client.go

feat(api): bump default Docker library timeout to 60s

---

package.json

fix(security): bump lodash to 4.17.15

---

app/index.html
yarn.lock

Related to #3045 
This PR only changes application loading text.

style(app): update app loading text

---

app/docker/components/datatables/containers-datatable/containersDatatableController.js
app/docker/components/datatables/host-jobs-datatable/jobsDatatableController.js
app/docker/components/datatables/images-datatable/imagesDatatableController.js
app/docker/components/datatables/networks-datatable/networksDatatableController.js
app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatableController.js
app/docker/components/datatables/services-datatable/servicesDatatableController.js
app/docker/components/datatables/tasks-datatable/tasksDatatableController.js
app/docker/components/datatables/volumes-datatable/volumesDatatableController.js
app/integrations/storidge/components/drives-datatable/storidgeDrivesDatatableController.js
app/integrations/storidge/components/nodes-datatable/storidgeNodesDatatableController.js
app/portainer/components/access-datatable/accessDatatableController.js
app/portainer/components/datatables/genericDatatableController.js
app/portainer/components/datatables/schedules-datatable/schedulesDatatableController.js
app/portainer/components/datatables/stacks-datatable/stacksDatatableController.js

Closes #3049 .
Introduced by #3022

fix(datatables): saved orderBy was always overridden by the default one

---

app/portainer/services/localStorage.js
app/portainer/views/auth/authController.js

fix(oauth): okta support

---

app/docker/components/datatables/networks-datatable/network-row-content/networkRowContent.html
app/docker/components/datatables/networks-datatable/network-row-content/networkRowContent.js
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/components/datatables/networks-datatable/networksDatatableController.js
app/docker/views/networks/networksController.js

feat(networks): group networks for swarm endpoints

---

app/docker/views/swarm/visualizer/swarmVisualizerController.js
app/docker/views/swarm/visualizer/swarmvisualizer.html
assets/css/app.css

feat(swarmvisualizer): add labels display under node info

---

api/http/handler/registries/registry_update.go
app/portainer/views/registries/edit/registry.html

fix(api): fix an issue with RegistryUpdate operation

---

api/cmd/portainer/main.go
api/git/git.go

fix(stack): Skip SSL Verification

---

app/docker/rest/service.js
app/docker/services/serviceService.js
app/docker/views/services/edit/service.html
app/docker/views/services/edit/serviceController.js

feat(services): rollback service capability

---

app/docker/views/services/create/createservice.html
app/docker/views/services/edit/includes/mounts.html

fix(services): mounted volumes are now persisted and displayed correctly

---

app/portainer/views/endpoints/create/createEndpointController.js
app/portainer/views/endpoints/create/createendpoint.html

fix(endpoint-creation): clarify docker endpoint

---

api/cron/scheduler.go

refactor(api): update scheduler to match new cron lib API

---

api/docker/snapshot.go
api/docker/snapshotter.go

feat(api): only error on ping failure for snapshots

---

api/http/handler/endpoints/endpoint_create.go

feat(api): prevent endpoint creation with already paired agent

---

build/windows2016/nanoserver/Dockerfile

Related to #3132 
Not closing the original issue as it is a workaround for an issue in Docker.

feat(build-system): remove VOLUME statement from Windows Dockerfile

---

api/http/handler/auth/authenticate.go

fix(api): prevent panic in auth when OAuth is enabled

---

api/exec/extension.go

Add an extra debug log line when enabling extensions.

feat(exec): add DEBUG statement when validating license

---

app/portainer/__module.js
app/portainer/helpers/urlHelper.js
app/portainer/services/authentication.js
app/portainer/services/localStorage.js
app/portainer/views/auth/auth.html
app/portainer/views/auth/authController.js

Closes #2957 .
Closes #2960 .
Fixes 2 bugs caused by legacy code.

fix(auth): authController full rewrite

---

api/http/handler/status/handler.go
api/http/handler/status/status_inspect_version.go
api/portainer.go
app/portainer/models/status.js
app/portainer/rest/status.js
app/portainer/services/api/statusService.js
app/portainer/services/stateManager.js
app/portainer/views/auth/authController.js
app/portainer/views/sidebar/sidebar.html
assets/css/app.css

feat(sidebar): add update notification

---

gruntfile.js

Reverts portainer/portainer#3202

Revert "update docker binary version to 19.03.2"

---

README.md

Adds security info to the readme for Portainer

docs(project): add security info to readme

---

app/docker/views/containers/create/createContainerController.js

This fixes #1645 and relates to #1907.

fix(containers) prevent duplicate MAC addresses (#1645)

---

api/http/proxy/docker_transport.go

fix(api): fix invalid resource control check

---

api/http/handler/stacks/create_compose_stack.go
api/http/handler/stacks/create_swarm_stack.go
api/http/handler/stacks/handler.go
api/http/handler/stacks/stack_create.go
api/http/server.go
app/portainer/views/stacks/create/createStackController.js

fix(api): prevent the use of bind mounts in stacks if setting enabled

---

api/http/proxy/docker_transport.go

fix(api): add access validation for agent browse requests

---

app/__module.js
app/libraries/isteven-angular-multiselect/.npmignore
app/libraries/isteven-angular-multiselect/LICENSE.txt
app/libraries/isteven-angular-multiselect/README.md
app/libraries/isteven-angular-multiselect/isteven-multi-select.css
app/libraries/isteven-angular-multiselect/isteven-multi-select.js
app/libraries/isteven-angular-multiselect/package.json
app/portainer/services/modalService.js
app/vendors.js
package.json
yarn.lock

security(app): xss vulnerabilities

---

api/cmd/portainer/main.go

fix(authentication): trim the newline character from the password string

---

api/bolt/datastore.go
api/bolt/migrator/migrate_dbversion19.go
api/bolt/migrator/migrator.go
api/portainer.go
app/portainer/components/forms/schedule-form/schedule-form.js

Related to https://github.com/portainer/portainer/issues/3007

fix(api): fix an issue with unsupported cron format

---

build/build_binary_azuredevops.ps1

cc @ssbkang I have 0 clue with this seems to fix the issue.

fix(build-system): fix build system on CI for Windows

---

app/docker/views/containers/edit/container.html

Closes: #2924
I have added code from line 236 to 239 which shows the Entrypoint details of a container.

feat(container-details): add entrypoint to container details view

---

app/extensions/registry-management/components/registries-repositories-datatable/registryRepositoriesDatatable.html

fix(registry): remove checkboxes on repositories list

---

app/extensions/registry-management/_module.js
app/extensions/registry-management/components/registries-repository-tags-datatable/registriesRepositoryTagsDatatable.html
app/extensions/registry-management/models/registryImageDetails.js
app/extensions/registry-management/models/registryImageLayer.js
app/extensions/registry-management/views/repositories/tag/registryRepositoryTag.html
app/extensions/registry-management/views/repositories/tag/registryRepositoryTagController.js

feat(registry): inspect repository images

---

api/bolt/internal/db.go

This change fixes #2633 as tested in our production environment.

fix(api): increment stack identifier atomically

---

app/portainer/views/endpoints/edit/endpoint.html
app/portainer/views/endpoints/edit/endpointController.js

feat(endpoint-details): add edge-key to commands

---

api/authorizations.go

fix(api): update user authorizations after team deletion

---

api/bolt/migrator/migrate_dbversion20.go
api/bolt/migrator/migrator.go
api/portainer.go

fix(api): data migration to update default Portainer authorizations

---

api/http/proxy/docker_transport.go

Reverts portainer/portainer#3225

Revert "fix(api): fix invalid resource control check"

---

api/authorizations.go
api/bolt/init.go
api/bolt/migrator/migrate_dbversion20.go
api/portainer.go

fix(api): introduce priority based logic for RBAC roles

---

app/portainer/views/templates/templates.html

feat(templates): replace volume selector with typeahead

---

app/docker/views/containers/edit/container.html

fix(container): hide opts when autoremove true

---

app/app.js
app/portainer/__module.js
app/portainer/services/authentication.js
app/portainer/services/stateManager.js
app/portainer/views/auth/authController.js

fix(app): permissions lost for UI on browser refresh

---

app/docker/views/containers/create/createContainerController.js

fix(container-creation): match container_network by id

---

app/docker/services/networkService.js
app/docker/views/containers/create/createContainerController.js
webpack/webpack.common.js

fix(container-creation): preserve network aliases

---

app/portainer/services/localStorage.js
app/portainer/views/auth/authController.js

fix(auth): clean browser cache on logout

---

app/docker/views/containers/create/createContainerController.js

preserve `null` value of network aliases if set as such

fix(container-creation): preserve aliases if null

---

api/http/proxy/factory/docker/transport.go

Fix an issue preventing users with the endpoint administrator role to browse volumes.

fix(http): update volume browsing validation

---

app/portainer/views/about/about.html

Part of suggested implementation to solve analytics topic, more work is still required

feat(about): add analytics notice

---

app/docker/services/imageService.js

fix(registry-selector): unique images in auto suggest

---

api/http/handler/auth/authenticate.go
api/http/handler/auth/authenticate_oauth.go
api/http/handler/auth/handler.go
api/http/server.go

fix(api): trigger an authorization update after auto-provisioning users

---

app/docker/models/config.js

atob only support decode ascii char, when this unicode in config, it will show unknown char.
Closes #3439

fix: atob convert unicode in config failed

---

.github/ISSUE_TEMPLATE/Bug_report.md

chore(project): require Portainer logs

---

api/http/proxy/factory/docker/containers.go

fix(UAC): rewrite container inheritance logic

---

app/portainer/views/endpoints/edit/endpoint.html
app/portainer/views/endpoints/edit/endpointController.js

refactor(endpoint-creation): remove unneeded port

---

app/portainer/views/stacks/create/createstack.html

refactor(stack-creation): add note for 2FA

---

app/docker/views/containers/create/createContainerController.js
app/docker/views/containers/create/createcontainer.html

Closes #2726 
I've added 2 fields and forwarded values to container configuration.
Checked that it works both for create/edit scenarios:
Results in:
```bash
$ docker inspect test -f '{{.HostConfig.Dns}}'
[1.1.1.1]
```
Should I add something, like docs? Not sure where to look for required changes, would be grateful for pointing out.

feat: add setting to change DNS servers

---

app/portainer/components/accessControlForm/porAccessControlFormController.js
app/portainer/components/accessControlPanel/porAccessControlPanelController.js
app/portainer/components/accessManagement/porAccessManagementController.js
app/portainer/views/teams/teamsController.js
app/portainer/views/users/usersController.js

feature(UX): sort dropdowns alphabetically

---

app/extensions/oauth/components/oauth-settings/oauth-settings.html
app/portainer/components/access-datatable/accessDatatable.html
app/portainer/components/accessControlForm/porAccessControlForm.html
app/portainer/components/accessControlPanel/porAccessControlPanel.html
app/portainer/components/accessManagement/porAccessManagement.html
app/portainer/components/forms/template-form/templateForm.html
app/portainer/views/users/users.html

refactor(UX): fix grammar

---

api/docker/client.go
api/http/proxy/factory/docker/configs.go
api/http/proxy/factory/docker/secrets.go
api/http/proxy/factory/docker/transport.go

fix(client): lower API for backwards support

---

app/docker/components/datatables/networks-datatable/network-row-content/networkRowContent.html
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/components/datatables/services-datatable/servicesDatatable.html

fix(UX): prevent task expand on row selection

---

app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.html
app/docker/components/datatables/networks-datatable/network-row-content/networkRowContent.html
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/views/services/edit/includes/configs.html
app/docker/views/services/edit/includes/constraints.html
app/docker/views/services/edit/includes/containerlabels.html
app/docker/views/services/edit/includes/environmentvariables.html
app/docker/views/services/edit/includes/hosts.html
app/docker/views/services/edit/includes/logging.html
app/docker/views/services/edit/includes/mounts.html
app/docker/views/services/edit/includes/placementPreferences.html
app/docker/views/services/edit/includes/ports.html
app/docker/views/services/edit/includes/resources.html
app/docker/views/services/edit/includes/servicelabels.html
app/docker/views/services/edit/service.html
app/extensions/rbac/directives/disable-authorization.js

refactor(UX): disable/remove uneeded UI elements

---

app/portainer/views/settings/authentication/settingsAuthentication.html
app/portainer/views/settings/authentication/settingsAuthenticationController.js

frontend changes to fix #3443 
API changes will probably still be needed

fix(authentication): frontend changes

---

app/portainer/views/templates/templates.html

fix(template-creation): select volume name not object

---

app/docker/components/datatables/networks-datatable/network-row-content/networkRowContent.html
app/docker/components/datatables/networks-datatable/networksDatatable.html

Patch formatting of networks datatable for helpdesk users using dropdown

fix(networks): patch datatable

---

build/build_binary_azuredevops.ps1

fix(build): Remove -ErrorAction:SilentlyContinue

---

api/go.mod
api/go.sum

fix(dependencies): bump go-winio lib

---

app/portainer/components/product-list/product-item/productItem.html
app/portainer/views/support/product/product.html
app/portainer/views/support/product/productController.js

feat(support): add new offerings

---

app/docker/components/datatables/containers-datatable/containersDatatableController.js

fix(containers): do not persist container status filter

---

app/portainer/views/support/product/product.html
app/portainer/views/support/product/productController.js

feat(support): make support type dynamic

---

api/http/handler/endpoints/endpoint_list.go

feat(endpoints): filter by endpoint type

---

app/docker/components/datatables/services-datatable/servicesDatatable.html

Fixes #3652
Prevents replica count from being set below zero and causing an error.

fix(services): enforce minimum replica count of 0

---

api/http/handler/settings/settings_update.go
api/portainer.go
app/portainer/models/settings.js
app/portainer/services/stateManager.js
app/portainer/views/settings/settings.html
app/portainer/views/settings/settingsController.js
app/portainer/views/sidebar/sidebar.html

Introduce a new setting to enable Edge compute features

---

api/http/handler/edgegroups/edgegroup_create.go
api/http/handler/edgegroups/edgegroup_update.go
api/http/handler/edgegroups/handler.go

fix(edge-groups): associate groups only with edge endpoints

---

api/http/handler/settings/settings_public.go
app/portainer/models/settings.js

fix(edge-compute): load edge compute setting on public setting

---

api/http/handler/edgegroups/edgegroup_create.go

fix(edge-groups): provide defaults for edge group

---

api/http/handler/endpoints/endpoint_list.go
app/portainer/services/api/endpointService.js
app/portainer/views/endpoints/endpointsController.js
app/portainer/views/home/homeController.js

feat(endpoints): filter by ids and/or tag ids

---

api/portainer.go

refactor(project): sort portainer types and interface definitions

---

api/http/handler/edgegroups/associated_endpoints.go
api/http/handler/edgegroups/edgegroup_create.go
api/http/handler/edgegroups/edgegroup_inspect.go
api/http/handler/edgegroups/edgegroup_list.go
api/http/handler/edgegroups/edgegroup_update.go
api/http/handler/edgegroups/handler.go
api/portainer.go
app/edge/components/group-form/groupForm.html
app/edge/views/groups/create/createEdgeGroupViewController.js
app/portainer/components/forms/schedule-form/scheduleForm.html
app/portainer/components/multi-endpoint-selector/multiEndpointSelector.html

feat(edge-groups): Provide a switch to use AND or OR for tags

---

api/http/handler/edgestacks/edgestack_file.go
api/http/handler/edgestacks/handler.go
app/edge/components/edge-stack-endpoints-datatable/edgeStackEndpointsDatatable.html
app/edge/components/edge-stack-endpoints-datatable/edgeStackEndpointsDatatable.js
app/edge/components/edge-stack-endpoints-datatable/edgeStackEndpointsDatatableController.js
app/edge/components/edit-edge-stack-form/editEdgeStackForm.html
app/edge/components/edit-edge-stack-form/editEdgeStackForm.js
app/edge/components/edit-edge-stack-form/editEdgeStackFormController.js
app/edge/rest/edge-stacks.js
app/edge/services/edge-stack.js
app/edge/views/edge-stacks/edit/editEdgeStackView.html
app/edge/views/edge-stacks/edit/editEdgeStackViewController.js

feat(edge-stacks) edit edge stack view

---

api/http/handler/edgegroups/edgegroup_delete.go
api/http/handler/edgegroups/edgegroup_list.go
api/http/handler/edgegroups/handler.go
api/http/server.go
app/edge/components/groups-datatable/groupsDatatable.html
app/edge/components/groups-datatable/groupsDatatable.js
app/edge/components/groups-datatable/groupsDatatableController.js

feat(edge-groups) prevent deletion of edge group used by an edge stack

---

app/portainer/models/template.js
app/portainer/services/api/templateService.js

feat(templates): support templates versioning

---

app/edge/components/groups-datatable/groupsDatatable.html

feat(edge-groups): add inuse tag

---

api/http/handler/edgestacks/edgestack_update.go
app/edge/views/edge-stacks/edit/editEdgeStackViewController.js

feat(edge-stack): update stack version when stack file is changed

---

build/linux/alpine.Dockerfile

feat(project): add alpine based Dockerfile

---

app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.html
app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.js
app/docker/components/datatables/container-networks-datatable/containerNetworksDatatableController.js
app/docker/components/datatables/containers-datatable/containersDatatable.html
app/docker/components/datatables/networks-datatable/network-row-content/networkRowContent.html
app/docker/components/datatables/networks-datatable/networksDatatable.html
app/docker/helpers/containerHelper.js
app/docker/helpers/networkHelper.js
app/docker/views/containers/create/createcontainer.html
app/docker/views/containers/edit/container.html
app/docker/views/networks/create/createNetworkController.js
app/docker/views/networks/create/createnetwork.html
app/docker/views/networks/edit/network.html
app/docker/views/networks/edit/networkController.js
app/docker/views/networks/networksController.js
app/docker/views/services/create/createServiceController.js

feat(networks): add ipv6 support

---

app/edge/components/group-form/groupForm.html
app/edge/components/group-form/groupForm.js
app/edge/components/group-form/groupFormController.js
app/edge/views/groups/create/createEdgeGroupView.html
app/edge/views/groups/create/createEdgeGroupViewController.js
app/edge/views/groups/edit/editEdgeGroupView.html
app/edge/views/groups/edit/editEdgeGroupViewController.js
app/portainer/components/forms/group-form/groupForm.html
app/portainer/components/group-association-table/group-association-table.js
app/portainer/components/group-association-table/groupAssociationTable.html

feat(edge-groups) replace multi endpoints selector

---

app/docker/views/networks/create/createNetworkController.js

feat(networks): remove the ability to create host network

---

api/go.mod
api/go.sum
api/ldap/ldap.go

feat(api): bump ldap library version

---

app/edge/components/group-form/groupForm.html
app/edge/components/group-form/groupFormController.js
app/edge/views/groups/edit/editEdgeGroupView.html
app/edge/views/groups/edit/editEdgeGroupViewController.js

feat(edge-groups): add dynamic group endpoints table

---

app/edge/views/edge-stacks/edit/editEdgeStackViewController.js

fix(edge-stacks): update version when updating stack files

---

app/portainer/views/endpoints/edit/endpoint.html
app/portainer/views/endpoints/edit/endpointController.js

close #3792 
moved the docker commands to the controller and using string templates

fix(endpoints): show line breaks in edge run commands

---

api/http/proxy/factory/docker/transport.go
api/http/proxy/factory/docker/volumes.go
app/docker/rest/volume.js

fix(volumes): add unicity check on volumes
